### ISSUE TITLE
LightSwitch: isDarkOS is not a widget function

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#1004]
https://www.primefaces.org/showcase-ext/sections/lightSwitch/jsAPI.jsf

jsAPI.jsf:25 Uncaught TypeError: PF(...).isDarkOS is not a function

**Comment by melloware** [comment]
Good catch

**Comment by jepsar** [comment]
@melloware shall we update the showcase? Or reintroduce the function? I would say update the showcase.

Commit with the removal https://github.com/primefaces-extensions/primefaces-extensions/commit/4f245cabd619ccc2b3ee866b33768b7c0a83efd3

**Comment by melloware** [comment]
Yeah its been removed so we should just update the showcase.

**Comment by melloware** [comment]
I removed it!
