### ISSUE TITLE
Orgchart: Version Update (from 2.1.9 to 2.2.0)

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions#1017]
### Describe the feature you would like to see added

Summary: Update orgchart version from 2.1.9 (orgchart repo: https://github.com/dabeng/OrgChart/releases/tag/v2.1.9, primefaces extensions commit: https://github.com/primefaces-extensions/primefaces-extensions/commit/f8409a07bfcb2b4379873e687698697b5247960a) to 2.2.0. 

Customized changes:
1. apply version number similar to https://github.com/primefaces-extensions/primefaces-extensions/commit/a80aaaac3e8aef86fec2fe19f830fc0739215b5c
2. apply self closing tag similar to https://github.com/primefaces-extensions/primefaces-extensions/commit/b030e14901b91982355dc5e157c2d84bba070711#diff-e551daa4dcf759a354eda411d536e9647f1823a89c012ca30342cbe271938939
3. remove jquery deprecated function similar to https://github.com/primefaces-extensions/primefaces-extensions/commit/6f5f2338339bc23d167cd2b0e8a635930e79f998

Ultimately we would like to update the orgchart version to the latest (as of today: https://github.com/dabeng/OrgChart/releases/tag/v3.1.4). However, I noticed the latest version is not compatible and the style is off. In that case, it should be more realistic to update to the latest v2 before moving to v3 orgchart giving some time to troubleshoot the breaking changes in v3.

**Comment by melloware** [comment]
I will release 12.0.3 this week!

**Comment by jxmai** [comment]
Great! Thanks.

**Comment by melloware** [comment]
12.0.3 should be in Maven Central in the next hour or two.

**Comment by jxmai** [comment]
https://mvnrepository.com/artifact/org.primefaces.extensions/primefaces-extensions/12.0.3
![Screen Shot 2023-01-04 at 6 08 21 PM](https://user-images.githubusercontent.com/10467831/210673148-1529598e-afc3-42f0-bf57-5bec0d668ce7.png)


I haven't seen 12.03 yet. Probably take some time to sync🤔 

https://mvnrepository.com/artifact/org.primefaces.extensions/primefaces-extensions

**Comment by melloware** [comment]
It there. That repository search you are using is an old and bad one

See: https://repo1.maven.org/maven2/org/primefaces/extensions/primefaces-extensions/

It's there. I am already using it.

**Comment by jxmai** [comment]
Ah, I see. Got it. Thanks!

**Comment by jepsar** [comment]
It's not old and bad, but indeed it needs time to sync. Also I find the security issues very useful there. See for example

https://mvnrepository.com/artifact/org.primefaces/primefaces/5.0

<img width="518" alt="Screenshot 2023-01-05 at 11 27 08" src="https://user-images.githubusercontent.com/7500178/210758673-8fc2071e-0378-419b-b5ee-6d1238f935bd.png">

**Comment by melloware** [comment]
I guess. To me if it doesn't update immediately it's no good for reasons just like above.  I always use Maven Central Search.
