### ISSUE TITLE
Timer: Initialized at zero -> counts down to -1

### ISSUE THREAD

**Issue by mschink** [primefaces-extensions/primefaces-extensions#1047]
### Describe the bug

A really simple timer like 

```
<h:form id="timer">
    <pe:timer timeout="0"/>
</h:form>
```

counts down to -1 and stalls. As time doesn't make sense as a negative value, I am reporting this as a bug.

```
<h:form id="timer">
    <pe:timer format="mm:ss" timeout="0"/>
</h:form>
```

This timer counts "down" to but goes to 59:59 and then stalls.

P.S. I am actually calling something like #{bean.getTimeRemaining()} to initialize the timer, but this example is cleaner to reproduce the issue.

Reproducer: https://github.com/mschink/primefaces-timer-issue

### Reproducer

Run it normally - the only change is I added a pe:timer to test.xhtml

Reproducer: https://github.com/mschink/primefaces-timer-issue

### Expected behavior

The timer should not count down past zero. It should check if it's currently at zero, and if so, not decrement. Negative values seem to show wrong remaining times.

### PrimeFaces Extensions version

12.0.0

### JSF implementation

MyFaces

### JSF version

2.3

**Comment by melloware** [comment]
Thanks for the report!  I will fix it.

**Comment by melloware** [comment]
Can I ask what is the expected behavior of `0` ? Because i could see it never starting the timer?

**Comment by mschink** [comment]
I see the timer initialized at 0 or 00:00 and then they count down to -1 or 59:59. Do they start at -1 and 59:59 for you?

**Comment by melloware** [comment]
Yes what I am asking is what do you think the behavior should be if timeout="0"??  the counter never starts??  Since there is nothing to count down?

**Comment by mschink** [comment]
I think the best way to implement it, without breaking any expected behavior, would be to let it start but to not allow negative values returned.

Example: onstart, onsuccess, oncomplete, exist to let the developer listen to different phases and do something accordingly. I guess its possible someone wants to trigger an event once it reached zero, even if it started at zero. So, if the timer never started at all, this might break some of their expectations.

Is that an easy fix? I could not track down the related part of code that updates the value.

**Comment by melloware** [comment]
yeah i think i can fix it pretty easy.  So basically this would happen..

1. 0 timer basically means start and call the `onStart` etc but never count negative.
2. So basically this is a fire immediately and stop the counter.

**Comment by mschink** [comment]
Makes sense to me. If you want to see something interesting, set the interval to 400ms or less. You'll see that sometimes it goes negative and sometimes doesn't based on when you refresh the page.

But if your fix does the trick, no need to look into that!

**Comment by melloware** [comment]
Yep I will hopefully have something for you tomorrow.

**Comment by melloware** [comment]
OK can you try this patched reproducer:
[pfe-1047.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/10557488/pfe-1047.zip)

```js
if (PrimeFaces.widget.ExtTimer) {
    PrimeFaces.widget.ExtTimer.prototype.start = function() {
        var $this = this;
        this.prevTime = this.currentTimeInSecs();

        if ($this.originalTimeout <= 0) {
            if ($this.cfg.listener) {
                $this.cfg.listener();
            }
            if ($this.cfg.ontimercomplete) {
                $this.cfg.ontimercomplete();
            }
            if ($this.cfg.singleRun) {
                $this.pause();
            } else {
                $this.currentTimeout = $this.forward ? 0 : $this.originalTimeout;
                $this.print();
            }
            return;
        }


        if (!this.interval) {
            this.interval = setInterval(function() {
                $this.doStep();

                var end = $this.forward ? $this.currentTimeout >= $this.originalTimeout : $this.currentTimeout <= 0;

                if (end) {
                    if ($this.cfg.listener) {
                        $this.cfg.listener();
                    }
                    if ($this.cfg.ontimercomplete) {
                        $this.cfg.ontimercomplete();
                    }
                    if ($this.cfg.singleRun) {
                        $this.pause();
                    } else {
                        $this.currentTimeout = $this.forward ? 0 : $this.originalTimeout;
                        $this.print();
                    }
                }
            }, $this.cfg.interval);
        }

    }
}
```

**Comment by melloware** [comment]
OK I completely refactored this JS code to not only fix this bug but clean up some duplication of code!

Fixed for 12.0.4

**Comment by mschink** [comment]
that's awesome - what is the release schedule for 12.0.4?

thanks for all your help!

**Comment by melloware** [comment]
i will do a 12.0.4 probably in the next week or so i want to look into one more issue.
