### ISSUE TITLE
Quarkus Extension

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1062]
I think I need to make a PFE/PF Quarkus Extension here.

I have too much PF specific stuff in the OmniFaces Quarkus Extension I think I need to move here to its own extension.

See: https://github.com/quarkiverse/quarkus-omnifaces/blob/b2c1c8ac9a4fd17ca2299b7fb4e4c5c18c607a56/deployment/src/main/java/io/quarkiverse/omnifaces/deployment/OmnifacesProcessor.java#L175-L180

And in MyFaces Extension:
https://github.com/apache/myfaces/blob/04afd8fed53224caf824563f6e71e489f00f77ff/extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java#L761-L831

**Comment by tandraschko** [comment]
Had a similar Idee months ago
Actually we should create a primefaces-quarkus module too

**Comment by melloware** [comment]
Perfect I will do this one first then PF.

**Comment by melloware** [comment]
@tandraschko i am wondering if I should do them as Quarkiverse extensions becuase we need to keep Quarkus2 branch for EE8 and Quakrus3 branch for EE10 and both PF and PFE aren't really condusive to having both versions?  Would you be OK if I did them there like the OmniFaces one?

**Comment by tandraschko** [comment]
yeah sure
the bridges belong a bit more to quarkus - as both omnifaces/primefaces is actually spec compatible

**Comment by melloware** [comment]
ok cool. I am going to ask The Quarkus guys to set it up.

**Comment by tandraschko** [comment]
perfect
i also thought about myfaces in the past but this is really a bit more "deep" compared to PrimeFAces/Omnifaces

**Comment by melloware** [comment]
agreed and the fact the Myfaces already has 2.3-next and 4.0 branches makes it eaiser.

**Comment by melloware** [comment]
https://github.com/quarkusio/quarkus/issues/31219

**Comment by melloware** [comment]
Working on this getting this error so  iam going to rename the Monaco Editor package to something else.

```
[WARNING] [io.quarkus.arc.deployment.SplitPackageProcessor] Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives:
- "org.primefaces.extensions.model.monacoeditor" found in [org.primefaces.extensions:primefaces-extensions::jar, org.primefaces.extensions:resources-monacoeditor::jar]
```

**Comment by melloware** [comment]
Quarkus Extension for PF and PFE is now live: https://github.com/quarkiverse/quarkus-primefaces
