### ISSUE TITLE
ComponentTraversalUtils.closestForm without argument context

### ISSUE THREAD

**Issue by tuerker** [primefaces-extensions/primefaces-extensions#1074]
### Describe the bug

which is dropped in PF 13.

Occurs in three places. Will fix it and provide a PR.

### PrimeFaces Extensions version

13.0.0

### JSF implementation

None

**Comment by melloware** [comment]
Thomas marked it deprecatde so I will remove it in 13 but leave it in 12 for now as your code should be working again you update your PF snapshot with the latest code as of this morning.
