### ISSUE TITLE
InputPhone: GEO IP lookup showcase not working?

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1080]
### Describe the bug

See:
https://www.primefaces.org/showcase-ext/sections/inputphone/geoIpLookup.jsf

![image](https://user-images.githubusercontent.com/4399574/221915899-3791bf15-fbdf-41db-b8aa-2bd24719263c.png)

### PrimeFaces Extensions version

12.0.4

### JSF implementation

MyFaces

### JSF version

2.3

**Comment by jepsar** [comment]
Works for me.

<img width="884" alt="Screenshot 2023-02-28 at 18 57 05" src="https://user-images.githubusercontent.com/7500178/221939257-353018e2-69bb-4b3c-9f7f-ddc6d2f1e509.png">

**Comment by melloware** [comment]
Got it just tried incognito mode and it works.  It was my Chrome uBlock Origin plugin blocking it.
