### ISSUE TITLE
CKEditor: Removed for licensing reasons

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1106]
We have been contacted by CKEditor owners that we are in license violation.   I respect all software developers and the rights to defend their software and licenses so PFE will be pulling CKEditor from the library.

The only remedy was to purchase a commercial license but as an unfunded open source library that is not an option.  We apologize to all of you currently using CKEditor but I hope you can appreciate CKSource stance on the matter.

**Comment by jepsar** [comment]
For those who bought a license, can we move our code (so excluding the CKEditor files) to a separate repo and provide instructions on how one could add their licensed files and build a legal version of a taglib only containing the editor?

Just an idea.

**Comment by melloware** [comment]
Yeah it will be a complex set of instructions but doable. I don't use this component so if someone wants to write up Wiki instructions that would be great.

**Comment by jepsar** [comment]
Maybe we could even keep the component in and just remove the CKEditor files? Maybe it's enough to add the files to a certain resource folder. Not sure if that's possible. Not a huge priority for me personally.

**Comment by melloware** [comment]
Me neither and for now I just want the fastest way to satisfy CKSource that we are no longer providing this component.

**Comment by fcorneli** [comment]
Seems like they are (also) GPL licensed. Viable way forward: extract the CKEditor JSF component into a separate project and relicense also under GPL. Need permission of PrimeTek for this I guess.
Problem here of course for integrators: you "contaminate" your project with GPL.

**Comment by jepsar** [comment]
@fcorneli I don't know if you are on Discord. Some options have been discussed there. Yours was one of them. If you are interested you read the options there. https://discord.gg/rVT3nzX8 / https://discord.com/channels/787967399105134612/787969344768311296

**Comment by fcorneli** [comment]
@jepsar Thanks, will have a look.
