### ISSUE TITLE
Achieve Pagination For Primefaces Sheet Table

### ISSUE THREAD

**Issue by anatoliaDev** [primefaces-extensions/primefaces-extensions#1170]
### Describe the feature you would like to see added

I would like to use pagination for Primefaces Sheet Table like how normal Primefaces Datatable does. I checked sheet properties to achive any pagination but it has no property to achieve this goal.

### Additional context

https://stackoverflow.com/questions/76162856/how-to-achieve-pagination-for-primefaces-sheet-table

**Comment by melloware** [comment]
HandsonTable does not officially support pagination so its not supported by the PFE Sheet: https://forum.handsontable.com/t/column-sorting-with-pagination/6267
