### ISSUE TITLE
Sheet: Paste into dropdown issue

### ISSUE THREAD

**Issue by anatoliaDev** [primefaces-extensions/primefaces-extensions#1213]
### Describe the bug

There is a problem with pasting data to sheetcolumn ( which are colType = dropdown ) from Excel . Let's say i have this dropdown values.
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/120382772/287090fc-35f5-46fe-9f10-7e070fc561c9)
I can copy dropdown value and can paste from excel  to dropdown(sheetcolumn) as expected if i copy like 
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/120382772/656d3f3a-4f37-411f-aea7-851ed4a31555)
and when paste to excel like 
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/120382772/756c094c-9eca-4866-a343-eebc32a1dbc0)
It's okay so far. If I copy without entering dropdown itself like 
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/120382772/f541696e-42ec-4a8b-8c1e-9a5abf372b71)
It produces in Excel like 
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/120382772/33227324-3311-4081-b937-f4a6965c341c)
When I try to paste this last one(which is in excel) to dropdown(sheetcolumn) it doesn't set value. I mean I can't paste data to sheetcolumn which is dropdown. I can paste to normal input fields. But it doesn't work for dropdowns. What can I do for that ? Thank you

### PrimeFaces Extensions version

12.0.5

### JSF implementation

None

**Comment by melloware** [comment]
Looks like a HandsonTable issue: https://forum.handsontable.com/t/copy-paste-on-cell-type-dropdown/6480

Since we are stuck on HandsonTable 6.2 as their last open source version I doubt this will ever get fixed.
