### ISSUE TITLE
Timer: Handle Chrome/Edge throttling

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1243]
Received word from a professional pentration test that our session countdown timer was not working.  It has worked for years so I was surprised to fail this test.

Turns out in 2021 Chrome/Edge significantly changed the behavior of timers used on "inactive tabs".

See: https://usefulangle.com/web-updates/post/110/chrome-88-will-throttle-timers-1-minute

**Comment by melloware** [comment]
Anywhere you use `window.setInterval`, `windows.setTimeout` you can replace with ...

```js
window.setInterval = PrimeFacesExt.timers.setInterval;
window.setTimeout = PrimeFacesExt.timers.setTimeout ;
window.clearInterval = PrimeFacesExt.timers.clearInterval;
window.clearTimeout = PrimeFacesExt.timers.clearTimeout;
```

**Comment by melloware** [comment]
Just a note if you use CSP with this component or just to use the `setInterval` utitlies standalone you need to modify your CSP policy to allow `worker-src 'self' blob:;`

```xml
<context-param>
    <param-name>primefaces.CSP_POLICY</param-name>
    <param-value>worker-src 'self' blob:; script-src 'self'</param-value>
</context-param>
```

**Comment by jxmai** [comment]
> Anywhere you use `window.setInterval`, `windows.setTimeout` you can replace with ...
> 
> ```js
> window.setInterval = PrimeFacesExt.timers.setInterval;
> window.setTimeout = PrimeFacesExt.timers.setTimeout ;
> window.clearInterval = PrimeFacesExt.timers.clearInterval;
> window.clearTimeout = PrimeFacesExt.timers.clearTimeout;
> ```

Hello @melloware . If I understand correctly, the workaround is to prevent timer from stopping due to browser tab inactivity. 

However, I don't see `PrimeFacesExt.timers` can be called from browser directly since it should be undefined.

Let's go to showcase for example, https://www.primefaces.org/showcase-ext/views/home.jsf

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/10467831/cc659bbc-ff49-4cdd-8fbc-12e00b160ce9)

Anything I missed here? :thinking:

**Comment by melloware** [comment]
That showcase is old. PrimeTek has not deployed the latest yet.

**Comment by jxmai** [comment]
Make sense. The commit (https://github.com/primefaces-extensions/primefaces-extensions/commit/6c466f44af2ae485d7dee53a8a4e5595749b5376) was done  in June, 2023 while the showcase build time was in April, 2023.

**Comment by melloware** [comment]
I have been using this code in production and we have proved it solved our issue where a Pen tester was leaving a tab in the background and our timer was not logging them because Chrome slowed the timers down. 😄

**Comment by jxmai** [comment]
Yes, that's a good catch since this kind of issue might be non-trivial to discover. The tab inactivity throttling makes more sense in mobile devices but if that applies to all browsers including those in desktop devices, having the workaround to make sure the timer is accurate is really nice.

**Comment by melloware** [comment]
@jxmai latest showcase deployed!  https://www.primefaces.org/showcase-ext/views/home.jsf

**Comment by jxmai** [comment]
Thanks for letting me know! PrimeFacesExt.timers exists now 👍
