### ISSUE TITLE
Document Viewer: Unable to load cmap

### ISSUE THREAD

**Issue by fukumotyo** [primefaces-extensions/primefaces-extensions#1248]
### Describe the bug

When viewing a PDF with no embedded fonts, the requested CMap resource path is incorrect.
A resource path such as "/jakarta.faces.resource/web/cmaps/Adobe-Japan1-UCS2.bcmap" is requested, but a 404 error occurs.

### PrimeFaces Extensions version

12.0.8

### JSF implementation

None

**Comment by melloware** [comment]
Do you have an example PDF I can test with?

**Comment by fukumotyo** [comment]
Please check the PDF at the URL below.
https://www.courts.go.jp/app/files/hanrei_jp/097/075097_hanrei.pdf

**Comment by melloware** [comment]
Thanks that will help me debug it!

**Comment by melloware** [comment]
Thanks fixed in 12.0.9 and 13.0.0.  12.0.9 should be in Maven Central in a couple of hours
