### ISSUE TITLE
Layout: updates don't work properly

### ISSUE THREAD

**Issue by yennor** [primefaces-extensions/primefaces-extensions#125]
I'm implementing an SPA (single page application) using the pe:layout component.
I'm using Primefaces 8 and Primefaces extensions 8
So the content of the layoutPanes need to be updated using ajax requests while the application runs.
So the whole construct looks more or less like that:
```
<h:form id="mainForm">
  <pe:layout fullPage="true" id="layout">
    <pe:layoutPane position="north">
    </pe:layoutPane>
    <pe:layoutPane position="west">
    </pe:layoutPane>
    <pe:layoutPane position="center">
      <ui:include src="#{indexView.centerView}" />
    </pe:layoutPane>
</h:form>
```
So now I want to update the center pane. I do that by updating the payoutPane element:
```
<p:menuitem value="User"
  actionListener="#{indexView.showSettingsUser}"
update=":mainForm:center" />
```
When I do that, the center pane gets updated. But it gets moved to the top of the screen. Beeing displayed over the north pane.

So I try to update the whole layout component:
```
<p:menuitem value="User"
  actionListener="#{indexView.showSettingsUser}"
update=":mainForm:layout" />
```
When I do that, absolutely nothing happns.
The only way that seems to work is updating everything at once:
```
<p:menuitem value="User"
  actionListener="#{indexView.showSettingsUser}"
update=":mainForm" />
```

**Comment by melloware** [comment]
going to close this for now as workaround has been provided.
