### ISSUE TITLE
ImageAreaSelect: weird styling with selection

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#1250]
### Describe the bug

See https://www.primefaces.org/showcase-ext/sections/imageAreaSelect/basicSelection.jsf

<img width="530" alt="Screenshot 2023-07-04 at 13 04 11" src="https://github.com/primefaces-extensions/primefaces-extensions/assets/7500178/7485521c-fa7c-429b-a369-8ffdfc512348">

### Reproducer

Go to the showcase (link above) and select a part of the image.

### Expected behavior

I think the selection should look normal, and the unselected part of the image should be darkened.

### PrimeFaces Extensions version

12.0.7

### JSF implementation

None

### Browser(s)

Chrome 114.0.5735.198 (Official Build) (arm64) macOS

**Comment by melloware** [comment]
I have to admit I have never used this component!  I wonder how long this has been broken?

**Comment by jepsar** [comment]
I will have a look in that case.

**Comment by melloware** [comment]
I can take a look too just giving you a heads up I am definitely not going will versed in this one! 😀

**Comment by melloware** [comment]
The line causing the issue is this one.

```js
                borderWidth: selection.y1 + 'px ' +
                    (imgWidth - selection.x2) + 'px ' +
                    (imgHeight - selection.y2) + 'px ' +
                    selection.x1 + 'px'
```
