### ISSUE TITLE
Jakarta version missing sources.jar

### ISSUE THREAD

**Issue by morvael** [primefaces-extensions/primefaces-extensions#1254]
### Describe the feature you would like to see added

Using version with "jakarta" classifier causes problems for my IDE, as it can't download javadoc and sources for it. You release only files with classifiers "sources" and "javadoc" which work only for no-classifier version of the library. Tested on my Nexus jakarta version supplementary files should have "jakarta-sources" and "jakarta-javadoc" classiffiers to be read by IDE. Not sure if this is my IDE problem or you're breaking Maven naming standards here (or not uploading relevant files)?

**Comment by melloware** [comment]
It looks like PrimeFaces has jakarta.jar and jakarta-sources.jar but no JAVADOC jar.

https://repo1.maven.org/maven2/org/primefaces/primefaces/12.0.0/

But PFE is missing the jakarta-sources.jar you are right!

https://repo1.maven.org/maven2/org/primefaces/extensions/primefaces-extensions/12.0.9/

**Comment by melloware** [comment]
Hmmm when I add `<createSourcesJar>true</createSourcesJar>` which is what PF does it is generating the new JAR but its empty.

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/cb10287d-8f6f-4d29-a2fd-06d2b0afcaf2)

**Comment by melloware** [comment]
PrimeFaces actually SHADES the JAR first which is the only difference as PFE doesn't need to do that step.  I don't know whether this is a SHADE plugin bug or just something that is not supported because we are just transforming to "jakarta" version and want the sources generated. cc @tandraschko in case he might know?

**Comment by morvael** [comment]
Yes, recently PF itself was improved and has jakarta-sources. Sadly javadoc is still only vanilla. I'd rather see the library have version X.X.X.jakarta and don't use classifiers and provide standard X.X.X.jakarta-sources and X.X.X.jakarta-javadoc files.

**Comment by melloware** [comment]
Yep but since we have to support JSF 2.2,2.3 and not just 4.0 the only way to do that is to have separate branches like OmniFaces does.  Since both codebases are so large we have been hesitant to do that but it may come to that sooner than later as Faces 4.0 becomes more and more popular.

**Comment by morvael** [comment]
Not a big issue, I just rename the artifacts (PF Elite) when uploading to local Nexus. Just wanted to signal this naming problem. I can live without sources and javadoc pulled for extensions for a long time.

**Comment by melloware** [comment]
fixed the sources JAR for next release!
