### ISSUE TITLE
MonacoEditor: fails to load with primefaces.HIDE_RESOURCE_VERSION=true

### ISSUE THREAD

**Issue by betimbryma** [primefaces-extensions/primefaces-extensions#1265]
### Describe the bug

Hi everyone! I am trying to use monaco editor, but I am having issues. The problem is a problem when primefaces.HIDE_RESOURCE_VERSION is set to true. Then the following code will not work:

`PrimeFaces.resources || (PrimeFaces.resources = {
    getFacesResource: function(a, c, b) {
        0 === a.indexOf("/") && (a = a.substring(1, a.length));
        var d = PrimeFaces.resources.getResourceScriptURI()
          , e = PrimeFaces.resources.getResourceScriptName(d);
        d = d.replace(e, a);
        e = "ln\x3d" + RegExp("[?\x26]([^\x26\x3d]*)ln\x3d(.*?)(\x26|$)").exec(d)[2];
        a = "";
        -1 < d.indexOf("?" + e) || -1 < d.indexOf("\x26" + e) || (a = (new RegExp("[?\x26]([^\x26\x3d]+)" + e + "($|\x26)")).exec(d)[1]);
        d = d.replace(a + e, a + "ln\x3d" + c);
        b && (c = (new RegExp("[?\x26]" + a + "v\x3d([^\x26]*)")).exec(d)[1],
        d = d.replace(a + "v\x3d" + c, a + "v\x3d" + b));
        b = window.location.protocol + "//" + window.location.host;
        return 0 <= d.indexOf(b) ? d : b + d
    },`

Because `b && (c = (new RegExp("[?\x26]" + a + "v\x3d([^\x26]*)")).exec(d)[1],` expects a version in the variable d in the form of "v=...", and there won't be any version in the scripts, so then we get a TypeError when we try to access it via `[1]`, as seen in the browser console:

`[MonacoEditor] Failed to initialize monaco editor TypeError: Cannot read properties of null (reading '1')
    at Object.getFacesResource (core.js?ln=primefaces:103:518)`.
    

### Reproducer

I have reproduced this issue also using the primefaces test, please find it attached to this issue. The server can be started using "mvn clean jetty:run -Pmyfaces40", and the page [[http://localhost:8080/primefaces-test](http://localhost:8080/primefaces-test%3C/strong%3E)](http://localhost:8080/primefaces-test) expects to render a monacoEditor, however that cannot happen, because in console an Error can be seen, that it is not working.
[primefaces-test.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/12237434/primefaces-test.zip)

### Expected behavior

The page should show the Monaco Editor, however it cannot render it, because it expects to have a version of primefaces-extensions in the script, however that will not work when primefaces.HIDE_RESOURCE_VERSION is set to true,

### PrimeFaces Extensions version

12.0.9

### JSF implementation

None

### JSF version

4.0.2

**Comment by melloware** [comment]
I never liked the HIDE_RESOURCE_VERSION you can read here why i think its a useless feature that DOES NOT make you more secure: https://github.com/primefaces/primefaces/issues/9138

**Comment by betimbryma** [comment]
Thanks for the info, yes I agree that it does not make it more secure, however the pen-testers will not remove it from the findings, which is then visible in the certificate.

**Comment by melloware** [comment]
issue is right here: https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/resources/META-INF/resources/primefaces-extensions/monacoeditor/01-monaco-helper.js#L228

cc @blutorange

**Comment by jepsar** [comment]
Pen-testing is a strange business. They will always come up with something new. Even if it is irrelevant, it just does not look good in the report, and you will have to explain it to management / the client.

We had a recent pen-test and they did not mention resource versions. It's no absolute science.

**Comment by blutorange** [comment]
Hmm, is this a general problem with `PrimeFaces.resources.getFacesResource` when no version is present? Seems like that function needs to be adjusted to work when no version is present or given?

But yeah, we too did have our fair share of customers that just look at some automatic report and want it to be clean. Of course, some tool not finding an issue does not mean you are actually safe, which is sometimes easy to forget.

**Comment by melloware** [comment]
Yep I bet CKEditor which usesd to use this function as well is probably broken but that is no longer a concern as we dropped it. I will have to look if that function is used elsewhere.

**Comment by betimbryma** [comment]
Just FYI guys, it works also when some random number is provided in primefaces.RESOURCE_VERSION.

**Comment by blutorange** [comment]
> I will have to look if that function is used elsewhere.

We use that function in our application, but we don't enable `HIDE_RESOURCE_VERSION`, so it's working fine (although it's probably just a matter of time until somebody asks us to hide the version as well...)

**Comment by melloware** [comment]
Because this is not worth fixing I am just logging a Development WARNING for MonacoEditor:

```java
        boolean hideResourceVersion = PrimeRequestContext.getCurrentInstance(context).isHideResourceVersion();
        if (hideResourceVersion) {
            logDevelopmentWarning(context, "Monaco Editor requires a resource version to work properly and '" +
                        Constants.ContextParams.HIDE_RESOURCE_VERSION + "' is currently configured.");
        }
```
