### ISSUE TITLE
SunEditor: Dialog and rendering issues

### ISSUE THREAD

**Issue by maroswal** [primefaces-extensions/primefaces-extensions#1275]
### Describe the bug

Depending on the version the `z-index` of `.sun-editor .se-wrapper` has been increased to `9999` or `1002`, but the `z-index` of `.sun-editor .se-toolbar` hasn't been increased and therefore the toolbar drop-downs will be hidden behind the content.

primefaces-extensions:13.0.0:
```
/* Ensure the editor can receive input in dialog */
.sun-editor .se-wrapper {
   z-index: 9999 !important;
}
```

Most recent version:
```
.ui-dialog-content .sun-editor .se-wrapper {
    z-index: 1002 !important;
}
```

Illustration of the problem:
<img width="727" alt="image" src="https://github.com/primefaces-extensions/primefaces-extensions/assets/235657/e56ebd27-cd9d-4d1e-a6a0-b7010b5e3a25">

### Expected behavior

Toolbar drop-downs should have a higher `z-index` than the editor content.

### PrimeFaces Extensions version

13.0.0

### JSF implementation

All

### JSF version

2.3

**Comment by melloware** [comment]
cc @stolp @MattSho

**Comment by melloware** [comment]
OK @stolp @MatthSHo I removed this CSS entirely and added a showcase example of using SunEditor in a dialog.  I can't see anything wrong.  I can edit text and add images and they get added in the correct spot.

What am I missing here?

**Comment by stolp** [comment]
Is the showcase live yet? I can't find a dialog there.

Anyway, in my application I reverted back to 12.0.7 (which also omits this CSS) and have no problems to speak of.

Yet, there are issues I can reproduce: When I use `p:sunEditor` with `mode=inline` in a dialog, the toolbar is cut off as shown here:

![bulkEditDialog](https://github.com/primefaces-extensions/primefaces-extensions/assets/522940/16ca2a3d-eb0c-43f5-aecc-df78ad7c13ea)

I circumvent this bug by using `mode=classic` in dialogs.

There also seem to be problems with the image highlighting when adding/editing images as shown here:

![bulkEditImage](https://github.com/primefaces-extensions/primefaces-extensions/assets/522940/c68317b4-15b5-4df4-8a14-4cd642a40a8b)

But this is more of a first world problem.

@MatthSHo may document his problem here again, but I am fine for now and approve reverting the prior fix.

**Comment by melloware** [comment]
Here is a runnable reproducer:
[pfe-suneditor.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/12443878/pfe-suneditor.zip)

Run `mvn clean jetty:run` and it looks like everything is working to me.  I do see the `inline` mode issue in the dialog you see but NONE of the other issues being reported by @mattsho ?

**Comment by melloware** [comment]
I think this fixes your dialog `inline` mode issue.

```css
.ui-dialog div.se-toolbar.sun-editor-common.se-toolbar-inline {
  top: 0px !important;
}
```

**Comment by melloware** [comment]
@maroswal I released 13.0.1 are you able to test your scenario again please?

**Comment by maroswal** [comment]
Thanks, I will give it a try and come back to you.

**Comment by melloware** [comment]
Sorry really have it fixed for 13.0.2 and 12.0.11. But for now this MonkeyPatch should work.

```js
if (PrimeFaces.widget.ExtSunEditor) {
    PrimeFaces.widget.ExtSunEditor.prototype._render = function() {
        var $this = this;

        //initialize
        this.getLanguage();
        this.editor = SUNEDITOR.create(this.id, this.cfg);
        this.editor.onload = function(core, reload) {
            $this.callBehavior('initialize');
        }
        if (this.cfg.readOnly) {
            this.editor.readOnly(true);
        }
        if (this.disabled) {
            this.editor.disable();
        }

        //update input on change
        this.editor.onChange = function(contents, core) {
            $this.input.val([].map.call(core.context.element.wysiwyg.children, function(node) {
                return node.outerHTML || "";
            }).join(""));
            $this.callBehavior('change');
        };

        this.editor.onScroll = function(contents, core) {
            $this.callBehavior('scroll')
        };
        this.editor.onMouseDown = function(contents, core) {
            $this.callBehavior('mousedown')
        };
        this.editor.onClick = function(e, core) {
            $this.callBehavior('click')
        }
        this.editor.onInput = function(e, core) {
            $this.callBehavior('input')
        }
        this.editor.onKeyDown = function(e, core) {
            $this.callBehavior('keydown')
        }
        this.editor.onKeyUp = function(e, core) {
            $this.callBehavior('keyup')
        }
        this.editor.onFocus = function(e, core) {
            $this.callBehavior('focus')
        }
        this.editor.onBlur = function(e, core) {
            $this.callBehavior('blur')
        }
        this.editor.onPaste = function(e, cleanData, maxCharCount, core) {
            $this.callBehavior('paste')
        }
        this.editor.onCopy = function(e, clipboardData, core) {
            $this.callBehavior('copy')
        }
        this.editor.onCut = function(e, clipboardData, core) {
            $this.callBehavior('cut')
        }
        this.editor.onDrop = function(e, cleanData, maxCharCount, core) {
            $this.callBehavior('drop')
        }
        this.editor.onSave = function(contents, core) {
            $this.callBehavior('save')
        };

        // check if being used in dialog
        var dialog = this.input[0].closest('.ui-dialog');
        if (dialog) {
            $(dialog).find('.sun-editor .se-toolbar').zIndex(9999);
            $(dialog).find('.sun-editor .se-wrapper').zIndex(9998);
        }
    }
};
```

**Comment by maroswal** [comment]
Seems to work for me with 13.0.2

**Comment by melloware** [comment]
Excellent thanks for reporting back!
