### ISSUE TITLE
New Component: Mapping OL3 or OpenStreetMap

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#128]
Based on 2 requests in PF...

https://github.com/primefaces/primefaces/issues/67
https://github.com/primefaces/primefaces/issues/40

OL3:  https://openlayers.org/

OpenSteetMap: https://www.openstreetmap.org/#map=5/38.007/-95.844

**Comment by melloware** [comment]
OK added to 14.0.1 and you can use the same Java model objects as are in PF core for GMAP. @mores 

I added 1 basic showcase example but @mores we probably need a few more like Markers etc.

**Comment by mores** [comment]
> @mores we probably need a few more like Markers etc.

I created an "Event Usage"  - https://github.com/mores/primefaces-extensions/tree/moreExamples

I will continue to build out more examples.

**Comment by melloware** [comment]
Excellent!
