### ISSUE TITLE
MonacoEditor: Custom autocompletion

### ISSUE THREAD

**Issue by arunvc** [primefaces-extensions/primefaces-extensions#1290]
### Describe the feature you would like to see added

Custom autocomplete

**Comment by melloware** [comment]
cc @blutorange

**Comment by blutorange** [comment]
Can you be more specific? What kind of autocomplete do you need, what is your use case? What kind of Java / XHTML API would you want (i.e. how should the xhtml code look like once this feature is implemented)?

Keep in mind that this component is just a wrapper around Monaco editor, so we can only do what Monaco editor can do. If you are referring to IntelliSense, monaco editor has an extensive JavaScript API, and we have an `extender` attribute that lets you customize the editor via JavaScript.

See for example the [showcase that load JQuery TypeScript declarations](https://www.primefaces.org/showcase-ext/sections/monacoEditor/extender.jsf?example=jquery), [various examples on the Monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#example-creating-the-editor-hello-world), and the [Monaco editor docs](https://microsoft.github.io/monaco-editor/docs.html)

In general I'm against trying to provide too much JSF abstraction around the underlying JavaScript library. Too often it leaks, and it's usually incomplete. When you need some specific feature you'll need custom JavaScript anyways, especially for a large and complex library such as Monaco editor.

Although if you do have a use case where it would make sense to add an option to the Monaco editor JSF component, we can consider it.

**Comment by melloware** [comment]
I think he is referring to similar to what is in CodeMirror: https://www.primefaces.org/showcase-ext/sections/codeMirror/codeCompletion.jsf

But agreed I don't want to add to much to the default MonacoEditor.
