### ISSUE TITLE
DynaForm: add client behavior dynamically

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions#130]
See https://stackoverflow.com/questions/56312802/add-client-behavior-dynamically-with-var-components

In progress: https://github.com/Rapster/core/commits/fix-706

**Comment by melloware** [comment]
@Rapster are you still working on this or should we close it?

**Comment by Rapster** [comment]
I don't plan to, got it working 90% but faced issues to add/remove listeners dynamically. You can close it
