### ISSUE TITLE
Layout: Remove IE hacks

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#1306]
Layout has been removed from PrimeFaces long ago for good reasons. I don't think we should spend time keeping this legacy component alive, as there are better alternatives.

I guess the elephant in the room here is that the showcase is using Layout.

**Comment by melloware** [comment]
Yeah and I still use it in a couple of production apps.  I had talked about leaving this here for all those who also migrate from the PF layout.  I have been updating this one based on the fork from @GedMarc

Fork: https://github.com/GedMarc/layout

**Comment by GedMarc** [comment]
It served its purpose during the age it was written in xD :D CSS 3 is a much better solution now and very portable across browsers unlike before when this sort of thing was necessary. Had to can the bootstrap-modal as well xD

I took a look at migrating to typescript, modernizing and removing JQuery from the base - it really is more work than it's worth considering the replacements on a technology level :) 

Was nice to say it was used in PF though won't lie ;) But it is time to archive that project (y)

**Comment by melloware** [comment]
i think I am going to keep it alive here for a while since my projects use it but I might rip out all the IE hacks out of it!

**Comment by jxmai** [comment]
I have been using the layout component in some of the app as well. and it is still serving its purpose. Unless we have alternative that can be easily port over rather than ask user to build their own layout :smile: , let's keep the component for now.

**Comment by melloware** [comment]
@jxmai i plan on keeping it around as i have a few production projects using it!  Thanks for your +1 vote!

**Comment by melloware** [comment]
@GedMarc how do you build your fork?  I don't see any scripts in package.json to build the `dist` files?

**Comment by jepsar** [comment]
The fact that it is being used is not really a good argument to keep it in honestly. IMO there are better alternatives. But as long it isn't too much work to maintain it, I guess we can keep it on live support.
