### ISSUE TITLE
New Component: HandleServerDownOrRestarted

### ISSUE THREAD

**Issue by ssibitz** [primefaces-extensions/primefaces-extensions#131]
I have an idea for a simple component without any gui but only javascript.

Preface:
When i restart, stop or reload my server on the client side the page can't be reloaded
and the user is currently not informed that the server is down at the moment.

So i tried the following to handle this special case which could also be 
an improvement for other users:

1.) Try to ping the server via AJAX like the ping in the speedtest component.
2.) On Error remember that the server is currently offline and show a sidebar panel in fullscreen mode that the server is currently offline.
Retry with the ping as described on 1.)
3.) On Success check if the server was offline before. If so, now redirect to login page. If the server was not offline before retry with the ping as described on 1.)

Here is the sidebar i used in a general template:
```
				<!-- Sidebar to show that server is currently offline -->
				<p:sidebar widgetVar="SideBarServerOffline" fullScreen="true" baseZIndex="10000">
					<div style="text-align: center;">
						<h1 style="font-weight: normal;">
							<p:outputLabel value="<span style='color:red;'>Server is currently offline.</span>" escape="false"/>
						</h1>
						<h2>
							<p:outputLabel value="You will be redirected when server is online again." escape="false"/>
						</h2>
					</div>
				</p:sidebar>

```

And here is the javascript which will do the action:
```
<h:outputScript>
	var SERVERPINGTIME = 30*1000; // in ms
	var SERVERTIMEOUTTIME = 10*1000; // in ms
	var isServerOnline = true;
	var ServerPingTimeout;
	var RedirectURL = "/index?faces-redirect=true";
	// Check server state
	function CheckServerState() {
		console.log("Checking current server state...");
		// Try to ping server and get result or timeout:
		$.ajax({
			url: "/dummy.html" + "?id\x3d" + "1",
			async: false,
			cache: false,
			type: "GET",
			success: function(a) {
				OnServerOnline();
			},
			error: function(a) {
				OnServerOffline();
			},
			timeout: SERVERTIMEOUTTIME
		});
	}
	function OnServerOnline() {
		// Redirect to start page
		if (isServerOnline == false) {
			console.log(" Server is online again, try to redirect to '"+RedirectURL+"'");
			window.location.href = RedirectURL;
		}
		// Re-Check
		if (isServerOnline == true) {
			console.log(" Server is online ...");
			ServerPingTimeout = setTimeout("CheckServerState()", SERVERPINGTIME);
		}
		isServerOnline = true;
	}
	function OnServerOffline() {
		console.log(" Server is now offline - retry ...");
		isServerOnline = false;
		// Show information that server is offline to user:
		PF('SideBarServerOffline').show();
		// Re-Check
		ServerPingTimeout = setTimeout("CheckServerState()", SERVERPINGTIME);
	}
	// Execute script on page ready
	$(document).ready(function()
	{
		// Install a timer to check the server's current state
		clearTimeout(ServerPingTimeout);
		ServerPingTimeout = setTimeout("CheckServerState()", SERVERPINGTIME);
	});
</h:outputScript>

```

The only thing here todo is to create a new component which 
is handling the parameters like SERVERPINGTIME, SERVERTIMEOUT, RedirectURL, ...
because it's currently tested in production and it works as it should ...

**Comment by melloware** [comment]
@ssibitz @balta3 are either one of you going to submit a PR for this if not I will close the ticket.

**Comment by melloware** [comment]
No updates from the OP or any follow up so closing for now. Will reopen if someone donates a PR.
