### ISSUE TITLE
MorphiaLazyModel: Refactor in 14.0.0

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1321]
Based on core PF changes: https://github.com/primefaces/primefaces/pull/10776

cc @Rapster cc @newk5

**Comment by melloware** [comment]
@Rapster @newk5 wouldn't mind if you guys looked at this.  @newk5 i am seeing some Morphia deprecation warnings as well?

**Comment by Rapster** [comment]
I can try make a PR

**Comment by Rapster** [comment]
@melloware should PFE requires java 11 from now on?

**Comment by melloware** [comment]
yes it should in 14.0
