### ISSUE TITLE
Exporter: exportFunction as component or facet

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions#133]
Export built-in solutions for certain components like `h:outputLink` or `p:cellEditor` are very nice and can be enhanced by `CustomExporter`. 

**ExportFunction:**

It is not possible to write a custom exporter for any complex or composite type and `exportFunction` of primefaces column lacks lacks support of alignment, styling, or potential future improvements like Number type exports (for excel).

It also does not supports an el expression like: `#{el:getEnumLabel(varOrder.state)}`, which is a very common use case.

**Idea**

Give more control to the developer to define how to export in markup using a facet or new component. 
With a `export` component, styling could be overriden on cell level and alignment could also be defined which gives a flexible approach.

	<p:column>

		
		<f:facet name="export">
			<h:outputText value="#{varOrder.timeRange.start}-#{varOrder.timeRange.end}"/>
		</f:facet>

		
		<pe:export value="#{varOrder.timeRange.start}-#{varOrder.timeRange.end}" fontColor="#00ff00" align="center">
			
			<h:outputText value="#{varOrder.timeRange.start}-#{varOrder.timeRange.end}"/>
		</pe:exporter>

		
		<comp:timeRange value="#{varOrder.timeRange}"/>
	</p:column>

**Comment by melloware** [comment]
@djmj Can you see this ticket and express anything you use the PFE Exporter for that is NOT in the core PF exporter?

https://github.com/primefaces-extensions/primefaces-extensions/issues/205

**Comment by djmj** [comment]
@melloware i dont have much insight in PF exporter and only used PFE exporter for PDF for the landscape orientation with a simple use case without styles / formatting. 

Specific things i do are:
- tableTitle="#{cc.attrs.fileName}" 
- orientation="Landscape" for PDF

This here works in both PFE and PE:
- `exportFunction="#{requestUtilBean.getStringValue(of:formatCurrency(tblVarCar.price, $))}"` since it does not allows el functions inside i guess.

**Comment by melloware** [comment]
Thanks for your feedback @djmj !

So in PF Exporter instead of tableTitle="" it is using the "header" facet like..
```xml
<f:facet name="header">
          #{cc.attrs.fileName}
</f:facet>
```

As for orientation Landscape for PF I will open a PF enhancement ticket to add that feature.
