### ISSUE TITLE
Sheet: Missing updates when pasting more rows than available in the current sheet

### ISSUE THREAD

**Issue by blutorange** [primefaces-extensions/primefaces-extensions#134]
## Version

PrimeFaces: 6.2.6, PrimeFaces Extensions: 6.2.7, JSF: mojarra 2.2, Server: jetty/9.4.11.v20180605

## Related

See also https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/586

## Steps to reproduce

1. Add a `<pe:sheet>` component.
1. Add an `ajax` listener for the `change` event
1. If the data sheet has got, for example, 10 rows, copy 4 rows to the clipboard, click on a cell of the last row, and press ctrl+v to paste those rows.
```xhtml
<pe:sheet>
...
<p:ajax event="change" global="false" listener="#{myBean.onSheetDataChanged}" />
...
<pe:sheet/>
```

On the client side, 3 new rows are created and displayed. However, when we retrieve the updates in the bean via `org.primefaces.extensions.component.sheet.Sheet#getUpdates`, we only get one `SheetUpdate`. All `SheetUpdate`s for cell of newly created rows are missing. This results in inconsistencies between the client and server-side model for me.

As far as I can tell, this happens because a `NullPointerException` was fixed in issue [#586](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/586) by [ignoring updates from cells of newly created rows](https://github.com/primefaces-extensions/core/commit/3f5daff0a3b4130475c926bf257e214fb8bf85f2).

**Comment by blutorange** [comment]
This seems to be fixed now. I am now receiving the `SheetUpdate`s for the newly added rows. Looking at the commit history, I suppose this is due to the update to HandsonTable 5.0 (#590).

**Comment by blutorange** [comment]
Hmm, I'm not sure what I've been seeing, but unfortunately, it seems the updates are still not sent to the server. Would be great if you could take a look at it when you've got time.

If it helps, the use case is a simple generic CSV editor where the user can copy&paste data into the sheet.

**Comment by melloware** [comment]
This one is definitely messy. I took a deeper dive and without RowKey it then fails the `validate` step etc.  I think this would have to be fixed in many many places for it to work and pass down into SheetUpdates.    Was hoping it was going to be simple.

**Comment by blutorange** [comment]
Yeah, though I think the real issue for us is that (as far as I heard) the sheet component was developed as an alternative for DataTable with a mostly fixed column schema. We're kinda using the sheet as a general excel / CSV editor and it really shows the sheet wasn't developed with that usage in mind.
