### ISSUE TITLE
Timer: executes an AJAX request, even if the "listener" attribute is absent 

### ISSUE THREAD

**Issue by Gmugra** [primefaces-extensions/primefaces-extensions#1345]
### Describe the bug

I only use **pe:timer** to execute javascript:
```
<pe:timer
    widgetVar="myTimer"
    global="false"
    visible="false"
    timeout="100"
    ontimercomplete="myJavaScriptFunction();"
    singleRun="true" />
```
So, the **listener** attribute is missing and everything works fine..., but the ajax-request is still triggered as a result of the timer complete.

IMHO it's not right.

Furthermore, I can see in the source code (timer.js) that this shouldn't really be the case:
```
stop: function (silent, end) {
        if (!silent && this.cfg.listener) {
            this.cfg.listener();
        }
```
but it doesn't seem to be working the way it should.

FYI: workaround, which I found, for my use-case is:
```
$(document).ready(
    function() {
        PF('myTimer').stop = function(silent, end) {
            PrimeFaces.widget.ExtTimer.prototype.stop.call(this, true, end);
        }
    }
);
```

### Reproducer

If there is no **listener** attribute, no ajax requests should occur

### Expected behavior

If there is no listener attribute, no ajax requests should occur

### PrimeFaces Extensions version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

Chrome/118.0.0.0

**Comment by blutorange** [comment]
You can probably also use `<pe:timer onstart="return false"/>` as a workaround, it's what I use in general when I don't need AJAX requests to be sent. The `this.cfg.listener` is not what you define on the component, it [appears to be always set](https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/java/org/primefaces/extensions/component/timer/TimerRenderer.java#L126)

**Comment by melloware** [comment]
I will take a look at this.

**Comment by melloware** [comment]
@Gmugra this component has been around a long time (since way before I joined this project) and I don't think it is quite right as you mentioned and @blutorange mentioned its ALWAYS setting the listener for some reason?

**Comment by melloware** [comment]
Even weird I have no idea why it has a Handler: https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/java/org/primefaces/extensions/component/timer/TimerHandler.java

**Comment by Gmugra** [comment]
> You can probably also use `<pe:timer onstart="return false"/>` as a workaround, it's what I use in general when I don't need AJAX requests to be sent. The `this.cfg.listener` is not what you define on the component, it [appears to be always set](https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/java/org/primefaces/extensions/component/timer/TimerRenderer.java#L126)

Thanks for the tip, this way is better :)

**Comment by Gmugra** [comment]
@melloware,
I also don't understand what for it has a Handler, and why listener is always set :)
(Furthermore, if it is always set, why check for it in javascript? )
But I'm not a big enough JSF expert to be 100% sure. Sorry.

I'd say it's just some legacy with some old bugs :)

Yes, the component exists since version 3, i.e. ~10 years.
It would be useful to check the history of old changes, maybe that would clarify things;
but as far as I can see, here exists a history of changes from 2020, not 2014. :(
