### ISSUE TITLE
SunEditor : Unable to save an Horizontal Line <hr> in Editor

### ISSUE THREAD

**Issue by ybs-fr** [primefaces-extensions/primefaces-extensions#1348]
### Describe the bug

When we create an horizontal line <hr ...> in SunEditor (with the spécialized  button by exemple), and then push on save button, the refresh textarea is displayed without this horizontal line.
The <hr ...> tag is lost.
We can show  this feature directly on the showcase page.

If the "save" action is without an active Ajax (event "save"), the display is correct.

It is also impossible to init the editor with a String contains a <hr ...> tag, the <hr> is lost.

### Reproducer

Use the showcase page https://www.primefaces.org/showcase-ext/sections/sunEditor/basicUsage.jsf

### PrimeFaces Extensions version

13.0.0

### JSF implementation

None

### Browser(s)

FireFox and Chrome

**Comment by melloware** [comment]
Are you using it in Secure mode with OWASP HTML Sanitizer?  It could be our Sanitizer settings?
