### ISSUE TITLE
DynaForm: disabled state not restored

### ISSUE THREAD

**Issue by pzoli** [primefaces-extensions/primefaces-extensions#135]
I don't understand how Visitor work.
Works as like I add disabled css for each uicomponent however I try disable only one from many.

Please visit forum topic

https://forum.primefaces.org/viewtopic.php?f=14&t=55559

**Comment by pzoli** [comment]
I added modifications to showcase(disable visitor) and core (readonly). 
please view attached files.
Oh, how can I add attachments?

**Comment by melloware** [comment]
Also I discovered Primefaces has a SavedState class that looks like it duplicates (or was moved from PFE) as our SavedEditableState.
