### ISSUE TITLE
DocumentViewer: javax.faces.resource/documentviewer/RES_NOT_FOUND".

### ISSUE THREAD

**Issue by Wembo1721** [primefaces-extensions/primefaces-extensions#1356]
### Describe the feature you would like to see added

hello @melloware please could you help me I´m trying to view a pdf from my file  server but i can´t, this is my code 
  <p:tab title="Resource">
                                <pe:documentViewer height="500"
                                                   library="JavaIOExamples"
                                                   name="Prueba.pdf" zoom="page-width"/>
                            </p:tab>

**Comment by blutorange** [comment]
Pretty sure you're gonna need to provide more info than that for anybody to help you

* Are sure certain that the resource can be found? Perhaps try `<h:outputText value="#{resource['JavaIOExamples:Prueba.pdf']}” />`. This should output a URL to the resource, if it can be found.
* What exactly does the error look like? Are there any log messages?

**Comment by melloware** [comment]
You can see it works on the showcase: https://www.primefaces.org/showcase-ext/sections/documentviewer/basic.jsf

```xml
 <pe:documentViewer height="500" library="books" name="hood.pdf" zoom="page-width"/>
```

For that to work it has to be located in your app at...

```
\src\main\webapp\resources\books\hood.pdf
```
