### ISSUE TITLE
New Component: InputPlace

### ISSUE THREAD

**Issue by mayankX** [primefaces-extensions/primefaces-extensions#137]
Add google place autocomplete component.

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

Since we already have Geocoding and Rev. Geocoding from Google, we should also have other google maps features like Place autocomplete etc.

**Comment by melloware** [comment]
This plugin https://ubilabs.github.io/geocomplete/ is now archived and no longer maintained so no point in creating a component for it.  I feel like in the world of GeoComplete not much is truly free etc so not sure its worth creating a component for....

**Comment by melloware** [comment]
Going to reopen this as I need this for a customer. I am going to create a Google Places based input called InputPlace
