### ISSUE TITLE
DynaForm - add responsive functionality

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions#138]
Probably with Bootstrap (bootstrap.css) http://getbootstrap.com/css/#grid because it is more advanced than PrimeFaces Grid Layout. Requirements:

1) "Reponsive" mode should be an alternative mode to the existing "table" mode.
2) Nested rows should be possible.

**Comment by melloware** [comment]
I think we should use PrimeFlex and now that we have added Flex detection and things like GridLayoutUtils in PF core it should be realtively easy to add Grid CSS or PrimeFlex.

**Comment by melloware** [comment]
Open for 7 years...should we close this if no one is going to work on it?  

I personally don't use DynaForm so I was not planning on working on this.

**Comment by Rapster** [comment]
Besides me, i don't see a lot of people using it and interested in it (too bad I think it's one of most powerful component in the PF suite but unfortunately has limitations). 

It can be close for now
