### ISSUE TITLE
InputPhone: Upgrade intl-tel-input JS

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1391]
See: https://github.com/jackocnr/intl-tel-input/releases

**Comment by jepsar** [comment]
Yeah, as soon as they figure out which countries to drop or keep 😆

**Comment by melloware** [comment]
I am updating but the only thing I see weird is the flags are askew?

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/5fbf5b6d-ea88-4239-8769-e419b58b7feb)

**Comment by melloware** [comment]
Nevermind had to update the flags.png's.
