### ISSUE TITLE
InputPhone: always submit complete E.164 number

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#1393]
Add a converter to store phone numbers in E.164 format while keeping validation done in the renderer (if no converter is set).

**Comment by NicolaIsotta** [comment]
Does this mean having the international prefix in the submitted value? That would make the component much more usable. Lemme know if you need help.

**Comment by jepsar** [comment]
Ha, this has slipped my mind. This shouldn't be too hard. I think an attribute would be easier to find for users instead of having to know that there is a converter somewhere in the PFE JAR.

**Comment by jepsar** [comment]
Let's add this to 14 as it's returning data in a different style. I'll add it to https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Migration-Guide

**Comment by melloware** [comment]
OK i merged to master (14) and reverted the change to 13.x branch
