### ISSUE TITLE
ThemeAccentColorResource is not finding accent color anymore

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#1434]
Probably the colors in the themes were updated at some point. These lists need to be updated

https://github.com/primefaces-extensions/primefaces-extensions/blob/cd855d736556953f4696a9d837299bae428eb191/core/src/main/java/org/primefaces/extensions/application/ThemeAccentColorResource.java#L53-L55

**Comment by jxmai** [comment]
wondering if this ticket is related to theming of clock picker? How we capture the color (color picker or go into theme code base or any other way) in case the ACCENT_COLORS map needs to be updated :thinking:

**Comment by jepsar** [comment]
Yeah, it is related. I'll fix both.

**Comment by jxmai** [comment]
Nice. Thanks @jepsar
