### ISSUE TITLE
New component: Apache EChart

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1451]
### Describe the feature you would like to see added

Request on Discord: https://discord.com/channels/787967399105134612/787974851100409866/1209370699697750016

https://echarts.apache.org/en/index.html

I think this would be easy to base on the new PrimeFaces Chart component which is pretty thin.  We can incubate it here in Extensions.

**Comment by fcorneli** [comment]
Check out:
https://demo.e-contract.be/ejsf-demo/echarts.xhtml

**Comment by melloware** [comment]
Nice @fcorneli i think i am going to create a echart component here in Extensions because echarts does look REALLY nice and full featured!

**Comment by fcorneli** [comment]
I've been using the ECharts JSF component within a few projects already. Easiest way to do graphs for me.

**Comment by melloware** [comment]
Plus some of the eCharts i have seen on their demo site I have not seen other charting libraries even have.

**Comment by melloware** [comment]
Got it all working.

## Dark Theme:

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/fb4f78a2-66ef-411e-a944-a8301cea2979)

## Light Theme:
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/fd509aba-3a0f-4c17-8759-421e68381142)

## Custom Theme:
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/c2ec485f-fe3b-4130-847c-4e25e085e158)

**Comment by fcorneli** [comment]
Nice with the theme support!

**Comment by melloware** [comment]
@fcorneli thanks for your feedback, updates made here and in PF Chart component which had the same issues.

**Comment by melloware** [comment]
I also just added JS methods `exportAsImage()` and `print()` to send the chart to the printer or export it as a PNG image.
