### ISSUE TITLE
New component: OTP / PIN input

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces-extensions/primefaces-extensions#1453]
We need a OTP input for a new project, I checked primefaces and extensions' showcase but I haven't found anything suitable.

Some examples found in the web:

- https://www.geeksforgeeks.org/create-otp-input-field-using-html-css-and-javascript/
- https://shuqikhor.github.io/Vanilla-OTP-Input/
- https://foolishdeveloper.com/otp-input-field-javascript/
- https://github.com/devfolioco/react-otp-input
- https://dominicarrojado.com/posts/how-to-create-your-own-otp-input-in-react-and-typescript-with-tests-part-1/

I may try to put something together if you guys think this could be useful.

**Comment by melloware** [comment]
i think it would be useful. I think @fcorneli had something like this in his project.

**Comment by fcorneli** [comment]
Showcase available at:
https://demo.e-contract.be/ejsf-demo/otp-validator.xhtml
https://demo.e-contract.be/ejsf-demo/pin-validator.xhtml

In combination with an auto-submit:
https://demo.e-contract.be/ejsf-demo/auto-submit.xhtml

Project source code at:
https://github.com/e-Contract/enterprise-jsf
