### ISSUE TITLE
InputOtp: Remaining Features

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1476]
- [x]  When `required='true'` the component should mark the inputs as `ui-state-error`
- [ ]  templating but it's (partially) replaced by the "separator" attribute

cc @NicolaIsotta

**Comment by NicolaIsotta** [comment]
I took a look back at this. I do think the templating feature is a bit overkill (and not easy to implement)
however
adding a class to the separator element, and adapting the css from the [PrimeVue "Sample" section](https://primevue.org/inputotp/#sample)
I managed to replicate the example:
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/18428155/e81fa47c-400a-41a6-9299-01b1f7c95207)
WDYT?

**Comment by melloware** [comment]
I like your workaround/example.  True templating is hard with JSF and easy with Vue/React so yeah its overkill for this.
