### ISSUE TITLE
New Component: Markdown Editor

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1484]
Can anyone recommend a Markdown editor which uses a toolbar (like on GitHub comments for example)?

 I've found  https://github.com/Ionaru/easy-markdown-editor.

Cc @jepsar

**Comment by melloware** [comment]
We need this our customer as well.

**Comment by jepsar** [comment]
I was thinking the same on my morning run. I'd better make this into a component.

**Comment by jepsar** [comment]
I don't like the fact that both editors try to be kind of WYSIWYG.

**Comment by melloware** [comment]
Well if we decide on one I don't mind taking the first shot at implementing it?

**Comment by jepsar** [comment]
Ha, they looked too similar. https://github.com/Ionaru/easy-markdown-editor is a fork. The other one seems to be dead.

**Comment by melloware** [comment]
Made great progress, this should be ready for review tomorrow or tuesday!

**Comment by melloware** [comment]
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/2c4df389-9568-4837-9f9f-0309f12a787f)
