### ISSUE TITLE
InputPhone: intl-tel-input 20.0.4 Breaking Changes

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1486]
https://github.com/jackocnr/intl-tel-input/releases/tag/v20.0.0

We should review the breaking changes and upgrade to 20.0.0

cc @jepsar @NicolaIsotta

**Comment by NicolaIsotta** [comment]
I wonder if we can use the `hiddenInput` option instead of wrapping the input event... I'll give it a try
