### ISSUE TITLE
SunEditor: Edit Link not working when inside Dialog

### ISSUE THREAD

**Issue by ZeroBrushV2** [primefaces-extensions/primefaces-extensions#1502]
### Describe the bug

When using the SunEditor inside a Dialog, as per Showcase (https://www.primefaces.org/showcase-ext/sections/sunEditor/dialog.jsf), trying adding a link and clicking on it after that doesn't show the mini dialog for editing it.

Mini Dialog in question:
![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/123548294/1e9280a8-198a-443c-89ff-989e015f2496)

### Reproducer

Go to the showcase https://www.primefaces.org/showcase-ext/sections/sunEditor/dialog.jsf

Try adding a link inside the text, and then try click on it

### Expected behavior

Should show the mini dialog to manage the link

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/123548294/d9d67d37-cdaa-4455-80a1-d0480efeca10)

### PrimeFaces Extensions version

13.0.7

### JSF implementation

All

### JSF version

2.3

### Browser(s)

Any browser

**Comment by melloware** [comment]
@ZeroBrushV2 thanks for the report i will check.  Probably a z-index issue with that link edit dialog.

**Comment by ZeroBrushV2** [comment]
> @ZeroBrushV2 thanks for the report i will check. Probably a z-index issue with that link edit dialog.

yup, i confirm is a z-index issue, setting it at 99999 makes it work, I think I can do a custom patch just forcing the z-index until you fix it officially

**Comment by melloware** [comment]
cool paste what you patched here it may help me make the real patch.

**Comment by ZeroBrushV2** [comment]
Basically override the css using this:

```
.sun-editor .se-controller{
	z-index: 9999!important;
}
```

I had to use 9999 since the dialog has 9997 (not sure if is JSF/PrimeFaces default)

@melloware I noticed that by default has `z-index: 6`, which is fine when is included normally in the page, but won't work in dialogs ecc. Up to you, I think leaving an high value should be ok for both cases

**Comment by melloware** [comment]
PR submitted.  Will be fixed in 1.30.8
