### ISSUE TITLE
SlideOut: Tab word wrapping

### ISSUE THREAD

**Issue by farhad-moazzezi** [primefaces-extensions/primefaces-extensions#153]
**problem:**
if title attribute contains space, title of handle button will be breakdown in two part, and it's ugly on design

**solution:**
this problem will resolve by add "width: max-content" in .ui-slideouttab-handle css class

**Comment by melloware** [comment]
@farhad-moazzezi I can't reproduce?  I made one of my tabs "Contact Information Testing" with spaces between each word and here is my screenshot:
![image](https://user-images.githubusercontent.com/4399574/92468802-bc55f500-f1a1-11ea-9516-c1b027af70ef.png)

Can you post your screenshot?

**Comment by melloware** [comment]
@farhad-moazzezi any response?

**Comment by farhad-moazzezi** [comment]
I searched more and sew in RTL pages direction and persian language this problem will happen

**Comment by jepsar** [comment]
@farhad-moazzezi could you try with this CSS rule?

```css
.ui-slideouttab-handle {
  white-space: nowrap;
}
```

does this fix your issue?

**Comment by melloware** [comment]
I added @jepsar suggestion to the CSS and closed the ticket.

**Comment by farhad-moazzezi** [comment]
ok my bro

**Comment by farhad-moazzezi** [comment]
thanks
