### ISSUE TITLE
InputPhone: Upgrade to v21.2.6+

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1533]
https://github.com/jackocnr/intl-tel-input/releases/tag/v21.2.6

Looks like he is still making lots of good changes and improvements.

cc @NicolaIsotta @jepsar

**Comment by NicolaIsotta** [comment]
I'm currently OOF so I can't look at this 'til 03/05. What is the ETA for PF 14?

**Comment by melloware** [comment]
PF14 can be any day but don't worry this can go in 14.0.1

**Comment by melloware** [comment]
Looks like 23.0 might cause some problems with how utils is loaded: https://github.com/jackocnr/intl-tel-input/releases/tag/v23.0.0

**Comment by NicolaIsotta** [comment]
Man's dropping updates at an insanely high rate, lol.
Maybe I can update to the latest v22 and then we can evaluate what to do after PFE 14.0.1?

**Comment by melloware** [comment]
Good plan!

**Comment by NicolaIsotta** [comment]
I'm currently testing the upgrade to [v22](https://github.com/jackocnr/intl-tel-input/releases/tag/v22.0.0).
`countrySearch` option has been removed, should I remove it from component attributes too or we should avoid breaking changes in minor releases?

**Comment by melloware** [comment]
weird that that option was removed?  Or is it just the default now to be able to search countries?

**Comment by melloware** [comment]
Oh its just TRUE by default yeah you can remove it then.
