### ISSUE TITLE
Sheet: Context Menu Doesn't Display After Sheet Update

### ISSUE THREAD

**Issue by TheMightyE** [primefaces-extensions/primefaces-extensions#1546]
### Describe the bug

I have a `SelectOneButton`. When I click it, it loads different types of rows in the sheet component, hence updating the sheet. After clicking this button, right clicking within the sheet no longer opens the context menu, but instead the default browser right click menu displays. If I reload the page, the context menu works on right click. This means I cannot access the context menu after clicking the `SelectOneButton`.

### Reproducer

Reproduce steps:
1. Run your project and go to `http://localhost:8080/manageLibrary.xhtml`.
2. Right click within the sheet to verify the context menu displays.
3. Click the "Books" `SelectOneButton`.
4. Right click within the sheet no longer displays the context menu.

The bean and the xhtml.
[manageLibrary.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/15251522/manageLibrary.zip)

### Expected behavior

The context menu within the sheet component should appear even after I click `SelectOneButon` to update the sheet to load different records.

### PrimeFaces Extensions version

13.0.8

### JSF implementation

MyFaces

### JSF version

4.0.2

**Comment by melloware** [comment]
I fixed your example.  You need to re-attach the sheet JS whenever updating the Sheet component.  

Unzip this code: 
[pfe-1546.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/15252088/pfe-1546.zip)

Run `mvn clean jetty:run` you will see it works.

**Comment by sylvesternumski** [comment]
I'm having similar issues with a Quarkus-Faces/PrimeFaces/Extensions application and tried using the example javascript provided.  It appears this isn't working as expected.  The javascript file isn't loaded from my resources directory and when embedding there's a disconnect.  Is there some additional configuration required to get this to work in Quarkus?

**Comment by melloware** [comment]
Nope it works out of the box in Quarkus.  @sylvesternumski do you mean the project above from @TheMightyE is not working in Quarkus or do you have some other Quarkus issue?

**Comment by sylvesternumski** [comment]
My context menus are disappearing after updating the sheets component, I'll code up a example based on my app and post it.

**Comment by melloware** [comment]
ok yeah because his issue above is that he was not -reapplying the script.  Let me know.

**Comment by sylvesternumski** [comment]
I think I figured out my issue while putting together a reproducible example.  I'm using a template and noticed when I have just a single page with no ui:composition and ui:define, it can see the javascript and it works as expected.  I didn't realize that I could put the outputScript tag inside my ui:define, but doing that makes it work.  Thanks!

**Comment by melloware** [comment]
The power of the reproducer!!!

**Comment by TheMightyE** [comment]
Thank you. All of this helped and fixed my issue. Closing this issue and marking it as complete.
