### ISSUE TITLE
SunEditor: Configure HtmlSanitizer to keep table styles

### ISSUE THREAD

**Issue by maroswal** [primefaces-extensions/primefaces-extensions#1580]
### Describe the bug

In SunEditor you can set different table styles (min width, max width and fixed with) but the added style classes will be removed from the HtmlSanitizer.

```
table.se-table-size-100 {
   width: 100% !important;
}
table.se-table-size-auto {
   width: auto !important;
}
table.se-table-layout-fixed {
   width: fixed !important;
}
```

### Expected behavior

Either make the HtmlSanitizer somehow configurable or add table elements to the styles sanitizer to keep the applied table styles.

```
private static final PolicyFactory HTML_STYLES_SANITIZER = Sanitizers.STYLES
	.and(new HtmlPolicyBuilder()
		.allowElements("span", "li", "p", "pre", "div", "hr")
		.allowAttributes("class", "style", "contenteditable")
		.onElements("span", "li", "p", "pre", "div", "hr")
		.toFactory());
```

### PrimeFaces Extensions version

13.0.11

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
Did you test will this fix it?

```java
private static final PolicyFactory HTML_STYLES_SANITIZER = Sanitizers.STYLES
	.and(new HtmlPolicyBuilder()
		.allowElements("table", "span", "li", "p", "pre", "div", "hr")
		.allowAttributes("class", "style", "contenteditable")
		.onElements("table", "span", "li", "p", "pre", "div", "hr")
		.toFactory());
```

**Comment by maroswal** [comment]
Yes that's the way I fixed it with a monkey patch, but I haven't investigated if there are other elements with the same issue.

**Comment by melloware** [comment]
Nice i will add it.  As a stopgap you can always set `allowStyles="true"` to turn off that 1 setting in the SunEditor.

**Comment by maroswal** [comment]
You're right, haven't thought about that option 😀

**Comment by melloware** [comment]
13.0.12 released
