### ISSUE TITLE
InputPhone: Keep user selected country on invalidation

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions#1613]
### Describe the feature you would like to see added

If you select a different country flag then the initial one and then input an invalid number like "111" and submit it, the flag value is lost. 

### Is your feature request related to a problem?

http://www.primefaces.org/showcase-ext/sections/inputphone/basicUsage.jsf

- showcase has initial country to US
- select different country like afghanistan from dropdown
- enter "111" and submit
- validation error occurs
- dropdown reverts back to "US" instead of "afghanistan"

### Describe the solution you'd like

It should keep afghanistan, even on invalidation.

**Comment by melloware** [comment]
Can you try 14.0.2 this is already fixed I am pretty sure

**Comment by melloware** [comment]
Latest version running here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/input/inputPhone.xhtml

**Comment by melloware** [comment]
I can confirm 14.0.2 this behavior is working fine.  Can you please confirm on your end @djmj

**Comment by djmj** [comment]
Nice i can confirm this!

**Similar issue in 14.0.2 showcase**

Similar issue if the input is empty and component updated with ajax. Seems if no value was submitted at client side the last selected country is lost.


**Basic**

1. select country afghanistan
2. press submit
3. requried validation error message occurs
4. initial country is selected `US` - afghanistan is lost

**Localized**

1. select country "duitsland" germany
2. press submit
4. initial country is "netherland" is selected - "germany" is lost

**Comment by melloware** [comment]
I do see what you mean this does seem like odd behavior.

**Comment by jepsar** [comment]
IMO this is expected behavior and the workaround should be used. The core value of this component is the number, changing the default event to countrySelect broke it even more. Let's see if we can have a better fix with https://github.com/primefaces-extensions/primefaces-extensions/issues/1751
