### ISSUE TITLE
InputPhone: ajax event countrySelect show invalid input if triggered by input

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions#1614]
### Describe the bug

In showcase the"countrySelect" ajax is fired on dynamic country detection from input and this should not trigger the input validation but show the info "selected" message.

### Reproducer

http://www.primefaces.org/showcase-ext/sections/inputphone/basicUsage.jsf

- initial country is US
- user enters "+49"
- component selects germany in country drop down correctly
- JSF message with "invalid" phone number appears

### Expected behavior

With "countrySelect" ajax event it should trigger the info message "country selected". Same behavior as if user selects it from dropdown menu.

### PrimeFaces Extensions version

14.0

### JSF implementation

None

**Comment by melloware** [comment]
Ahhh I think I see what you are saying.  The Input value should not be processed and trigger a validation warning when only the country is selected.

**Comment by melloware** [comment]
@djmj why not just do this...use `@none`

```xml
<p:ajax event="countrySelect" process="@none" listener="#{controller.onCountrySelect}"/>
```

This is how most PF components work and gives you the added flexibility for people who DO want it to validate the submission on country change.

**Comment by djmj** [comment]
**Case A) user entered number**

I see your point in case a user already entered a phone number and then changes the country the validation should occur and for this case i want to validate it too.

Example: user switches from germany to austria with a valid phone number

- germany (+49) input "02175 1234" is valid
- austria (+34) input "02175 1234" is valid

**Case B) Input field is still empty**

But the case i described is when the user has not entered anything at all in the text input and this is confusing to the user since he has not done anything wrong to be "invalid".

**Cant have A and B**

Yes this could be a workaround but with a drawback. The workaround will work not work for case A which is not desired but for case B. Cant have both this way.

**Internal solution**

Can the component itself not check if its fired from event `countrySelect` and stop validating empty input?

In this showcase its also confusing for the user since the `required` JSF validator gets triggered while he has just selected a country.

For us its not really important since we dont have a use case for `countrySelect` but i just wanted to check current state of the component if we shall use it in our application.

**Comment by melloware** [comment]
@NicolaIsotta @jepsar i also can see this scenario being confusing for users.

**Comment by jepsar** [comment]
IMO this is expected behavior and the workaround should be used. The core value of this component is the number, changing the default event to countrySelect broke it even more. Let's see if we can have a better fix with #1751

**Comment by jepsar** [comment]
In the renderer I'll be adding
```java
protected boolean needsValidation(final FacesContext context) {
    final String eventName = context.getExternalContext()
                .getRequestParameterMap()
                .get(Constants.RequestParams.PARTIAL_BEHAVIOR_EVENT_PARAM);
    return !EVENT_COUNTRY_SELECT.equals(eventName);
}
```

**Comment by jepsar** [comment]
Workaround does not submit the value
