### ISSUE TITLE
InputPhone: SVG flags

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions#1615]
### Describe the feature you would like to see added

SVG flags would enhance render quality of the component and there are some githubs out there which could be used:

https://flagicons.lipis.dev/

**Configurable?**

In case an application already has flag icons accesible via CSS they could reuse them if they are made configurable with a JSF "context-param" like:

`
<context-param>
    <param-name>primefaces.extension.inputPhone.flags</param-name>
    <param-value>de=my-flag-de,us=my-flag-us</param-value>
</context-param>
`

**Comment by melloware** [comment]
Not sure whether this needs to be done by InputPhone itself @jepsar ?

Not sure if PFE can replace the flags.

**Comment by jepsar** [comment]
It would be best if the third party would implement this. @djmj please open a ticket at https://github.com/jackocnr/intl-tel-input

**Comment by jepsar** [comment]
See also https://github.com/jackocnr/intl-tel-input/issues/1605
