### ISSUE TITLE
QRCode: Label properties incorrect.

### ISSUE THREAD

**Issue by mores** [primefaces-extensions/primefaces-extensions#1629]
### Describe the bug

Attributes of mSize, mPosX, mPosY are not working as documented. The bean is using two Capital Letters next to each other.
Pull Request to follow

### Expected behavior

mSize="0.2" should make the font larger. It does not.

### PrimeFaces Extensions version

14.0.4

### JSF implementation

Mojarra

### JSF version

4.0.1

**Comment by melloware** [comment]
Thanks in advance for the PR!

**Comment by melloware** [comment]
@mores why not use the PF core QR code component: https://www.primefaces.org/showcase/ui/multimedia/barcode.xhtml?jfwid=f1ccd

https://primefaces.github.io/primefaces/14_0_0/#/components/barcode

Is there some the PFE component has the PF one doesnt?

**Comment by mores** [comment]
@melloware 

I googled "primefaces qrCode" and only the component from the extension showed up.

In the primefaces showcase search: qrCode -> No Results Found.

I am/was using it because it was the only one I could find. :-)

**Comment by melloware** [comment]
OK and I think this PFE one is much more feature rich than the core PF one from what I can tell @jepsar ?

**Comment by jepsar** [comment]
Does it have more features or noise? I don't really care about colors, rounded corners and a label. But that's me.

In PF we could add a stand alone menu item in the showcase for QR code so it shows up when you search for it there.

**Comment by melloware** [comment]
i think we should add a standalone QR code menu in PF. I will do that today and move the showcase example.
