### ISSUE TITLE
DocumentViewer: does not load if `primefaces.HIDE_RESOURCE_VERSION` enabled

### ISSUE THREAD

**Issue by segaura** [primefaces-extensions/primefaces-extensions#1631]
### Describe the bug

When using the <pe:documentViewer> component and setting the context param primefaces.HIDE_RESOURCE_VERSION to true, e.g.

<context-param>
<param-name>primefaces.HIDE_RESOURCE_VERSION</param-name>
<param-value>true</param-value>
</context-param>

the widget does not work properly.

In our tests primefaces version is the same as primefaces-extensions, 12.0.7.

### Reproducer

Attached is a sample project where you can verify that in one case the pdf is displayed correctly, while activating the primefaces.HIDE_RESOURCE_VERSION param, results in a blank pdf.

[primefaces-test-master.zip](https://github.com/user-attachments/files/16494091/primefaces-test-master.zip)

### PrimeFaces Extensions version

12.0.7

### JSF implementation

MyFaces

### JSF version

2.2.15

**Comment by melloware** [comment]
@segaura you can read about why here: https://github.com/primefaces-extensions/primefaces-extensions/issues/1265

Can I ask why you are hiding the resource version?

**Comment by segaura** [comment]
Sure you can.

It was a requirement we've been asked to add by our company's security department.
Something like "The web application discloses specific technologies or software version numbers" meaning an attacker can gain valuable knowledge on your system (e.g. presence of a bug in a specific library version).

The requirement is related to this [CWE-200](https://cwe.mitre.org/data/definitions/200.html) which web page provides various useful information.

Being PrimeFaces PRO users we asked PrimeTek to implement this HIDE_RESOURCE_VERSION toggle which improves overall PrimeFaces security, maybe by a little, but in the right direction.

**Comment by tandraschko** [comment]
the param just improves absolutly nothing
1) you can easily check the used technologies by includes JS sources or CSS
2) you can easily get the PF version via JS: PrimeFaces.VERSION

**Comment by melloware** [comment]
agree with @tandraschko it was a non-sense requirement from your security department.

See this StackOverflow on why: https://security.stackexchange.com/questions/215205/is-it-really-security-misconfiguration-to-show-a-version-number/215212#215212

**Comment by segaura** [comment]
I agree with everybody, the fact you are right does not necessary means my security department (and similarly OWASP) is wrong.
We had similar extensive discussion with PrimeTek support team before going this way ...now that I remember, they were really stimulating.

I understand that in _this specific case_ the technology and its version can be obtained in other way but having the version in the querystring add _another way_ to obtain them. In security 

I understand also this is a generic requirements which applies everywhere, a best practice which in turn I personally do not discuss every time.

I propose you two additional non-strictly-security-related perspectives I have, the first one is the architectural one: is this version in querystring really necessary? Is it part of a good architectural design? Can I do the same without it.
Often a design that can do the same thing without some elements is more robust and generally better.

The latter one is the user experience one: I interact with my web application sending it requests; let's say I do the same thing now and a year later; why have the requests to be different in the two sessions only because a library has been updated?  If you think this is negligible by the user point of view, consider that probably this querystring parameter forces developers to update their Gatling and WebDriver scripts accordingly.

**Comment by melloware** [comment]
@segaura without the `v=` string then your browser cache won't be invalidated when you upgrade from PF 13.0.0 to PF 13.0.1 so now you don't get latest JS and CSS changes in that version which can break and annoy your customers.

Sure it could be a meaningless string like `v=123472205p6` but it would have to be static per PF version else it would reload your CSS and JS every time.  So now the question is back to that the version number `v=13.0.1` makes the most sense for cache invalidation while exposing little to no security information any hacker couldn't already discover by just browsing the code in your F12 console?


Also with a meaningless string like `v=123472205p6` what hackers will do is just make a table like this..

```
v=123472205p6    PF 13.0
v=86753095g1     PF 14.0
```

so you still are giving away version information.

At the end of the day all you are doing is trying to satisfy a security department that does NOT understand the core issue and realizing this isn't making your application any more secure.

**Comment by segaura** [comment]
> @segaura without the `v=` string then your browser cache won't be invalidated when you upgrade from PF 13.0.0 to PF 13.0.1 so now you don't get latest JS and CSS changes in that version which can break and annoy your customers.

This is an interesting example.

As I said: can this cache invalidation be obtained without this querystring parameter?
I think the answer is yes: for instance if each static resource includes a hash of the file content in its name

Is this solution better?
I think it is. Now a file which content is not changing is not refreshed in vain inside the browser cache between two primefaces[-extensions] versions. In addition this makes more happy some security departments.

Whenever possible we already moved our static resources to this content-hash-in-the-filename pattern, it works with primefaces resources, also. As far as I can remember it is done in a build step, possibly by a maven plugin, but I can be wrong.

**Comment by melloware** [comment]
Yes that is possible. But it all goes back to "why" and "is it worth it" and the answer is definitely NO. your app is not more secure all you have done is make someone in your security department happy who doesn't clearly know anything about security...

**Comment by melloware** [comment]
Also i believe this all will work if you make your hash `?v=<hash>` the `v=` is the important part.

**Comment by segaura** [comment]
> Also i believe this all will work if you make your hash `?v=<hash>` the `v=` is the important part.

Correct, and if _v_ stands somehow for _version_, it is now the "version" of the file which in turn changes only if content change, not the version of the library.
We are going exactly like this, we have a `?ourHashSomething=<hash>`.

This has not to do with security, it is a matter of performance, efficiency and ultimately elegance.
But looking back at the issue, it can be a way to efficiently remove the library version from the querystring.

My security department only wants to make OWASP and MITRE guys happy, the ones who wrote [A05:2021](https://owasp.org/Top10/A05_2021-Security_Misconfiguration/) and [CWE-200](https://cwe.mitre.org/data/definitions/200.html).
I want to make my security department happy so I asked PrimeTek to add the `HIDE_RESOURCE_VERSION` toggle.
Now you have the opportunity to make all of us happy, supporting the `?v=something` absence :-)

**Comment by melloware** [comment]
I stand by this is correct: https://security.stackexchange.com/questions/215205/is-it-really-security-misconfiguration-to-show-a-version-number/215212#215212

You are not meeting any OWASP requirement you are jus tmaking yourself feel better.  it doesn't change the fact that the PrimeFaces and Jquery versions can easily be determined by a hacker just inspecting the browser source code.

**Comment by melloware** [comment]
@segaura here is a MonkeyPatch for you to get DocumentViewer working with your code just replace `v=` in the code below to `ourHashSomething=` and the code will work.

```js
PrimeFaces.resources.getFacesResource = function(name, library, version) {
  // just get sure - name shoudln't start with a slash
  if (name.indexOf('/') === 0) {
    name = name.substring(1, name.length);
  }

  // find any JS served JSF resource
  var scriptURI = PrimeFaces.resources.getResourceScriptURI();
  var scriptName = PrimeFaces.resources.getResourceScriptName(scriptURI);

  // replace core.js with our custom name
  scriptURI = scriptURI.replace(scriptName, name);

  // find the library like ln=primefaces
  var libraryRegex = new RegExp('[?&]([^&=]*)ln=(.*?)(&|$)');

  // find library to replace e.g. 'ln=primefaces'
  var currentLibraryName = 'ln=' + libraryRegex.exec(scriptURI)[2];

  // In a portlet environment, url parameters may be namespaced.
  var namespace = '';
  var urlParametersAreNamespaced = !(scriptURI.indexOf('?' + currentLibraryName) > -1 ||
    scriptURI.indexOf('&' + currentLibraryName) > -1);

  if (urlParametersAreNamespaced) {
    namespace = new RegExp('[?&]([^&=]+)' + currentLibraryName + '($|&)').exec(scriptURI)[1];
  }

  // If the parameters are namespaced, the namespace must be included
  // when replacing parameters.
  scriptURI = scriptURI.replace(namespace + currentLibraryName, namespace + 'ln=' + library);

  if (version) {
    var extractedVersion = new RegExp('[?&]' + namespace + 'v=([^&]*)').exec(scriptURI)[1];
    scriptURI = scriptURI.replace(namespace + 'v=' + extractedVersion, namespace + 'v=' + version);
  }

  var prefix = window.location.protocol + '//' + window.location.host;
  return scriptURI.indexOf(prefix) >= 0 ? scriptURI : prefix + scriptURI;
};

/**
 * Gets the resource URI of the first Javascript JS file served as a JSF resource.
 * 
 * @return {string} The first JavasScript resource URI.
 */
PrimeFaces.resources.getResourceScriptURI = function() {
  if (!PrimeFaces.resources.SCRIPT_URI) {
    function findScriptWithVersionParam(scripts) {
      scripts.each(function() {
        var src = $(this).attr('src');
        if (src && src.indexOf('v=') !== -1) {
          PrimeFaces.resources.SCRIPT_URI = src;
          return false; // Exit the loop early
        }
      });
    }

    // normal '/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=13.0.5'
    findScriptWithVersionParam($('script[src*="/' + PrimeFaces.RESOURCE_IDENTIFIER + '/"]'));

    // portlet 'javax.faces.resource=jquery/jquery.js.xhtml?ln=primefaces&v=13.0.5'
    if (!PrimeFaces.resources.SCRIPT_URI) {
      findScriptWithVersionParam($('script[src*="' + PrimeFaces.RESOURCE_IDENTIFIER + '="]'));
    }
  }
  return PrimeFaces.resources.SCRIPT_URI;
};
```
