### ISSUE TITLE
SunEditor C Code loses <stdio.h> - strictMode does not apply

### ISSUE THREAD

**Issue by bercolax** [primefaces-extensions/primefaces-extensions#1639]
### Describe the bug

Version Used: 14.0.4
- In the sunEditor, i enter the following C code (choosing the code in the drop down). The code is saved in the database after the < being converted to ampersand lt ;
`#include<stdio.h>`

int main()
{
   //more code here
}

- Later when I edit the content again, <stdio.h> is lost and only #include is present in the editor.

### Expected behavior

The <stdio.h> must be retained.

### PrimeFaces Extensions version

14.0.4

### JSF implementation

Mojarra

### JSF version

3.0.1

### Browser(s)

Chrome, Firefox

**Comment by melloware** [comment]
Can you paste your SunEditor XHTML configuration here? Using secure mode?

**Comment by bercolax** [comment]
```xml
<pe:sunEditor allowFormatting="false"   secure="false" id="reference" widgetVar="description" value="#{programCodeAction.program.description}" required="true" requiredMessage="Please enter description"
                                            mode="classic"   toolbar="[['font','fontSize','formatBlock'],['paragraphStyle','blockquote'], ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript', 'removeFormat'],
                                            '/'
                                            ,['fontColor', 'hiliteColor', 'outdent', 'indent', 'align', 'horizontalRule', 'list', 'table'],
                                            ['link', 'image', 'audio', 'video', 'fullScreen', 'showBlocks', 'codeView', 'preview', 'print', 'save']]"/>
```

**Comment by bercolax** [comment]
In the 0-suneditor.min.js file (used in Maven build under primefaces-extensions-14.0.4/core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor, the code for the function cleanHTML is 

'cleanHTML:function(e,t,n){if(!l.strictMode)return e;'

In the file 1-suneditor-widget.js, the strictMode is set to true. (As SunEditor is using negation, should we set the strictMode to false?)

'// do not alter HTML
this.cfg.strictMode = true;'

**Comment by melloware** [comment]
have you tried it with `strictMode=false` ?   strictMode was added in this Fix: https://github.com/primefaces-extensions/primefaces-extensions/issues/1527

as was recommended by the SunEditor developer? we used to have this hack and he added `strictMode` setting to replace overriding those function.

https://github.com/JiHong88/suneditor/issues/1320

**Comment by bercolax** [comment]
In the extender function, how to get hold of the widget handle of the sun editor instance? 

` function editorExtender() {
            // this = widget
            // this.cfg = JSON configuration
            this.cfg.katex = window.katex;
            this.cfg.font = ["Serif", "Sans-Serif", "Monospace", "Roboto", "Bruno Ace SC"];
            this.cfg.defaultStyle = "font-family:Serif;";
        };`

**Comment by melloware** [comment]
PR submitted it has nothing to do with that `strictMode`

**Comment by jepsar** [comment]
@bercolax If you are just using C code, you might want to have a look at https://www.primefaces.org/showcase-ext/views/monacoEditor.jsf

**Comment by melloware** [comment]
@bercolax this fix break's font usage with SunEditor.  I would switch to MonacoEditor.

**Comment by melloware** [comment]
nevermind its a bug in HTMLSanitizer: https://github.com/OWASP/java-html-sanitizer/issues/232
