### ISSUE TITLE
SunEditor: Moves Tables

### ISSUE THREAD

**Issue by cbclark64** [primefaces-extensions/primefaces-extensions#1664]
### Describe the bug

We have a page that contains the sunEditor component. If we go into codeView mode and paste the contents the attached HTML file, the tables are moved to the end of the HTML stream.

### Reproducer

Go to the PrimeFaces Extensions showcase.  Select the sunEditor component page, Basic Usage.  Go into Code View and paste the contents of the attached file.

### Expected behavior

The tables should be inline where they exist in the source HTML.
[Holiday and Vacation Pay Sick Leave Jury Duty Bereavement Leave.txt](https://github.com/user-attachments/files/16786331/Holiday.and.Vacation.Pay.Sick.Leave.Jury.Duty.Bereavement.Leave.txt)

### PrimeFaces Extensions version

8.0.3

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
Assuming this is spam

**Comment by stolp** [comment]
I cannot see why this is spam, looks just like an example text to me.

Yet I tried it with the current version (14.0.4) of PrimeFaces and the tables came out ok for me. So it is ok to close I guess.

**Comment by melloware** [comment]
oh because it says PFE 8.0.3 and SunEditor wasn't until 13 😄 

I thought this was some AI generated non-sense. Seeing it a lot on GitHub lately.

**Comment by melloware** [comment]
@cbclark64 have you tried this with PFE 14.0.4?

**Comment by cbclark64** [comment]
> Assuming this is spam

This is not spam, thanks.

**Comment by cbclark64** [comment]
> oh because it says PFE 8.0.3 and SunEditor wasn't until 13 😄
> 
> I thought this was some AI generated non-sense. Seeing it a lot on GitHub lately.

I used IntelliJ to search for primefaces*jar and it did not show the actual one in use. It showed one in an unused module. 
It is actually version 13.0.4

**Comment by cbclark64** [comment]
> @cbclark64 have you tried this with PFE 14.0.4?

No, but I will do that now.  Is 14.0.4 running on the showcase site?  It's easy to show the error there.

**Comment by melloware** [comment]
No showcase is running 14.0.0 not 14.0.4

**Comment by melloware** [comment]
OK i am able to reproduce it locally on 14.0.5  Not sure whether this is a Suneditor bug or not.

**Comment by melloware** [comment]
OK yep its a bug in Suneditor please report it. You can go here and try it for yourself this takes PFE out of the equation: http://suneditor.com/sample/index.html

So report it on his GitHub: https://github.com/JiHong88/suneditor/issues

**Comment by cbclark64** [comment]
> OK yep its a bug in Suneditor please report it. You can go here and try it for yourself this takes PFE out of the equation: http://suneditor.com/sample/index.html
> 
> So report it on his GitHub: https://github.com/JiHong88/suneditor/issues

I've reported it to Ji Hong.

**Comment by melloware** [comment]
Issue https://github.com/JiHong88/suneditor/issues/1442
