### ISSUE TITLE
TimePicker: spinner buttons do not work with custom format

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#167]
Set to "00:00" and submit. Fails both in production and when built from source.

**Comment by melloware** [comment]
Hmm cant reproduce this in the Showcase?

![image](https://user-images.githubusercontent.com/4399574/95663653-16363b80-0b0f-11eb-85de-5388fdf85047.png)

**Comment by jepsar** [comment]
Hmm.. it seems it does work in production. I think this may be the same issue with JDK 11 we had with the remote command examples.

**Comment by melloware** [comment]
Let me know what you find out i tried it in JDK 11 as well and it seems to be working.

**Comment by jepsar** [comment]
This is what I'm getting

<img width="269" alt="Screen Shot 2020-10-25 at 09 31 03" src="https://user-images.githubusercontent.com/7500178/97102343-dd689b80-16a4-11eb-95f6-95ca98e20cd7.png">

**Comment by jepsar** [comment]
Hmm.. I'm no longer able to run the showcase with JDK 8? I was able to with this command from my history:
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home mvn clean jetty:run
```
Now that gives me:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project showcase: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by jepsar** [comment]
Oh, It's not JDK related. When I click the input it works.. when I click the spinner, it will only give me "00:00"

**Comment by melloware** [comment]
Thanks for debugging let me look at it.   Also the Compiler Plugin upgrade is what I think broke JDK8 as its not longer supported so I think I can back that plugin version up.

**Comment by melloware** [comment]
Oh yeah its the customization example.  Since it doesn't have a first value to spin to it spins to 00:00 and thus is no a valid value for the customized TimePicker.
```javascript
          // if the value is empty, set 00:00 and process with spinning
            this.jq.val('00:00');
```
