### ISSUE TITLE
SunEditor: Configure HtmlSanitizer to keep img styles and dataset attributes

### ISSUE THREAD

**Issue by rheia475** [primefaces-extensions/primefaces-extensions#1711]
### Describe the bug

Hi,

this issue is very similar to this [SunEditor: Configure HtmlSanitizer to keep table styles](https://github.com/primefaces-extensions/primefaces-extensions/issues/1580)

In `SunEditor` you can add images and align them (left, center, right) but the added `dataset` properties like `data-rotate` will be removed by the HtmlSanitizer and after saving the content of the editor `SunEditor` just seems to reset the `dataset` to the default.

The result is an image with the default alignment set (left) instead of whatever alignment that got set before.

Before:
```html
<div class="se-component se-image-container __se__float-center"><figure><img src="data:image/png;..." alt="" data-rotate="" data-proportion="true" data-rotatex="" data-rotatey="" data-align="center" width="" height="" data-size="," data-percentage="auto,auto" data-index="0" data-file-name="logo.png" data-file-size="65417" data-origin="," style=""></figure></div>
```

After:
```html
<div class="se-component se-image-container __se__float-none"><figure><img src="data:image/png;..." data-index="0" data-file-name="DJTYnFJyBcAAAAASdEVYdEVYSUY6T3JpZW50YXRpb24AMYRY7O8AAAAASUVORK5CYII=" data-file-size="0" origin-size="370,370" data-origin="," data-size="," data-rotate="" data-rotatex="" data-rotatey="" width="" height="" data-align="none" data-percentage="auto,auto" style=""></figure></div>
```

I don't exactly know how maroswal monkeypatched his Java code - I just copy pasted the `HtmlSanitizer` class into my own `package org.primefaces.extensions.util` and basically overwrote the code with the help of `maven-shade-plugin` since I'm using Maven in my project.

Anyways, the only thing I changed was the `HTML_IMAGES_SANITIZER`:

```java
    private static final PolicyFactory HTML_IMAGES_SANITIZER = new HtmlPolicyBuilder()
            .allowUrlProtocols("data", "http", "https")
            .allowElements("img")
            .allowAttributes("src")
            .matching(Pattern.compile("^(data:image/(gif|png|jpeg|webp|svg)[,;]|http|https|mailto|//).+", Pattern.CASE_INSENSITIVE))
            .onElements("img")
            .allowAttributes(
                    "data-rotate",
                    "data-proportion",
                    "data-rotatex",
                    "data-rotatey",
                    "data-size",
                    "data-align",
                    "data-percentage",
                    "data-index",
                    "data-file-name",
                    "data-file-size",
                    "data-origin"
            ).onElements("img")
            .toFactory();
```

I added additional attributes - all the `dataset` properties that are used by `SunEditor`.
This seems to keep the alignment of the image. It would be nice to be able to directly configure the `HtmlSanitizer` without any "dirty" workarounds.

### Expected behavior

Either make `HtmlSanitizer` somehow configurable or add img `dataset` attributes to the styles sanitizer to keep the applied imagestyles.

```java
    private static final PolicyFactory HTML_IMAGES_SANITIZER = new HtmlPolicyBuilder()
            .allowUrlProtocols("data", "http", "https")
            .allowElements("img")
            .allowAttributes("src")
            .matching(Pattern.compile("^(data:image/(gif|png|jpeg|webp|svg)[,;]|http|https|mailto|//).+", Pattern.CASE_INSENSITIVE))
            .onElements("img")
            .allowAttributes(
                    "data-rotate",
                    "data-proportion",
                    "data-rotatex",
                    "data-rotatey",
                    "data-size",
                    "data-align",
                    "data-percentage",
                    "data-index",
                    "data-file-name",
                    "data-file-size",
                    "data-origin"
            ).onElements("img")
            .toFactory();
```

### PrimeFaces Extensions version

14.0.5

### JSF implementation

Mojarra

### JSF version

4.0.1

**Comment by melloware** [comment]
Thanks this will be in 14.0.6

**Comment by melloware** [comment]
OK fixed in main to your original fix. I see the issue now.

**Comment by rheia475** [comment]
@melloware Thanks for fixing it this quickly!

**Comment by melloware** [comment]
Thanks for testing!
