### ISSUE TITLE
SunEditor: does not remove newline characters (CR, LF, CRLF)

### ISSUE THREAD

**Issue by roabol** [primefaces-extensions/primefaces-extensions#1722]
### Describe the bug

I am using the <pe:sunEditor> component to publish content in my application. Copying and pasting from a Microsoft Word document works fine, but when the document is opened with LibreOffice (https://www.libreoffice.org/download/download/), the SunEditor fails to remove newline characters (CR, LF, CRLF). Could you help me with this issue? I thought about using the onPaste event, but I’m not sure how to implement it with the <pe:sunEditor> component.

The issue occurs across all browsers, but in Firefox, it happens immediately, while in other browsers it only happens when I submit the form.

I will attach images showing how the text looks after pasting it into the SunEditor.

* document libreoffice
![image](https://github.com/user-attachments/assets/32033839-52f3-4839-886c-58b61ff28756)

* SunEditor content that was pasted
![image](https://github.com/user-attachments/assets/252ca272-7893-49d8-b801-1640ac76c6de)

* content pasted into the primefaces-extensions showcase 
![image](https://github.com/user-attachments/assets/bda8205d-30bf-4e4d-b719-634df694c4f1)

* SunEditor source code 
![image](https://github.com/user-attachments/assets/4f05c983-410e-45a7-9835-3659e5566294)

### PrimeFaces Extensions version

14.0.6

### JSF implementation

Mojarra

**Comment by melloware** [comment]
Looks like a known SunEditor issue, you can use the Extender functionality to add the hack from this ticket: https://github.com/JiHong88/suneditor/issues/1433

**Comment by roabol** [comment]
Thanks for responding so quickly!

I can capture the onpaste event through the Extender functionality. If you can help me with an example, it would be a great help. Thanks!

**Comment by melloware** [comment]
you just need this example: https://www.primefaces.org/showcase-ext/sections/sunEditor/extender.jsf

**Comment by roabol** [comment]
Thanks again. I tried to follow the example, but my code didn't work for the onPaste event. Could you point out where I'm going wrong?

```
function editorExtender() {
        console.log("editor extender!");
        const editor = this;

        editor.onPaste = function (e, cleanData, maxCharCount) {
                console.log("onpaste event detected!");
    };
}
```

**Comment by melloware** [comment]
Ahh the extender is for changing the configs before the SunEditor gets created the `editor` itself doesn't exist yet at this point.   Try this..

```xml
<pe:sunEditor id="sunEditor" widgetVar="sunEditor" value="#{basicSunEditorController.html}">
        <f:attribute name="widgetPostConstruct" value="widget.editor.onPaste = function (e, cleanData, maxCharCount) {console.log('onpaste event detected!'); };" />
</pe:sunEditor>

```

**Comment by melloware** [comment]
I just tested the above and it works!

**Comment by roabol** [comment]
Yes, it worked here too. Thank you very much!
