### ISSUE TITLE
sunEditor needs new line (line break) option instead of <br> (as in TinyMCE) 

### ISSUE THREAD

**Issue by bercolax** [primefaces-extensions/primefaces-extensions#1726]
### Describe the feature you would like to see added

Recently several code syntax highlight plug-ins are removing HTML in the code snippets. When we use sunEditor code (in the dropdown) it uses `<br> `tag for the new lines. Inturn these `<br>` tags are removed during syntax highlighting and hence all the lines (of code) are highlighted in a single line. 
Hence we request an option to retain the line breaks instead of converting them to `<br> `tags.
The `<p>` in PrimeFaces editor is not also helping as `<p>` tags are also removed.

**Comment by melloware** [comment]
@bercolax can you give me an example?  Is SunEditor stripping the `<br>` or is it the PFE HTML Sanitizer?  According to SunEditor docs `<br>` is default Whitelist allowed tag.

```
// _defaultTagsWhitelist : 'br|p|div|pre|blockquote|h1|h2|h3|h4|h5|h6|ol|ul|li|hr|figure|figcaption|img|iframe|audio|video|table|thead|tbody|tr|th|td|a|b|strong|var|i|em|u|ins|s|span|strike|del|sub|sup|code|svg|path|details|summary'
```

**Comment by bercolax** [comment]
SunEditor is not stripping` <br>`. But instead it is doing the reverse. It is replacing the new line "\n" with `<br>`.
As a result, when we use a syntax highlighting plugin like prism or highlight.js, as `<br>` is a HTML tag it is removed by the syntax highlighter. So all the lines of code are displayed in a single line. 
I copy the code from an IDE like Netbeans or Eclipse and paste into the SunEditor. So the new lines are replaced by `<br>`

**Comment by melloware** [comment]
Ahhh thanks for the explanation

**Comment by melloware** [comment]
A few things. 

1. Read this issue: https://github.com/primefaces-extensions/primefaces-extensions/issues/1722 on how to control the Paste yourself.
2. looks like a SunEditor bug you can upvote: https://github.com/JiHong88/suneditor/issues/1317 or https://github.com/JiHong88/suneditor/issues/1434

**Comment by melloware** [comment]
Let us know if overriding the paste function works and post your solution please!

**Comment by melloware** [comment]
@bercolax did you get this working?
