### ISSUE TITLE
Suneditor: Adding new attribute strictMode

### ISSUE THREAD

**Issue by raphy2503** [primefaces-extensions/primefaces-extensions#1758]
### Describe the feature you would like to see added

The strictMode already exists on the suneditor component and should also be exposed in the primefaces suneditor component.

### Is your feature request related to a problem?

Setting the strictMode attribute in the extender javascript will be overwritten by the primefaces extensions initialization.

**Comment by melloware** [comment]
I will take a look at this should be easy to add.

**Comment by raphy2503** [comment]
Thanx a lot, looks good :-)

**Comment by melloware** [comment]
Thanks for testing!
