### ISSUE TITLE
Sheet: changes stack up

### ISSUE THREAD

**Issue by morvael** [primefaces-extensions/primefaces-extensions#1767]
### Describe the bug

Made a simple sheet:
![image](https://github.com/user-attachments/assets/4110e728-7e64-4e2a-a478-f308f2672072)

Added logging to setters. And what do I see:
first cell changed - 1 setter logged
second cell changed - 2 setters logged
third cell changed - 3 setters logged
fourth cell changed - 4 setters logged

It seems like it isn't clearing the list of "updates", just reapplies them on top of all previous ones (so this will be degratation of performance).

Will make reproducer, just need some time.

### Reproducer

[primefaces-test-sheet.tar.gz](https://github.com/user-attachments/files/17827853/primefaces-test-sheet.tar.gz)

### Expected behavior

A single setter logged per cell changed.

### PrimeFaces Extensions version

14.0.7.1

### JSF implementation

Mojarra

### JSF version

4.0

### Browser(s)

Firefox 132.0.1

**Comment by morvael** [comment]
Reproducer:
[primefaces-test-sheet.tar.gz](https://github.com/user-attachments/files/17827853/primefaces-test-sheet.tar.gz)

**Comment by morvael** [comment]
Edited cells (in this order): ffff, rrrr, zzz:
![image](https://github.com/user-attachments/assets/2be07f74-a9fb-4d35-a175-b878deb9ba01)

Log:
```
Nov 20, 2024 10:04:40 AM org.primefaces.test.Data setValue
INFO: text1_3.setValue (key k3, value ffff)
Nov 20, 2024 10:04:40 AM org.primefaces.test.TestView onCellChange
INFO: onCellChange(org.primefaces.extensions.event.SheetEvent[source=org.primefaces.extensions.component.sheet.Sheet@5e267404])
Nov 20, 2024 10:04:42 AM org.primefaces.test.Data setValue
INFO: text1_3.setValue (key k3, value ffff)
Nov 20, 2024 10:04:42 AM org.primefaces.test.Data setValue
INFO: text1_2.setValue (key k4, value rrrr)
Nov 20, 2024 10:04:42 AM org.primefaces.test.TestView onCellChange
INFO: onCellChange(org.primefaces.extensions.event.SheetEvent[source=org.primefaces.extensions.component.sheet.Sheet@78bacb05])
Nov 20, 2024 10:04:57 AM org.primefaces.test.Data setValue
INFO: text1_2.setValue (key k4, value rrrr)
Nov 20, 2024 10:04:57 AM org.primefaces.test.Data setValue
INFO: text1_4.setValue (key k5, value zzz)
Nov 20, 2024 10:04:57 AM org.primefaces.test.Data setValue
INFO: text1_3.setValue (key k3, value ffff)
Nov 20, 2024 10:04:57 AM org.primefaces.test.TestView onCellChange
INFO: onCellChange(org.primefaces.extensions.event.SheetEvent[source=org.primefaces.extensions.component.sheet.Sheet@68c8ada9])
```

**Comment by morvael** [comment]
See how there's 1x setValue, then 2x setValue, then 3x setValue

**Comment by morvael** [comment]
I guess maybe I can clear the list by doing commitUpdates in listener? But why this is the default mode if the component directly calls my setters?

**Comment by melloware** [comment]
looks like you didn't follow the showcase.  you need to call `commitUpdates` to tell it you have finished processing the ones you want to process.

```java
public void cellChangeEvent(final SheetEvent event) {
        final Sheet sheet = event.getSheet();
        final List<SheetUpdate> updates = sheet.getUpdates();
        // A SheetUpdate exists for each column updated, the same row may
        // appear more than once. For this reason we will track those we already
        // persisted
        final HashSet<Asset> processed = new HashSet<Asset>();
        int rowUpdates = 0;
        for (final SheetUpdate update : updates) {
            final Asset asset = (Asset) update.getRowData();
            if (processed.contains(asset)) {
                continue;
            }
            System.out.println("Asset " + asset.getAssetId() + " updated.");
            rowUpdates++;
        }
        sheet.commitUpdates();
        FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage("Update Success", rowUpdates + " rows updated"));
    }
```

**Comment by morvael** [comment]
But I get no choice of processing or not, because my setters in objects are called directly. That is what is misleading here. Kind of expected the thing to run in some auto-commit mode. It would be different if it wouldn't use setters and just called the event method.

**Comment by morvael** [comment]
I also have no other place to ask: moving through cells via Tab clears some. What controls that behavior? I'd like Tab enter be the same as click enter.

**Comment by melloware** [comment]
Hmm I will test myself I see what you mean but weird in 10 years I have never had an issue so I am doing something differently I suspect

Also TAB is controlled by HandsonTable. I would not expect a cell to clear on tabbing through it.

**Comment by melloware** [comment]
You should use the Discord channel for questions.  There is a PrimeFaces Extensions channel specifically on Discord.

**Comment by morvael** [comment]
When you tab through cells in normal spreadsheet app cell content remains unchanged:
![image](https://github.com/user-attachments/assets/213dd08c-b434-4324-836a-5509c48151c7)

When you tab here:
![image](https://github.com/user-attachments/assets/7142811e-3bf6-4cad-9728-a4c47182a545)
you get:
![image](https://github.com/user-attachments/assets/fa1fad3d-aad0-4dfd-895e-49db5b582f44)
and gone:
![image](https://github.com/user-attachments/assets/53e431dc-1025-4743-85d8-45cb432526ab)

**Comment by melloware** [comment]
Weird doesn't happen on my showcase does it?

**Comment by morvael** [comment]
(sorry page refreshed last screenshot is from regenerated view, but you get my meaning)

Clicking is safe:
![image](https://github.com/user-attachments/assets/a577ba8b-a572-4c8d-a2d9-d96a440282b7)
Doubleclick:
![image](https://github.com/user-attachments/assets/edf52300-f37d-4321-8e45-e3eebd864e3c)

Kind of tab already acts as "key typed" so clears the value.

Maybe it's limited to Firefox?

**Comment by melloware** [comment]
Also have a customer using this for 10 years without issues tabbing through thousands of cells.

**Comment by morvael** [comment]
Yeah, edge is OK. So this time Firefox is causing problems, unlike in the "million inputs" issue :D

**Comment by morvael** [comment]
I can report this as separate issue, browser specific bug. Or does it have to be reported against HandsonTable?

**Comment by melloware** [comment]
Most likely a HandsonTable issue as this is just a wrapper around HT 6.2.2 which is the last open source version before they made it a commercial project.

**Comment by morvael** [comment]
Oops, like iText. That will mean they'll probably not fix it in an old unsupported version :(

**Comment by morvael** [comment]
So there's a risk this will stop working one day. But I have no choice for now :)

**Comment by melloware** [comment]
Yep like I said have a customer using it 10 years in production without issue. But yeah don't expect any HandsonTable fixes.

**Comment by melloware** [comment]
Here is why..

```
java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
org.primefaces.test.Data.setValue(Data.java:48)
org.primefaces.test.Data$ValueAsObject.setValue(Data.java:80)
java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
java.base/java.lang.reflect.Method.invoke(Method.java:580)
jakarta.el.BeanELResolver.setValue(BeanELResolver.java:413)
com.sun.faces.el.DemuxCompositeELResolver._setValue(DemuxCompositeELResolver.java:199)
com.sun.faces.el.DemuxCompositeELResolver.setValue(DemuxCompositeELResolver.java:222)
org.apache.el.parser.AstValue.setValue(AstValue.java:202)
org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:222)
org.jboss.weld.module.web.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:95)
org.primefaces.extensions.component.sheet.Sheet.updateModel(Sheet.java:774)
jakarta.faces.component.UIInput.processUpdates(UIInput.java:622)
com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:619)
com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:158)
jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1266)
jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
jakarta.faces.component.UIForm.visitTree(UIForm.java:344)
jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:394)
com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:260)
org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:61)
jakarta.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1309)
com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:50)
```


Code explaining why it does this...

```java
/**
     * Override to update model with local values. Note that this is where things can be fragile in that we can successfully update some values and fail on
     * others. There is no clean way to roll back the updates, but we also need to fail processing. Consider keeping old values as we update (need for event
     * anyhow) and if there is a failure attempt to roll back by updating successful model updates with the old value. This may not all be necessary.
     */
    @Override
    public void updateModel(final FacesContext context) {
        final Iterator<Entry<SheetRowColIndex, Object>> entries = localValues.entrySet().iterator();
        // Keep track of the dirtied rows for ajax callbacks so we can send
        // updates on what was touched
        final HashSet<String> dirtyRows = new HashSet<>();
        while (entries.hasNext()) {
            final Entry<SheetRowColIndex, Object> entry = entries.next();

            final Object newValue = ToBeRemoved.class.equals(entry.getValue()) ? null : entry.getValue();
            final String rowKey = entry.getKey().getRowKey();
            final int col = entry.getKey().getColIndex();
            final SheetColumn column = getColumns().get(col);
            setRowVar(context, rowKey);
            final Object rowVal = rowMap.get(rowKey);

            final ValueExpression ve = column.getValueExpression(PropertyKeys.value.name());
            final ELContext elContext = context.getELContext();
            final Object oldValue = ve.getValue(elContext);
            ve.setValue(elContext, newValue);
            entries.remove();
            appendUpdateEvent(getRowKeyValue(context), col, rowVal, oldValue, newValue);
            dirtyRows.add(rowKey);
        }
        setLocalValueSet(false);
        setRowVar(context, null);

        if (context.getPartialViewContext().isPartialRequest()) {
            renderRowUpdateScript(context, dirtyRows);
        }
    }
```

**Comment by melloware** [comment]
@morvael i am also using Firefox against the PFE showcase and I can TAB through cells fine?

**Comment by morvael** [comment]
This happened for me on Linux, will re-verify. I could tab fine but the contents were erased. I think drop-down cells are not susceptible, but plain text are.

**Comment by melloware** [comment]
OK I am testing Firefox on Windows with this example: https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf

And here: https://www.primefaces.org/showcase-ext/sections/sheet/validation.jsf

I could TAB and SHIFT+TAB through the whole sheet.

**Comment by morvael** [comment]
Looks like this happens only when working via VNC...
https://github.com/user-attachments/assets/492d715d-5e58-4b49-8ade-e7cfda8c53c6

Can't replicate it on same OS-same browser run locally :smile:

**Comment by morvael** [comment]
> Here is why..
> Code explaining why it does this...

Anyway, I didn't understand this post. All I do for now in cell change is:
```
    public void onCellChange(SheetEvent event) {
        event.getSheet().commitUpdates();
    }
```
and it appears to be working as I want it (my setters are called, value is re-read back, only single call is made per cell changed). Should I do some more here?

**Comment by melloware** [comment]
Nope that is what I would do!   The only reason we did it this way is our client wanted to be edit say cell 5, 77, and 94 and then process those in 1 batch to the database.  But your solution is exactly what I would do!
