### ISSUE TITLE
Sheet: error in JSON

### ISSUE THREAD

**Issue by morvael** [primefaces-extensions/primefaces-extensions#1773]
### Describe the bug

I have a problem with Sheet that I cannot write replicator for, because it happens only on full site. When changing other form elements would cause the sheet to be shown and filled the sheet "table" does not appear at all (there's only header with my custom buttons visible). In the JS console there's this error logged:
![image](https://github.com/user-attachments/assets/3f4713e9-01a5-43d6-b915-ea4e4ab2fd65)
Before I spotted this I was going like crazy replacing all null-possible calls with safe method from bean, but it didn't help (I was thinking some NPE was breaking the sheet).

What I see in the json response from when the sheet should appear is indeed a JSON with one `[[` and two `]]`, so maybe something somewhere is produced incorrectly. I think I can't show everything publicly but here are crucial parts:
```
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>...,data:[[" ",...
...,""</script></td></tr></tbody></table>
</form>]]></update><update id="j_id1:jakarta.faces.ViewState:0"><![CDATA[-4105232086132405834:-3327090845627537063]]></update></changes></partial-response>
```

I think the bug is in the fact that `data` array of arrays isn't closed at all. It's actually cut off like there would be a size limit, which isn't enough for my sheet.

```
,errors:"{}",data:[[" "," ","\-3000.00","24000.00","",
...
""],["18","17:30 \- 18:00","",
...
,"","",""</script>
```

It should end with 24:00, but it manages to reach only 18:00 and is then cut off. What controls that limit?

### Expected behavior

Sheet renders correctly.

### PrimeFaces Extensions version

14.0.7.1

### JSF implementation

Mojarra

### JSF version

4.0

### Browser(s)

Firefox 132.0.1

**Comment by morvael** [comment]
There's no such bug in "edit" mode where the thing is filled on first page load, but is broken when the thing is to be filled with partial ajax update. So perhaps there's a limit on partial ajax update response size. But where? In PF? In Sheet? In my Wildfly?

**Comment by morvael** [comment]
What's make me think it's not Wildfly configuration is that it's not that the entire response is cut off, because it does contain some text **after** broken data, only that data is truncated.

**Comment by morvael** [comment]
Ok, so if that's that I can probably write a reproducer that makes big response in partial update.

**Comment by morvael** [comment]
Oh, but of course it will happily render 256x100 cells from partial update on Jetty :cry:

**Comment by morvael** [comment]
Response on Jetty is about 109kB, while my truncated response on wildfly is about 49kB uncompressed.

**Comment by morvael** [comment]
See no limits here:
`final JavascriptVarBuilder jsData = new JavascriptVarBuilder(null, false);`
`wb.nativeAttr("data", jsData.closeVar().toString());`
So the deed must somehow happen in
`rw.write(value);` (WidgetBuilder.nativeAttr)

It would be indeed able to cut only value while leaving rest of response intact.

**Comment by morvael** [comment]
I see there might be some of your classes involved in this (for example PrimePartialResponseWriter), as well as some Wildfly implementation specifics at its core.

**Comment by morvael** [comment]
Managed to run pf reproducer on Wildfly, and got normal response of 108kB :man_facepalming:

**Comment by morvael** [comment]
I'm even running on the same instance of Wildfly and reproducer is working.

Bad response:
![image](https://github.com/user-attachments/assets/f614620d-641a-49f5-8329-c7094e849dbc)

Good response:
![image](https://github.com/user-attachments/assets/33ee8465-fcf0-4fd3-9739-77702c310ae1)

Looks like more is decompressing to less.

**Comment by morvael** [comment]
Disabling gzip filter changed nothing, `,"","","","</script><` - value is still brutally truncated

**Comment by morvael** [comment]
Ok, I'm getting somewhere. As soon as I use non-ASCII in data everythings stops working.

**Comment by morvael** [comment]
And this doesn't happen on Jetty, so perhaps com.sun.faces.renderkit.html_basic.HtmlResponseWriter is to blame.

**Comment by morvael** [comment]
At this stage the text is still correct, I'm afraid the matcher will kill it:
![image](https://github.com/user-attachments/assets/11c2d439-ed7c-4645-b4bc-51271e276ac9)

**Comment by morvael** [comment]
Ok, it didn't do anything here and correct content went to io.undertow.servlet.spec.ServletPrintWriterDelegate - and at that moment I couldn't dig deeper. So it's somewhere in Undertow.

**Comment by morvael** [comment]
This is totally crazy:
```
        <h:form id="frmTest">
            <p:commandButton value="ĄĘĆŚŻŹ" actionListener="#{testView.fill}" update="@form"/>
            <pe:sheet id="elements"
                      widgetVar="elementsSheet"
```

This version is broken on WildFly because the button has Polish letters in value. As soon as I change value to "Fill" it works again. I guess that's because this value gets serialized somewhere in the response and kills Undertow writer.

**Comment by morvael** [comment]
[responses.tar.gz](https://github.com/user-attachments/files/17846237/responses.tar.gz)

Guess I need to report something against Undertow.

**Comment by melloware** [comment]
Do you have CharacterEncodingFilter?

```xml
    <filter>
        <filter-name>Character Encoding Filter</filter-name>
        <filter-class>org.primefaces.webapp.filter.CharacterEncodingFilter</filter-class>
    </filter>
```

**Comment by morvael** [comment]
I didn't but adding it changes nothing, as it breaks at some different level of Undertow writer. Perhaps the response is not safely escaped enough? But still this should work.

**Comment by melloware** [comment]
I have been using Undertow for 10 years and never run into this issue.  What version are you on?

**Comment by melloware** [comment]
According to BalusC everything in JSF is UTF-8: https://balusc.omnifaces.org/2009/05/unicode-how-to-get-characters-right.html

**Comment by morvael** [comment]
I've reported it here: https://issues.redhat.com/browse/UNDERTOW-2527

**Comment by morvael** [comment]
> I have been using Undertow for 10 years and never run into this issue. What version are you on?

On Undertow 2.3.17.Final from Wildfly 33.0.2.

**Comment by melloware** [comment]
ok so I write a small Undertow app and just use `<p:commandButton value="ĄĘĆŚŻŹ" actionListener="#{testView.fill}" update="@form"/>` you say it breaks?

**Comment by morvael** [comment]
Well it breaks on that large response that sheet is generating. I guess it's harder to reach that size of response on normal page.

**Comment by melloware** [comment]
it sounds like internally there is an an Undertow setting for allowing the larger response payload?

**Comment by morvael** [comment]
This is the "reproducer" I'm using though the pom was changed a bit to make it run on my WildFly:
[primefaces-test-sheet.tar.gz](https://github.com/user-attachments/files/17846474/primefaces-test-sheet.tar.gz)

**Comment by melloware** [comment]
how about this: https://stackoverflow.com/questions/55394427/post-large-json-object-using-ajax-request

**Comment by morvael** [comment]
> it sounds like internally there is an an Undertow setting for allowing the larger response payload?

Sure, but remember it's doing 108kB response no problems IF there are no Polish letters and cuts off part of it (and not the tail end, just element content!) when those letters appear.

**Comment by melloware** [comment]
You should open an Undertow ticket with your reproducer.

To confirm this works fine on Jetty?

**Comment by morvael** [comment]
Current logic is like:
`if there are non-ASCII chars in content written so far reduce xml element's value max length to 32kB else make it unlimited.`
that's why it's so crazy...

**Comment by morvael** [comment]
> To confirm this works fine on Jetty?

Yes, looks like so.

**Comment by morvael** [comment]
![image](https://github.com/user-attachments/assets/875a5172-aab7-4c83-bae4-ab87a366867d)
Magic, eh? :smile:

**Comment by melloware** [comment]
OK open an Undertow ticket and link to this ticket and I will close this ticket as "tracked in third party"

**Comment by morvael** [comment]
> I've reported it here: https://issues.redhat.com/browse/UNDERTOW-2527

opened

**Comment by morvael** [comment]
Maybe this could be worked around if you'd divide the big string in WidgetBuilder :)

**Comment by morvael** [comment]
lol comment in https://github.com/undertow-io/undertow/blob/main/servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java:
```
        //for some known charset we get optimistic and hope that
        //only ascii will be output
        //in this case we can avoid creating the encoder altogether
```

**Comment by melloware** [comment]
classic.   iwould rather not hack the widgetbuilder to work around an Undertow bug

**Comment by morvael** [comment]
Fair. Let's see what they write. What is the problem with going the official route is long time to get the fix in official build. I've already went once through patching one jar in WildFly manually until the bug was fixed 1-2 versions later.

I don't understand how they could hope to see UTF-8 and expect only ASCII. I guess a different charset name should be there like Windows-1252 or something. But not UTF-8.

```
        //for some known charset we get optimistic and hope that
        //only ascii will be output
        //in this case we can avoid creating the encoder altogether
        if (!charset.equalsIgnoreCase("utf-8") &&
                !charset.equalsIgnoreCase("iso-8859-1")) {
            createEncoder();
        }
```

**Comment by morvael** [comment]
Oh well after manually updating undertow from 2.3.17 to 2.3.18 in my WildFly 33.0.2 the bug is gone.

**Comment by melloware** [comment]
Thanks I just sent this note to another user who had reported this issue on Undertow and JSON as well he will try it tomorrow as well.
