### ISSUE TITLE
Component: DynaForm "Advanced features" showcase broken since 14.0.7 (Button does not submit via AJAX)

### ISSUE THREAD

**Issue by blutorange** [primefaces-extensions/primefaces-extensions#1794]
### Describe the bug

The "advanced features" tab of the DynaForm showcase seems to be broken since 14.0.7. Not sure what the issue is exactly. It's working fine locally with the `14.0.6` tag and below, and doesn't work with `14.0.7` and `14.0.8`. At first glance, I didn't see any change that might be responsible, though.

### Reproducer

* Pull the current master branch and start the showcase
* Go to http://localhost:8080/showcase-ext/sections/dynaform/advancedFeatures.jsf
* After 1-2 seconds, an error is logged to the console (`Widget for var 'dynaFormWidget' not available!`) and the page becomes blank

The JS error seems unrelated -- the widget calls `PF(...)` to check if the widget exists and that just logs an error message.

What seems to be happening is that the showcase set the `autoSubmit` property on the DynaForm to `true`. ~~The client side JavaScript then submits the form. The server, when it processes that POST request, notices a CSP nonce mismatch and throws an exception. This results in an unfinished response, which probably explains the blank page.~~ The main issue seems to be that the submit is not made via AJAX anymore, see comment below.

Java logs a CSP issue:
 
```
org.primefaces.csp.CspException: CSP nonce mismatch
	at org.primefaces.csp.CspState.getNonce(CspState.java:90)
	at org.primefaces.csp.CspPhaseListener.initCsp(CspPhaseListener.java:96)
	at org.primefaces.csp.CspPhaseListener.beforePhase(CspPhaseListener.java:68)
	at org.apache.myfaces.lifecycle.PhaseListenerManager.informPhaseListenersBefore(PhaseListenerManager.java:77)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:259)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
```

### Expected behavior

Behaves as befores: It submits the form and displays the result in a dialog.

### PrimeFaces Extensions version

14.0.7

### JSF implementation

None

**Comment by blutorange** [comment]
Another difference between 14.0.6 and 14.0.7 is that previously, the POST was sent via AJAX, but now seems to be sent as a normal POST request. And the AJAX submit JS code seems to be missing from the button:

14.0.6
![image](https://github.com/user-attachments/assets/91ffc436-39d5-4475-83b7-249812c2e389)

14.0.7
![image](https://github.com/user-attachments/assets/735da34f-0e88-473f-a689-3bbd512bcfd8)

**Comment by melloware** [comment]
Yep has to be CSP related.

**Comment by melloware** [comment]
It's the only thing that really changed between these versions was enabling CSP on the showcase

**Comment by blutorange** [comment]
I think I found the issue now. Enabling CSP is definitely the reason why the onlick attribute is missing. Instead, the `CspResponseWriter` renders a JavaScript at the end of the body like `PrimeFaces.csp.register('dynaForm:search', ...)` to handle the search. The problem is though, that this happens too late.

The [DynaForm code](https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/resources/META-INF/resources/primefaces-extensions/dynaform/0-dynaform.js#L19) that checks for the `autoSubmit` attribute and submits the form is run when the widget is created, and that happens on page load before `PrimeFaces.csp.register(...)`  gets run.
