### ISSUE TITLE
Exporter: Remove from Extensions

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#205]
Wanted to float this out there to anybody watching about removal of the Extensions DataExporter.

PF DataExporter has most of the features now of this exporter and the code in PFE is both ugly and difficult to maintain.

Just wanted to get +1 votes for removal and -1 votes for leaving it in PFE.

**NOTE:**
- [x] Remove POI from pom.xml
- [x] Remove all code and showcase examples and controllers
- [x] Remove file \src\main\resources\META-INF\services\org.primefaces.extensions.component.exporter.ExporterFactory

**Comment by tandraschko** [comment]
+1 and add features to PF if required

**Comment by stolp** [comment]
I gave up on PFE Exporter early after trying it out. PF DataExporter is in a good shape.

**Comment by melloware** [comment]
thanks @stolp I think it solved problems in the early days of PF but the main PF exporter has come a long way and added features this had.  It doesn't have them all but some of them are even oddly implemented in this version.

**Comment by melloware** [comment]
I have just marked all the code as `@deprecated`

**Comment by Rapster** [comment]
I added my +1, we should list the diffs between those two. For example, as I'm having a look to ColumnGroup lately, I can say PFE exporters seems to support ColumnGroup while PF exporter does not.

**Comment by melloware** [comment]
@Rapster agreed there is this open PF ticket for years about adding ColumnGroup to Exporter: 
https://github.com/primefaces/primefaces/issues/59

The only other real useful feature I can see if the ability for Excel/PDF if a column has style="float:right" etc to right align it.  I don't like how its done in PFE exporter as its looking at HtmlOutputtext instead of the p:column style itself.

**Comment by melloware** [comment]
ColumnGroup support added in main PF now.  Ported this code over and cleaned it up.  It actually worked quite well.

**Comment by melloware** [comment]
I now think we have ported over most of the useful code from PFE exporter so I have no hesitation deleting after the next Major release.

**Comment by tandraschko** [comment]
+1

**Comment by petterlarsen** [comment]
PF DataTablePDFExporter is still using com.lowagie itext. Either PF should upgrade to another maintained lib or a new PDF exporter in PF Extension?

**Comment by stolp** [comment]
I don't think that this is needed.

[OpenPDF](https://github.com/LibrePDF/OpenPDF) is a maintained, fully compatible replacement for com.lowagie itext.

I am using this successfully for years in my PrimeFaces project for the DataTablePDFExporter.

**Comment by melloware** [comment]
Yes OpenPDF still uses the com.lowagie package space but its been forked and actively maintained for bugfixes while keeping backwards compatibility.  You can just drop this in your pom.xml and it works.

```xml
            <dependency>
                <groupId>com.github.librepdf</groupId>
                <artifactId>openpdf</artifactId>
                <version>1.3.30</version>
            </dependency>
```
