### ISSUE TITLE
documentviewer: Add possibility to select which buttons are shown

### ISSUE THREAD

**Issue by bstobbe** [primefaces-extensions/primefaces-extensions#217]
**Is your feature request related to a problem? Please describe.**
Currently the pe:documentviewer renders all possible buttons for pdf.js. Sometimes we want users to only use a subset of this buttons. It would be good to add a possibility to select which buttons are shown.

**Describe the solution you'd like**
It would be great if the <pe:documentviewer> tag gets a new attribute showButtons which can get a list of buttons that will rendered by pdf.js. E.g. <pe:documentviewer showButtons="download,print">

**Comment by melloware** [comment]
There is no JS Widget for Document Viewer however this can be accomplished easily with a JS function like this.  

**Note:** Some buttons like `presentationMode` are special and need to be hidden a little differently.

```javascript
pdfHideButtons : function() {
         var pdfViewer = window.frames[0].PDFViewerApplication;
         if (pdfViewer) {
            pdfViewer.toolbar.items.openFile.hidden = true;
            pdfViewer.toolbar.items.viewBookmark.hidden = true;
            pdfViewer.toolbar.buttons.find(el => el.eventName === 'presentationmode').element.style.display = "none";
         }
      }
```

Then on your page add this code to basically hide the buttons after the page loads.
```xml
<script>
        $(document).ready(function() {
            setTimeout(function(){ pdfHideButtons(); }, 1000);
        });
</script>
```
