### ISSUE TITLE
Sheet: Ajax event not fire when editing value with colType="numeric"

### ISSUE THREAD

**Issue by nixonyeung** [primefaces-extensions/primefaces-extensions#230]
**Describe the bug**
Sheet: Ajax change event not fire when editing value in colType="numeric" 

**Reproducer**
https://www.primefaces.org/showcase-ext/sections/sheet/ajaxEvents.jsf
1.  Double click any value in "Editiable" column,  the value changes to edit mode.
2.  Key in a new value.
3.  Click on any empty space other than pressing enter key or clicking on the sheet components .
4.  The value changes from edit mode to read-only but the ajax event is not fired.

**Expected behavior**
Behavior should be the same as other colTypes to fire the ajax change event.

**Comment by melloware** [comment]
I have confirmed your issue.  let me look into it.

**Comment by melloware** [comment]
OK it was similar to https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/599

And its fixed for 9.0. Thanks for reporting!
