### ISSUE TITLE
Orgchart : Error converting circular structure to JSON

### ISSUE THREAD

**Issue by jsolanou** [primefaces-extensions/primefaces-extensions#235]
**Version**

tested in PrimeFaces Extensions Showcase - © 2011-2020,	PrimeFaces: 8.0, PrimeFaces Extensions: 8.0.2,	JSF: jakarta 2.3.14,	Server: jetty/9.4.2.v20170220,	Build time: 2020-04-29 13:39

**Steps to reproduce**
1. Go to https://www.primefaces.org/showcase-ext/sections/orgchart/basicUsage.jsf
2. Click a node in the org chart

**Describe the bug**
Add blank grids infinitely by continuing to click on nodes.

**The stack trace**
Opening the DevTools in google chrome in the console shows the following error:

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property 'jQuery341060492224040539221' -> object with constructor 'Object'
    |     property 'events' -> object with constructor 'Object'
    |     ...
    |     property '$chartContainer' -> object with constructor 'k.fn.init'
    --- property '0' closes the circle
    at JSON.stringify (<anonymous>)
    at HTMLDivElement.<anonymous> (orgchart.js.jsf?ln=primefaces-extensions&v=8.0.2:27189)
    at HTMLDivElement.dispatch (jquery.js.jsf?ln=primefaces&v=8.0:2)
    at HTMLDivElement.v.handle (jquery.js.jsf?ln=primefaces&v=8.0:2)
(anonymous) @ orgchart.js.jsf?ln=primefaces-extensions&v=8.0.2:27189
dispatch @ jquery.js.jsf?ln=primefaces&v=8.0:2
v.handle @ jquery.js.jsf?ln=primefaces&v=8.0:2
orgchart.js.jsf?ln=primefaces-extensions&v=8.0.2:81 SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at jquery.js.jsf?ln=primefaces&v=8.0:2
    at l (jquery.js.js

![extensionchart](https://user-images.githubusercontent.com/74940614/100035918-ca8cd800-2dc4-11eb-990e-46d9885c97ce.jpg)

**Comment by melloware** [comment]
Thank you for reporting I have fixed it for 9.0!  If you need this fix right now just add this code to your application JS file that loads after PF.
```javascript
PrimeFaces.widget.ExtOrgChart.prototype.init = function (cfg) {
    PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
    this.id = cfg.id;

    // user extension to configure plugin
    var extender = this.cfg.extender;
    if (extender) {
        if (typeof extender === "function") {
            extender.call(this);
        } else {
            PrimeFaces.error("Extender value is not a javascript function!");
        }
    }

    var opts = $.extend(true, {}, cfg);
    opts['data'] = JSON.parse(opts['data']);

    this.orgchart = this.jq.orgchart(opts);

    this._bindEvents();
};

PrimeFaces.widget.ExtOrgChart.prototype._bindEvents = function () {
    var $this = this;

    this.jq.on('click', '.node', function () {
        var $thisNode = $(this);

        var options = {
            params: [{
                name: $this.id + '_nodeId',
                value: $thisNode[0].id
            }, {
                name: $this.id + '_hierarchy',
                value: JSON.stringify($this.orgchart.getHierarchy())
            }]

        };
        $this.callBehavior('click', options);
    });

    this.jq.children('.orgchart').on('nodedropped.orgchart', function (event) {
        var options = {
            params: [{
                name: $this.id + '_draggedNodeId',
                value: event.draggedNode['context']['id']
            }, {
                name: $this.id + '_droppedZoneId',
                value: event.dropZone['context']['id']
            }, {
                name: $this.id + '_hierarchy',
                value: JSON.stringify($this.orgchart.getHierarchy())
            }]

        };
        $this.callBehavior('drop', options);

    });
};
```

**Comment by jsolanou** [comment]
Thank you very much for the solution i needed it it is an important component for the development of the organization. I tried it and the solution works well, we are waiting for the version of primefaces 9 soon.

Cheers

**Comment by melloware** [comment]
Excellent thanks for reporting back!  When 9.0 comes out you should just be able to rip out that code you added above but for now it should get you through :)
