### ISSUE TITLE
Timer: Locale support

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions#253]
**Is your feature request related to a problem? Please describe.**
There is no i18n support for timer component. For `human` format, it is shown only English time words, such as `an hour`, `a few minutes` so on.

**Describe the solution you'd like**
Need to implement the solution mentioned moments documentation at https://momentjs.com/docs/#/i18n/

**Comment by melloware** [comment]
Yep this should be doable no problem.
