### ISSUE TITLE
FAB: Support PF Badge

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#257]
**Is your feature request related to a problem? Please describe.**
@jepsar since PE Badge works with FAB we should make it work with the new PrimeFaces Badge as that would be the only functionality lost if we deprecated and removed PE Badge.

**Comment by melloware** [comment]
If this is too much of a pain, we should just add a badge attribute to the FAB so it can render it.

**Comment by jepsar** [comment]
Haven't played with the new badge yet. Will give it a look this evening.
