### ISSUE TITLE
Showcase based on the one used with PF

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#264]

**Comment by melloware** [comment]
I think we should wait until they are all done making changes.  It will be a large undertaking to convert ours to theirs.

**Comment by jepsar** [comment]
I agree.. this will be a huge time drain

**Comment by melloware** [comment]
Closing for now.  PrimeTek has mentioned redoing their showcase again and right now we have no capacity for this undertaking.
