### ISSUE TITLE
TimePicker: should respect theme colors

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#273]
<img width="401" alt="Screen Shot 2021-01-23 at 16 36 52" src="https://user-images.githubusercontent.com/7500178/105606397-6624cf80-5d99-11eb-8b32-348991a9a64f.png">

**Comment by melloware** [comment]
I fixed it looks much better now!
![image](https://user-images.githubusercontent.com/4399574/105609471-922f5900-5d77-11eb-876c-eb3ae05f0102.png)

**Comment by jepsar** [comment]
I wanted to get this more in line with the date picker.

**Comment by melloware** [comment]
OK but dont remove the border boxes.  It looks too naked like that and I use this component a lot and my production users have complained they like seeing the border boxes.

**Comment by melloware** [comment]
I also just checked in fixes to fix the logo in the upper left to be SVG so it also adjusts properly with the theme.  The old one was a PNG that was not transparent.

**Comment by jepsar** [comment]
> OK but dont remove the border boxes. It looks too naked like that and I use this component a lot and my production users have complained they like seeing the border boxes.

Well, the date picker also does not have borders arround each date. This is somethime you could easily add to a custom style sheet... if you don't mind.

<img width="460" alt="Screen Shot 2021-01-23 at 19 52 16" src="https://user-images.githubusercontent.com/7500178/105611300-b8271e80-5db4-11eb-93ee-c7be7c017955.png">

**Comment by melloware** [comment]
OK I guess that doesn't look that bad.  I can always add the borders back if my users complain...

**Comment by jepsar** [comment]
> OK I guess that doesn't look that bad. I can always add the borders back if my users complain...

The extra padding does a lot
