### ISSUE TITLE
Calculator: should respect theme colors

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#282]
<img width="578" alt="Screen Shot 2021-01-24 at 15 56 10" src="https://user-images.githubusercontent.com/7500178/105634098-c597e380-5e5c-11eb-9c0c-125428c24555.png">

**Comment by melloware** [comment]
Not perfect but much better.

![image](https://user-images.githubusercontent.com/4399574/105637892-d9801d00-5e3d-11eb-9529-a087148440fb.png)
