### ISSUE TITLE
New Component: TimeClockPicker

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#283]
<img width="358" alt="Screen Shot 2021-01-24 at 16 00 39" src="https://user-images.githubusercontent.com/7500178/105634258-7605e780-5e5d-11eb-90ce-2547dac6fcc1.png">

**Comment by melloware** [comment]
I used some tricks we use in PF Core for Calendar DatePicker and others that have similar overlays.  Reset CSS to 0.0 and call `flipfit` doesn the trick to make it detect where the window edges are.

**Comment by jepsar** [comment]
I'm not seeing any difference

**Comment by melloware** [comment]
When you say be adaptive what do you mean?  

Maybe I think it means something different.

**Comment by jepsar** [comment]
I would like to prevent horizontal scrolling somehow.

**Comment by melloware** [comment]
Oh you mean if the browser is that small preventing it from flowing off the screen? 

Does the DatePicker do that?  If it does we should look how it does it.

**Comment by jepsar** [comment]
The date picker does not flow off the screen.. so we need to come up with a custom solution.

**Comment by melloware** [comment]
Yep I bet the old Jquery Calendar DOES flow off screen though right?

**Comment by melloware** [comment]
I have a feeling this is not an insignificant hacking of the TimePicker JQ component to get it to be responsive.

**Comment by jepsar** [comment]
Yeah, I think this will not be a quick fix.

**Comment by jepsar** [comment]
I think we can offer [this time picker](https://github.com/loebi-ch/jquery-clock-timepicker/) as an alternative component. It's just so much more intuitive (at least for me it is).

A big con (for the US) could be that it does not support AM / PM. It's an open issue though.

**Comment by melloware** [comment]
I think we should call it `InputTime` and I like this idea a lot.  We could also do `InputColor` which if you have seen the html5 color picker is is very nice and intuitive!

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by jepsar** [comment]
> I think we should call it `InputTime` and I like this idea a lot.

You are talking about html5 here, and not about https://github.com/loebi-ch/jquery-clock-timepicker/ , right?

**Comment by melloware** [comment]
Oh i did not even notice you posted that!   That one does look pretty sharp!  What would you call it `ClockPicker`?

**Comment by melloware** [comment]
This one looks like it is meant to be mobile and responsive too which is a plus.

**Comment by jepsar** [comment]
> What would you call it `ClockPicker`?

Either that or `TimePicker360` or `TimePickerClock`

**Comment by melloware** [comment]
Maybe `TimeClockPicker`

**Comment by jepsar** [comment]
https://github.com/ShaneGH/analogue-time-picker
