### ISSUE TITLE
CommandSingleClickRenderer: Support new ConfirmPopup

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#289]
**Is your feature request related to a problem? Please describe.**
We currently support ignoring ConfirmDialog buttons this extends it to support the new ConfirmPopup component.

**Comment by melloware** [comment]
@jepsar please review.  The new confirm popup buttons are `ui-confirm-popup-yes` for example and confirm dialog is `ui-confirmdialog-yes` so this makes it generic to just look for ui-confirm

**Comment by jepsar** [comment]
@melloware good catch. Fix looks good to me.

I was just talking with a co-worker whether to replace the confirm dialog with a popup :-)

**Comment by melloware** [comment]
HA yeah I REALLY like the confirm popup it seems so much less annoying than a whole dialog!
