### ISSUE TITLE
OmniFaces CombinedResourceHandler PF Convenience Classes

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#293]
We heavily use the `Omnifaces CombinedResourceHandler` to combine our CSS and JS to just 1 script each in our PrimeFaces apps.

See: https://showcase.omnifaces.org/resourcehandlers/CombinedResourceHandler

However PrimeFaces hard codes some resources in the HeadRenderer which leave it outside the scope of being combined like the theme.css, beanvalidation.js etc etc.  

Of course @BalusC has an excellent solution provided on his WIKI here: https://github.com/omnifaces/omnifaces/wiki/Combine-hardcoded-PrimeFaces-resources-using-CombinedResourceHandler

So rather than make people copy and paste and change with every PF version I thought I would include the classes here for PrimeFaces Extensions starting with 10.0.

**faces-config.xml**
```xml
<application>
    <system-event-listener>
        <system-event-listener-class>org.primefaces.extensions.application.PrimeFacesScriptProcessor</system-event-listener-class>
        <system-event-class>javax.faces.event.PostAddToViewEvent</system-event-class>
        <source-class>javax.faces.component.UIViewRoot</source-class>
     </system-event-listener>
</application>

<lifecycle>
    <phase-listener>org.primefaces.extensions.application.PrimeFacesResourceProcessor</phase-listener>
</lifecycle>
```
Don't forget to disable PF's HeadRenderer:
```xml
<render-kit>
    <renderer>
        <component-family>javax.faces.Output</component-family>
        <renderer-type>javax.faces.Head</renderer-type>
        <renderer-class>com.sun.faces.renderkit.html_basic.HeadRenderer</renderer-class>
    </renderer>
</render-kit>
```
In case you're using MyFaces, use `org.apache.myfaces.renderkit.html.HtmlHeadRenderer` as <renderer-class>.

**Comment by melloware** [comment]
OK this is checked in and I tested it locally and its working great.

**Comment by melloware** [comment]
Just a word of warning I have found one issue in my testing and that is with CKEditor because of the way it dynamically loads scripts.  The URL's all look wrong and get 404's.  Need to investigate.

**Comment by stolp** [comment]
Tested this (without CKEditor) and it is working flawlessly in my application. Thanks a lot!

**Comment by melloware** [comment]
Nice!  I was able to fix CKEditor as well!

**Comment by jepsar** [comment]
There is no page for this feature in the showcase, right?

**Comment by melloware** [comment]
No there is not. I should make one. I will open a ticket.

**Comment by melloware** [comment]
Showcase page added with this commit: https://github.com/primefaces-extensions/primefaces-extensions/commit/abccb3f85d322166f62396e68e15b89dec426e5c
