### ISSUE TITLE
Sheet: dark mode selected cell header and footer background are too light

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#302]
<img width="276" alt="Screen Shot 2021-02-01 at 19 50 17" src="https://user-images.githubusercontent.com/7500178/106504273-fdd79b80-64c6-11eb-821a-1de67272b74f.png">

Rule: `.handsontable thead th.ht__highlight`

**Comment by melloware** [comment]
![image](https://user-images.githubusercontent.com/4399574/106506918-5b082880-6498-11eb-93ee-c33474c2422e.png)

I now use primary color and primary text color.
