### ISSUE TITLE
New component: Monaco editor

### ISSUE THREAD

**Issue by blutorange** [primefaces-extensions/primefaces-extensions#305]
The [Monaco Editor](https://microsoft.github.io/monaco-editor/index.html) is the code editor which powers VS Code, with the features better described here.

Two years, ago I started making a JSF wrapper for the monaco editor (https://github.com/blutorange/primefaces-monaco) so we could use it in our JSF pages. It's already implemented as a PrimeFaces widget. By now the wrapper component works well enough that I was wondering if we could add it to PrimeFaces extensions ? I would need to make some adjustments, but it should not be too hard.

* Allows a language / locale to be specified.
* There's an inline version and an iframe version. The iframe version is useful when you want to use a different language service configuration.
* There's an extender that lets you setup the monaco editor via custom script.
* The github project includes a demo JSF application that I also use for testing, see https://github.com/blutorange/primefaces-monaco#demo if you want to try it out.

**Comment by melloware** [comment]
@blutorange I love this idea and would be happy to review your PR and merge it here in Extensions. It would be a great addition.  I did the same thing with Sheet I wrote it for a client and since I put it here people have offered great feedback and improvements making it way more advanced than what I had written for my client.

**Comment by melloware** [comment]
Even better Monaco is MIT Licensed so it doesn't have to be a separate JAR like CKEditor is it can be right in the core jar!

**Comment by blutorange** [comment]
I'm glad you like the idea : ) I'll take a look and see if I can integrate it into extensions. A few quick questions:

* Currently I use the `frontend-maven-plugin` to fetch monaco editor from NPM and create the final build files. For CKEditor, it seems all the source files are in this repository and it doesn't download anything from NPM. Should I include all necessary source files for monaco editor as well or is it ok to fetch the resources from NPM during build time?
* Also, since there are some build scripts etc, I think it would be a good idea to make it a maven submodule?

**Comment by melloware** [comment]
OK feel free to make it a submodule if it makes building it easier for you. I like the idea of the NPM build etc.  The CKEditor build has always been a static download build.  i grab the files from the CKEditor site and copy them in whenever we upgrade.

**Comment by blutorange** [comment]
I now ported the code and it's working already. I need to add more examples, test all features, and do some general cleanup. There's two examples in the showcase if anybody want to check it out and share their opinion (see https://github.com/blutorange/core/tree/feature-305). Would also be nice to know if the build and the component works for other people.

* I created a maven submodule `monacoeditor` for the webpack build that creates the monaco editor resources. The webpack build can take around 30 - 60 seconds. Most of the time monaco you build, monaco resources are not updated, so this makes it easier to reduce build times by not building that maven project.
* The control code for the widget itself is inside the `core` maven project and compressed with closure compiler like all the other widgets.
 
![image](https://user-images.githubusercontent.com/2456413/108601324-4c78a700-739c-11eb-8cb6-9a5ce2ac81cc.png)

**Comment by melloware** [comment]
This looks really good!   A couple of things that are pseudo code review comments.
- uiLanguageUri should probably be `locale` and use all the built in local tricks we have in other compoennts and it also can respect the JSF view language etc for determining the language.  And then we have `LocaleUtils.getjavaScriptLocale` if your locale uses dashes instead of underscores etc. This would put it more in line with other PF components.
- Have you tried with CSP=true in the web.xml?  Just interested if Monaco supports CSP.

**Comment by blutorange** [comment]
Thanks for taking a look : )

* I already added a few tricks that make it possible to use a custom locale from any given source. I can adjust it so that it reads from `PrimeFacesExt.locales.MonacoEditor` ? Locale codes are freely changeable, so we can just use underscores if that's better. And yes, I can rename the option and use the view language.  Are there any more locale tricks I should be aware of? 
* Regarding CSP, I turned it on and I had to pass the nonce in one place where it was missing. Otherwise it seems to be working now, for both the inline and framed version. I"ll just leave it on while I create more showcase examples, so I"ll notice if something won't work.

**Comment by melloware** [comment]
Well if you look at how the Calculator/CalculatorRenderer component in PFE does `locale` that might give you some more direction.

**Comment by melloware** [comment]
Nice work updating for locale!  Now if someone has a global locale set your component will just pick it up and use it.

**Comment by melloware** [comment]
Whenever you think you are ready to submit PR I can make sure it gets in RC2 of PFE.

**Comment by blutorange** [comment]
Thanks : ) I'd like to do a little bit more of testing and check that all features work. Other than that, what's the estimated date for RC2 or rather, when would this need to be ready to make it into RC2?

**Comment by melloware** [comment]
So I usually cut RC2 a few hours after PF Core releases RC2 in Maven Central.  I think PrimeTek is planning on doing it early this week maybe Monday or Tuesday.   You will still have between RC2 and Final 10.0.0 to polish this component as well.

**Comment by melloware** [comment]
This component is pretty awesome.  Its so much nicer than CodeMirror.  I just wish there was a FreeMarker template language for Monaco since that is what I use it for in production.  I know I could write mine own for Monaco just don't have that time to invest right now!

**Comment by blutorange** [comment]
Yeah, I know, it's essentially VSCode light with lots of nice features and quite customizable with enough time. Though it's got a much heavier footprint, and code mirror provides a nice light-weight alternative, so having both component lets people choose what fits their use case.

**Comment by melloware** [comment]
I also can't figure out when I build why Maven Reactor thinks it needs to build Monaco before the Core? 
```
[INFO] Reactor Summary for PrimeFaces Extensions Parent 10.0.0-SNAPSHOT:
[INFO]
[INFO] PrimeFaces Extensions Parent ....................... SUCCESS [  1.609 s]
[INFO] PrimeFaces Extensions Resources MonacoEditor ....... SUCCESS [ 54.365 s]
[INFO] PrimeFaces Extensions .............................. SUCCESS [ 13.527 s]
[INFO] PrimeFaces Extensions Resources CKEditor ........... SUCCESS [  2.808 s]
[INFO] PrimeFaces Extensions Showcase ..................... SUCCESS [  8.698 s]
```

**Comment by blutorange** [comment]
That is intentional: core has a dependency on Monaco. Try searching for the class "EditorOptions". This is a a wrapper for the https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html and sent as JSON to the client.

The "EditorOptions" class is generated automatically from the file https://github.com/primefaces-extensions/primefaces-extensions/blob/master/monacoeditor/src/main/js/descriptor/create.js 

There I only have to maintain the property name and the type, which is much easier to maintain than a Java class that is 4-5 times as large with the field name and getters and setters.

**Comment by melloware** [comment]
Ahh I need to change that scope to provided.  We can't force anyone using Core to have to bring in the Monaco Resources.  So it can compile with this but we don't want to force people that have to have this JAR like we don't with the others.

**Comment by melloware** [comment]
I also updated the READMD.MD to have the Monaco Resources like we do with CKEditor.

**Comment by melloware** [comment]
Actually I am gong to update to `<optional>true</optional>`

**Comment by blutorange** [comment]
Ok, I didn't know that. So that means people who wish to use monaco editor should add resources-monacoeditor as an additional dependency to primefaces-extensions. I guess that should workl

**Comment by melloware** [comment]
Yep that is how CKEditor is only if you want to use that component you need the extra dependency so your WAR isn't 4MB bigger for no reason if you are not using the component.

**Comment by melloware** [comment]
Sorry one last thing.  If you look at CodeMirror it extends `AbstractPrimeHtmlInputTextArea` which adds a bunch of new HTML5 DOM events like `oninput`. You didn't want to extend that?

**Comment by blutorange** [comment]
Pretty sure I didn't think of it when I originally made the component. When I take a look at `AbstractPrimeHtmlInputTextArea`, it does have a few events / methods such as `oncut` / `oncontextmenu` etc. I'm not sure we can provide (since the textarea is just a hidden dummy for transferring data). If that's no problem, I see no reason not to use it.

**Comment by melloware** [comment]
Oh OK.  Well yeah if you have specifically what works then no need to inherit it.

**Comment by melloware** [comment]
Showcase is now up if you want to check it out: https://www.primefaces.org/showcase-ext/views/monacoEditor.jsf

**Comment by blutorange** [comment]
Awesome, so RC2 is available now. Looks great to it in action : )

**Comment by melloware** [comment]
Yep RC2 is in Maven Central for both PF and PFE.
