### ISSUE TITLE
Bundle and automatically load client side locale Javascripts

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#310]
See https://github.com/primefaces/primefaces/wiki/Locales#client-localization

**Comment by melloware** [comment]
+1

**Comment by tandraschko** [comment]
@melloware please ask PrimeTek to bundle it directly in PF core.
We can add a context param to add this File dynamically

**Comment by jepsar** [comment]
Even better :-)

**Comment by melloware** [comment]
Oh I love that Idea.  I assumed they didn't do it for a reason :)
