### ISSUE TITLE
Counter: Internationalization Support

### ISSUE THREAD

**Issue by willbigas** [primefaces-extensions/primefaces-extensions#320]
**Is your feature request related to a problem? Please describe.**
In the **Counter** component today, I can't dynamically display the user's decimal and currency formats, using their location, I don't have internationalization support, just fixed CurrencyFormat parameters, Decimal places and thousands.

**Describe the solution you'd like**
Using the same logic as convertNumber, allow the component to assign a locale parameter and it will dynamically assume the currency format and decimal places based on the parameter.
Something like `<pe:counter locale="BackingBeanLocaleHere()" </pe:counter>`

**Additional context**
Today I use the counter to display financial results in my system, but I need internationalization support, if I will not have
to find another long-term solution, since the United States user does not work with the same currency format as the Brazilian user.

**Comment by melloware** [comment]
I am investigating

**Comment by melloware** [comment]
@willbigas for now you can use the separator and decimal for your Locale right if you don't want the defaults?

```xml
<pe:counter end="9000" separator="." decimals="2" decimal=","/>
```

separator | Grouping separator. Default is ','.
-- | --
decimal | Decimal seperator. Default is '.'.

**Comment by willbigas** [comment]
@melloware Yes, I already use it, but I think that if I wanted to try a kind of internationalization just using this, I will have to check in the code which locale is the current one and put the symbol and decimal places accordingly, something in my opinion kind of bad , what you think? the most elegant way would be to have the locale behavior that I mentioned.

**Comment by melloware** [comment]
Agreed I just added so you can use `locale` and it will auto detect your locale if you leave locale blank and use your current locale's default like other PF components do! Thanks for the suggestion!

**Comment by melloware** [comment]
10.0.0.RC2 is now in Maven Central and has this new feature if you want to try it out
