### ISSUE TITLE
Lightswitch: Not working with CombinedResourceHandler

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#324]
**Describe the bug**
Because there is no ThemeLink when using the Omnifaces/PFE CombinedResourcehandler there is no link to change.

In this case we must reload the window for it to pick up the theme change.

**Comment by melloware** [comment]
@jepsar please review.

**Comment by jepsar** [comment]
> @jepsar please review.

https://github.com/primefaces-extensions/primefaces-extensions/commit/4b2bafba6100f867d95b35173f6bcdf289fdde7d#r47741143

**Comment by melloware** [comment]
OK how does this look? https://github.com/primefaces-extensions/primefaces-extensions/commit/e30cef3babd1180596f64a766596668f4b183345

**Comment by melloware** [comment]
OK now I think I have it all working! see: https://github.com/primefaces-extensions/primefaces-extensions/commit/6d2b488b0c8c7ba51b2a26e00e5ac1db4d7d9019
