### ISSUE TITLE
CKEditor: Add placeholder attribute

### ISSUE THREAD

**Issue by phillipross** [primefaces-extensions/primefaces-extensions#325]
This is a feature request for support of html placeholder in the CKEditor component.

For reference, the [p:texteditor](https://primefaces.github.io/primefaces/8_0/#/components/texteditor) in primefaces supports a `placeholder` attribute which populates the html placeholder attribute of the rendered html input.  It would be great if the CKEditor component did the same thing.

CKEditor apparently supports this via a plugin:
https://ckeditor.com/docs/ckeditor4/latest/features/editorplaceholder.html

**NOTE:** there appears to be a separate notion of a "placeholder" within CKEditor:
https://ckeditor.com/docs/ckeditor4/latest/examples/placeholder.html
This feature request refers to the "editor placeholder" rather than this.

**Comment by melloware** [comment]
fixed it will make it in the 10.0.0 final release.
