### ISSUE TITLE
CommandSingleClickRenderer: Duplicate onClick events

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#327]
**Describe the bug**
Go to this page: https://www.primefaces.org/showcase-ext/sections/inputphone/basicUsage.jsf

Right click and do view source. You will see duplicate `onClick` events registered for the same component.

Found it using W3C validator...

![image](https://user-images.githubusercontent.com/4399574/110217029-e69e1c00-7e7f-11eb-80a3-54b84caa4846.png)

**Environment:**
 - PF Version: _10.0_
 - JSF + version:  MyFaces 2.3.8
 - Affected browsers: ALL

**Comment by jepsar** [comment]
Isn't this a bug in PrimeFaces? It looks like the onclick is rendered again here:

https://github.com/primefaces/primefaces/blob/ad61861b8db7601c5979d72dc545cb979a387fbc/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java#L98

or, am I missing something?

**Comment by melloware** [comment]
Yep I think you are right. Let me investigate.

**Comment by melloware** [comment]
Reported: https://github.com/primefaces/primefaces/issues/7078

**Comment by melloware** [comment]
What's weird is its registering 3 onClick's...

```xml
<button id="j_id_z" name="j_id_z" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" aria-label="" 
onclick="PrimeFaces.bcn(this,event,[function(event){var w=PrimeFaces.widgets['widget_j_id_z'];if(w){w.disable();};},function(event){PrimeFaces.ab({s:&quot;j_id_z&quot;,f:&quot;mainForm&quot;,u:&quot;txtPhone&quot;,onco:function(xhr,status,args,data){var w=PrimeFaces.widgets['widget_j_id_z'];if(w){w.enable();};;}});return false;}]);" type="submit" 
onclick="var w=PrimeFaces.widgets['widget_j_id_z'];if(w){w.disable();};" 
onclick="var w=PrimeFaces.widgets['widget_j_id_z'];if(w){w.disable();};">
	<span class="ui-button-text ui-c">Submit</span>
</button>
```

**Comment by melloware** [comment]
Even with this PR: https://github.com/primefaces/primefaces/pull/7080

Now this example is registering 2 onclick's instead of 3. So it has eliminated one of them.

**Comment by jepsar** [comment]
I don't get how this renderer could cause this. It's not writing anything.

**Comment by melloware** [comment]
I am kinda stumped myself. I have to dig deeper into this.

**Comment by melloware** [comment]
found the last onclick: https://github.com/primefaces/primefaces/pull/7091
