### ISSUE TITLE
clipboard not work

### ISSUE THREAD

**Issue by tyrone1987** [primefaces-extensions/primefaces-extensions#337]
Hello. I'm using the latest versions of primefaces and when I enabled the security option primefaces.CSP it stopped working <p: ajax event = "success" listener = "# {bean.successListener}" />.
the option to copy if it works but not the listener.

**Comment by melloware** [comment]
I will investigate. Thanks for reporting.

**Comment by tyrone1987** [comment]
Hi, try onclick = "return false;", and it worked.
I'm sorry I wasted your time
