### ISSUE TITLE
Core: JS  changeTheme does not work with combined resource handler

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#338]

**Comment by melloware** [comment]
I was debugging this last night.  It works locally but when running on Jetty Server in Production it looks like when we create the HTML HEAD CSS file for Theme Link its not actually overridding the theme found in the combined CSS for some reason.

**Comment by jepsar** [comment]
> I was debugging this last night. It works locally but when running on Jetty Server in Production it looks like when we create the HTML HEAD CSS file for Theme Link its not actually overridding the theme found in the combined CSS for some reason.

Yes, that's exactly the reason. The combined theme is loaded later, so it will always override the one in the head. Append to the body and it is fixed.
