### ISSUE TITLE
Orgchart - show case exception

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions#346]
@melloware Please take a look as well and see if you can replicate the bug. This behavior has not been presented in the live showcase yet. 

Build the showcase, choose orgchart, and click basicUsage:

or go to http://localhost:8080/showcase-ext/sections/orgchart/basicUsage.jsf directly

![image](https://user-images.githubusercontent.com/10467831/112251053-8271ab00-8c28-11eb-85bc-f437fa0969ff.png)

I will send a PR for review, but I wonder why there's no exception prevoiusly 🤔?

**Comment by melloware** [comment]
Ahhh this doesn't show up on the Showcase because it runs in JSF Production Mode but when running locally it is in Development Mode and shows these kinds of errors. Thanks for the fix!

**Comment by jxmai** [comment]
I see. Makes sense!
