### ISSUE TITLE
CodeScanner: How to set the device Id for rear facing camera?

### ISSUE THREAD

**Issue by anuragnz** [primefaces-extensions/primefaces-extensions#350]
How to set the device Id for rear facing camera? I mean how do we know the device id for rear facing camera in Android or iPhone?

**Comment by jepsar** [comment]
This has been fixed with https://github.com/primefaces-extensions/primefaces-extensions/pull/334 which will be available in 10.0.1

**Comment by jepsar** [comment]
For now you can find the device you want to use and pass it to the component using the `deviceId` attribute.
