### ISSUE TITLE
MonacoEditor: Console error when used twice in seperate tabs

### ISSUE THREAD

**Issue by stolp** [primefaces-extensions/primefaces-extensions#372]
**Describe the bug**
My Page consists of a TabView with several tabs. Two of them each contain one MonacoEditor.
When switching tabs from one editor to the other, the following error is thrown in the console. This goes away after reloading via F5.

```
VM6290:5 Element already has context attribute: ui-monaco-editor-ed
C @ VM6290:5
createScoped @ VM6290:5
e @ VM6290:5
L @ VM6290:5
R @ VM6290:5
(anonymous) @ VM6290:5
W @ VM6290:5
U @ VM6290:5
a._doRender @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:711
a._render @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:710
render @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:464
(anonymous) @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:464
invokeDeferredRenders @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:458
postTabShow @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:539
show @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:539
select @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:539
(anonymous) @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:539
dispatch @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:68
v.handle @ eNp9j9EOwjAIRb9o8r6_qS3bWFuopc1c4scbnXGmOl-4N3DIBZgVBrFVT7PeUqaIg7Go_XypmFfY5N-sS6GOxO2-lYxfrZiEkUvLDhSwpiDGwW4bRm2WEJJhDPDhG2qS4nGFTZpZkWoneFZdKDXXdXgtyErC2v_sHuPnINZXgpc2scSplmjUw9s1hDMFE1mPGXZ7HBeFjRV0VCTDQm7E0hEH4sdHdxLLuWI.js.seam?ln=omnifaces.combined&v=1615471860000:68
```

**Reproducer**
Will work on this later. The combined resources handler currently makes it quite unreadable, sorry.

**Environment:**
 - PF Version: _10.0.0_
 - JSF + version:Mojarra 2.3.14_
 - Affected browsers: _ALL_

**To Reproduce**

will follow up

**Expected behavior**
No console error should appear.

**Comment by melloware** [comment]
CC @blutorange

**Comment by blutorange** [comment]
Multiple monaco editors in the same page should definitely work, I've been doing that. I'll be taking a look during the weekend, if I can reproduce this. @stolp I'll try if I can reproduce, if not you can work on a reproducer.

**Comment by blutorange** [comment]
Alright I can reproduce. Seems to be related to an additional render call due to it being a deferred widget. I'll take a closer look tomorrow.

**Comment by blutorange** [comment]
@stolp  Hmm it seems it was pretty late yesterday -- I gave both monaco editors the same `widgetVar`. This caused one editor to be rendered twice, resulting in this error. Could you check whether that's the case for you? With different widget vars I can't get the error to occur anymore, I tried several variations with `dynamic` and `cache` attributes on the tab view. Are your tabs inside a dialog or another dynamic container? Otherwise it would help if you could try making a reproducer with https://github.com/primefaces/primefaces-test.git
'

**Comment by stolp** [comment]
@blutorange I gave distict widgetVars to the two instances, the tabs are not in a dynamic container, *but* inside a ui:fragment. May this is the cause here?

I will try to build a reproducer in the evening, weather is too nice today :-)

**Comment by blutorange** [comment]
Take your time, the weather is nice here too : ) Won't be back till evening either. But yes, if you use ui:fragment for conditional rendering, that could be it.

**Comment by melloware** [comment]
I think you guys are both in Germany right?  So you may be having the same weather 😄

**Comment by stolp** [comment]
I have a reproducer ready, but can not yet get the behavior described from it.

The different widgetVars are hardcoded so I can not imagine this as a cause. I also played wit the tab attributes to no avail.

I plan to reuse the reproducer to demonstrate a layout problem I discovered tomorrow as a separate problem. 

Germany is not *so* small. I think its roughly 500km to @blutorange (west to east).

**Comment by melloware** [comment]
Just checking in on this issue? Any update?

**Comment by blutorange** [comment]
Doesn't seem to be reproducible, but from what I've seen, the error message is logged by the monaco editor when the editor is rendered again when it was already rendered. I'll take a general look if I can spot something. @stolp  Was the editor still usable when the error was logged?

**Comment by stolp** [comment]
Yes, the editor was fully usable. I did not yet have a reproducer ready.

**Comment by stolp** [comment]
For what it is worth, I added my reproducer here: https://github.com/stolp/primefaces-test/tree/PFE-372

It does not show the described behavior but resembles the conditions I have in my application.

@blurorange: A non related question: When adding deliberate content to the editors I find size of the scrollbars odd. 
I seems to me, that the calculation is against the initially displayed content size, not the overall content size. Sorry for my incompetent wording, but I think you can see this right away. Or am I missing something here?

**Comment by blutorange** [comment]
Thanks for the reproducer, I'll see if I can do anything to prevent the error message.

Do you mean when you set an intial value for the editor via the bean? The scrollbars look fine to me, perhaps what surprises you is that the editor can scroll past the last line as in the screenshot below? If so, that can be turned off via https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#scrollbeyondlastline

Or if the editor has the wrong size, you can add `autoResize=true` to have the editor resize automatically when the browser supports ResizeObserver. Otherwise you can call `PF("widgetVar").layout()` to manually refresh the editor.

![image](https://user-images.githubusercontent.com/2456413/116357737-1cff7400-a7fd-11eb-9ead-52a71bbf518e.png)

**Comment by stolp** [comment]
@blutorange : Thank you, scrollbeyondlastline indeed solved this issue.

**Comment by blutorange** [comment]
So that error message is logged by Monaco editor when you try to create a new editor widget on an element that already has an editor. There are refresh/destroy listeners that should dispose the editor before reload.
  
One way I managed to get the error message is by having 2+ editors on the page, having them rendered when a checkbox is checked, and (very) quickly clicking that checkbox. Though it only happens when I force an editor reload, such as by changing the UI language each time.

I'll at least take a look at that and add a fix for that. Considering it's just a log message that doesn't prevent the editor from working, I think we can call it done after that.

**Comment by melloware** [comment]
@blutorange You probably want to override the `destroy` and `refresh` listeners in the widget to dispose of the current editor.

**Comment by blutorange** [comment]
In a few hours I've got time to look at it, so I think we should be ready for a release by tomorrow.   @melloware  I'm already using addDestroyListener / addRefreshListener, but perhaps I'll just override the method

**Comment by blutorange** [comment]
After a bit more experimentation, I now finally figured out how to reproduce this -- it happens when the editor is in a not-yet visible tab (or dialog etc.) and gets updated via an AJAX call. When you then go to the tab or open the dialog, it tries to render the editor twice. Will push a fix soon

**Comment by blutorange** [comment]
@melloware So the main fix here was adding `PrimeFaces.removeDeferredRenders(this.id);` to the `refresh` method. The `DeferredWidget` only calls it during `destroy`, not during `refresh`. Seeing that `init` is called during refresh immediately after, which usually calls `renderDeferred`, that makes me wonder whether we should `PrimeFaces.removeDeferredRenders` to the PrimeFaces `DeferredWidget.refresh` method as well.

**Comment by melloware** [comment]
The deferred renderer question is for @tandraschko
