### ISSUE TITLE
ThemeAccentColorResourceHandler: uses response instead of request character encoding

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#386]
As a result, in combination with the combined resource handler, the Prime Icons are not displayed correctly.

**Comment by jepsar** [comment]
When I remove the `CharacterEncodingFilter` from the `web.xml`, the icons are working.

```xml
    <!-- UTF-8 Encoding filter over the default ISO-8859-1. -->
    <filter>
        <filter-name>CharacterEncodingFilter</filter-name>
        <filter-class>org.omnifaces.filter.CharacterEncodingFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>CharacterEncodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```

**Comment by melloware** [comment]
That is bad. That is the right character filter. I wonder if this error has popped up again in their packaged CSS.

https://github.com/primefaces/primefaces/issues/4958

**Comment by jepsar** [comment]
Hmm.. I think I was fooled by cache.. it broke as soon as I reloaded. Looking further.

**Comment by jepsar** [comment]
Okay, it worked when I removed the `ThemeAccentColorResourceHandler`. PR fixed the issue for me locally using
```xml
    <context-param>
        <param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_DISABLED</param-name>
        <param-value>false</param-value>
    </context-param>
```
