### ISSUE TITLE
TimePicker: Spinner won't stop when right- and leftclicked

### ISSUE THREAD

**Issue by straubev** [primefaces-extensions/primefaces-extensions#423]
**Describe the bug**
The time won't stop increasing / decreasing when a spinner button is both left- and rightclicked. It's only "fixed" by reloading the page. By repeating the steps, it always gets twice as fast.

**Environment:**
 - PF Version: 10.0.0 (known since 6.2)
 - PF Ext Version: 10.0.1 (known since 6.2)
 - Affected browsers: ALL

**To Reproduce**
1. Go to showcase https://www.primefaces.org/showcase-ext/sections/timePicker/basicUsage.jsf
2. Click and **hold** one of the spinner buttons with the left mousekey
3. Click the same button with the right mousekey while still pressing the left key

**Expected behavior**
The time stops increasing / decreasing once the left key is released. The right click has no effect on the time at all

**Comment by jepsar** [comment]
@melloware I could reproduce right clicking (without left click). I cannot reproduce the left + right click scenario due to my hardware. I could have a look, but can't fully test it.

**Comment by melloware** [comment]
OK let me look.    We should only respect left click and ignore right clicks at the very least.
