### ISSUE TITLE
CKEditor: wrong default value for shiftEnterMode

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces-extensions/primefaces-extensions#441]
**Describe the bug**
With https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/779 the enterMode and shiftEnterMode attributes have been introduced.
The ckeditor default for shiftEnterMode is CKEDITOR.ENTER_BR.
Primefaces Extension uses CKEDITOR.ENTER_P as default for shiftEnterMode.
Primefaces Extension should not change the default settings of the ckeditor.

**Comment by melloware** [comment]
I think I originally defaulted to "P" to make it consistent with existing behavior.  I can definitely change it.

**Comment by OBreidenbach** [comment]
Defaults in ckeditor are:
enterMode = CKEDITOR.ENTER_P
shiftEnterMode = CKEDITOR.ENTER_BR
See:
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-enterMode
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-shiftEnterMode

**Comment by melloware** [comment]
Perfect.  Updating now for 10.0.2

**Comment by OBreidenbach** [comment]
Is there already a release date planed for 10.0.2?

**Comment by melloware** [comment]
Nope I can make one whenever we want.   Would you prefer one today?

**Comment by OBreidenbach** [comment]
That would be great. Then I can use it right away and does not have to fix the bug in our code.

**Comment by melloware** [comment]
OK let me do some testing today and I will push a Maven Central 10.0.2 today.

**Comment by melloware** [comment]
OK it looks like 10.0.2 is in Central!

**Comment by melloware** [comment]
Attachment for Forum Post:
https://forum.primefaces.org/viewtopic.php?f=14&t=68174

Attachment:
[pfe-ckeditor.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/6938369/pfe-ckeditor.zip)
