### ISSUE TITLE
Showcase: Orgchart - font awesome icon does not appear on hover

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions#451]
This issue would be more like a discussion.

In the showcase, https://www.primefaces.org/showcase-ext/sections/orgchart/basicUsage.jsf

If we hover on the node, there's no green arrow icon to indicate which node can be collapsed / expanded. This looks like a broken component from the UI perspective. I think part of the reason is that we removed the font awesome support from https://github.com/primefaces/primefaces/pull/7110/files which is where the dependency is relied on. The question is that how we are going to fix this rendering issue on the showcase side? (if we are not allowed to add font awesome lib in pf-extension)

**Comment by melloware** [comment]
What we have done for other PF components is add CSS to allow for use of PrimeIcons which is now built into PF 10.0. @jepsar and I have done that for TimePicker already for example.  Let me look and see if we can fix OrgChart.

**Comment by melloware** [comment]
I see what you mean the orgchart lib itself is hardcoded for FA like...

```javascript
.children('.title').prepend('<i class="fa '+ opts.parentNodeSymbol + ' symbol"></i>');
```

So what I will do is add FontAwesome to the Showcase using external FontAwesome like here:: https://primefaces.github.io/primefaces/10_0_0/#/core/fonticons?id=fontawesome-5x-or-higher

**Comment by melloware** [comment]
OK I fixed it by adding FontAwesome to the showcase and now that example looks fine again.

**Comment by jepsar** [comment]
Shouldn't we document this in the showcase?

**Comment by melloware** [comment]
Maybe on the main org chart page?

**Comment by melloware** [comment]
I added a note to the main page this this component requires FontAwesome.

**Comment by jepsar** [comment]
I modified it a bit to make clear that the user needs to load it.

**Comment by melloware** [comment]
Excellent.

**Comment by jxmai** [comment]
Nice! That's awesome that font-awesome can be loaded separately still after the built-in one be removed. Really quick on updating the documentation and code changes. Thanks!
