### ISSUE TITLE
New Component: Image Zoom

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions#461]
**Is your feature request related to a problem? Please describe.**
Need a zoomable component for viewing images. Should be as useful as` p:graphicImage`/`p:galleria`

**Describe the solution you'd like**
https://fengyuanchen.github.io/viewerjs/ (5.9k stars, still maintained)

**Comment by melloware** [comment]
This could also replace this ticket which has been out there for 6 years....

https://github.com/primefaces/primefaces/issues/61

So it may kill 2 birds with 1 stone!

**Comment by melloware** [comment]
I went with this one: https://github.com/francoischalifour/medium-zoom

And you can use it with `graphicImage` like this...

```xml
    <p:graphicImage id="tibet"
                    alt="Tibet"
                    value="/resources/images/imagezoom/tibet-small.jpg"
                    pt:data-zoom-src="/showcase-ext/resources/images/imagezoom/tibet-hd.jpg"/>

    <pe:imageZoom for="tibet"/>
```

or with `Galleria` like this...

```xml
<p:galleria id="galleria" value="#{images}" var="image">
            <p:graphicImage value="/images/#{image}"
                            a:data-zoom-src="/images/hd/#{image}"/>
</p:galleria>
<pe:imageZoom for="galleria"/>
```

**Comment by melloware** [comment]
@jepsar @Rapster @fcorneli  Feel free to code review and suggest changes.

**Comment by fcorneli** [comment]
When implementing to component as suggested at https://github.com/primefaces/primefaces/issues/8586 we also tried out different Javascript zoom libraries. Although https://github.com/francoischalifour/medium-zoom is far from active, it was the only one that was not too painful to integrate. Easy to hook in and just does the job without too much fancy options (rotate, whatever).

Related to:
```javascript
var selector = PrimeFaces.escapeClientId(this.cfg.target);
        var targetWidget = PrimeFaces.getWidgetById(this.cfg.target);
        if (targetWidget && targetWidget instanceof PrimeFaces.widget.Galleria) {
            selector = selector + " li[class='ui-galleria-item'] > img";
        }

        this.zoom = mediumZoom(selector, this.cfg);
```

In my original code I had to loop over all images within the Galleria. So this is not required to make it work?

**Comment by jepsar** [comment]
> @jepsar @Rapster @fcorneli Feel free to code review and suggest changes.

I'll give it a spin tonight 😃

**Comment by melloware** [comment]
@fcorneli according to their docs that selector can point to any CSS selector that returns 1 or more images.

I agree medium-zoom is easy to integrate and does the job. ViewerJS is really cool but its much largers with a million options and feature to integrate.

Also I just pushed 11.0.3-SNAPSHOT publicly so if you want to try it just add this to your pom.xml

```xml
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependency>
   <groupId>org.primefaces.extensions</groupId>
   <artifactId>primefaces-extensions</artifactId>
   <version>11.0.3-SNAPSHOT</version>
</dependency>
```

**Comment by fcorneli** [comment]
@melloware I tested out 11.0.3-SNAPSHOT `pe:imageZoom` within our application against a `p:galleria`. You're right about the CSS selector stuff. Works like a charm. Thanks!

**Comment by melloware** [comment]
Great news!
