### ISSUE TITLE
PrimeFacesScriptProcessor: Uncaught Synatx Error, Primefaces.settings rendered in SPAN

### ISSUE THREAD

**Issue by Phipsee** [primefaces-extensions/primefaces-extensions#486]
When using the PrimeFacesScriptProcessor according to the [Showcase](https://www.primefaces.org/showcase-ext/sections/utils/combinedResourceHandler.jsf) you can see in the WebDev-Console "Uncaught SyntaxError: Unexpected token '<'" and when inspecting the webpage you see that the "Primefaces.settings"-Part is inside of a SPAN-tag, which seems to be the cause of the 
error. In the Showcase itself it is not visible, but there can also not see any Primefaces.settings in the head.

When using BalusC approach, the tag gets rendered as expected but after a click or ajax request, Mojarra throws excpetion caused by duplicated id in component. 

Primefaces Extension Code
>private void addJS(FacesContext context, String script) {
        String id = UUID.randomUUID().toString();
        final UIOutput js = new UIOutput();
        js.setId("js-" + id + "1");
        js.setRendererType("javax.faces.resource.Script");
        final UIOutput content = new UIOutput();
        content.setId("js-" + id + "2");
        content.setValue(script);
        js.getChildren().add(content);
        context.getViewRoot().addComponentResource(context, js);
    }

Rendered HTML:
`<script type="text/javascript"><span id="js-a07c21e3-04b7-4063-b3eb-b570c6b974ee2">if(window.PrimeFaces)...</span></script>`

BalusC
>private void addJS(FacesContext context, String script) {
        UIOutput js = new UIOutput();
        js.setRendererType("javax.faces.resource.Script");
        UIOutput content = new UIOutput();
        content.setValue(script);
        js.getChildren().add(content);
        context.getViewRoot().addComponentResource(context, js);
    }

Rendered HTML:
`<script type="text/javascript">if(window.PrimeFaces)...</script>`

**Environment:**
 - PF Version: 10.0.0
 - JSF version: Mojarra 2.3
 - Affected browsers: reproduced in Chrome and Firefox

**To Reproduce**
1. Include the PrimeFacesScriptProcessor according to the showcase
2. Open Browser

**Expected behavior**
No Error (and JS not encapsulated by SPAN-tag?)

**Sample XHTML**
Trivial xhtml-page

**Sample Bean**
No Bean necessary

**Comment by melloware** [comment]
I will investigate this. Thanks for reporting!

**Comment by melloware** [comment]
@Phipsee are you also using in your web.xml...

```xml
    <!-- enable script collecting and moves all script to end of body -->
    <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```

And if not can you try it?

**Comment by Phipsee** [comment]
@melloware 
No I am not using it. When I enable it, the Primefaces.settings seem to get lost..

**Comment by Phipsee** [comment]
I just tried your fix and I got the exception for the duplicated id. 

I kicked also the first id which got me left with the method like this: 

>	    private void addJS(FacesContext context, String script) {
	        final UIOutput js = new UIOutput();
	        js.setRendererType("javax.faces.resource.Script");
	        final UIOutput content = new UIOutput();
	        content.setValue(script);
	        js.getChildren().add(content);
	        context.getViewRoot().addComponentResource(context, js);
	    }

It works fine, no excpetions while navigating or clicking, no span-tag and Primefaces.settitngs in the right place. Can you confrim this?

**Comment by melloware** [comment]
I have verified your fix and implemented it!  Thanks!

**Comment by melloware** [comment]
10.0.3 is in Maven Central now...
