### ISSUE TITLE
QrCode - add style, styleClass attributes

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions#490]
It would be nice if we can generate the qrCode image with a higher resolution than actual rendering it with css to support zoom-in on mobile. For this style or styleClass attributes are required.

`<pe:qrCode size="400" style="width: 200px;">`

**Comment by jepsar** [comment]
FYI With PrimeFaces 11 and up you can render QR codes as SVG. See https://github.com/primefaces/primefaces/issues/7101

**Comment by melloware** [comment]
Added for 10.0.3

**Comment by djmj** [comment]
That sounds even greater!
