### ISSUE TITLE
CreditCard: Using Month Picker feature of Primefaces for expiry

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions#494]
**Is your feature request related to a problem? Please describe.**
Nope, but improvement

**Describe the solution you'd like**
I would like to use Month Picker feature of Primefaces DatePicker component by implementing java.time.YearMonth class, 
in order to simplify backend comparison for expired cards instead of parsing string expireMonth and expireYear.

**Describe alternatives you've considered**

**Additional context**
I would like to know if any inconsistency between DatePicker and jessepollak/card component since it accepts expiry input as text

```
 <input type="text" name="expiry"/>
```

**Comment by melloware** [comment]
Let me try and get this working.  The Card component definitely has its own JS running on that input box to format the date but let me see what I can do.  Not sure it will be possible since DatePicker uses a hidden Input etc and the JavaScript collisions that might occur.

**Comment by aripddev** [comment]
I think that's the reason why i couldn't make it work

**Comment by melloware** [comment]
OK I got it working with a little JS Magic. 

1. You need to mark the `expiry` inputtext as `display:none` to hide it on the page but keep it there.
2. Use MonthPicker and use JS code to set the value of the `expiry` field when a month is selected.

```xml
<p:inputText id="number" placeholder="Card number" inputmode="numeric"/>
<p:inputText id="name" placeholder="Full name"/>
<p:outputPanel id="expiration">
   <p:datePicker id="month" widgetVar="monthPicker" 
    view="month" pattern="MM/yy" yearNavigator="true" yearRange="2000:2050"
    onchange="$('#expiry').val(PF('monthPicker').input.val()); $('#expiry')[0].dispatchEvent(new Event('change'));"/>
   <!-- Hide Expiration field so we can use PF MonthPicker -->
   <p:inputText id="expiry" placeholder="MM/YY" inputmode="numeric" style="display:none"/>
</p:outputPanel>
 <p:inputText id="cvc" placeholder="CVC" inputmode="numeric"/>
```

`$('#expiry').val(PF('monthPicker').input.val());` sets the hidden input to the value from the MonthPicker.

`$('#expiry')[0].dispatchEvent(new Event('change'));` triggers a JS change event on that hidden input so it updates the Card UI.

**Comment by melloware** [comment]
You can see it in Action here: https://www.primefaces.org/showcase-ext/sections/creditcard/basicUsage.jsf
