### ISSUE TITLE
Layout: On page load the page renders prior to the CSS being applied

### ISSUE THREAD

**Issue by smckeetx** [primefaces-extensions/primefaces-extensions#498]
The pages initially load with all text and images but not properly laid out. Then it all snaps in to place. This works perfectly in PF 8.

Appears to be related to the switch from p:layout to pe:layout.

Initially opened this as a bug with PrimeFaces but they have redirected me here.

Have attempted various CSS/jQuery tricks to delay display of page until fully rendered but none work.

![Jolt_effect_menu_item_select](https://user-images.githubusercontent.com/10233004/128741392-570ff2e0-9c8c-4854-91e1-f79ffe1bd674.jpg)

**Comment by melloware** [comment]
Can you provide your exact XHTML or a PrimeFaces Test reproducer: https://github.com/primefaces/primefaces-test

Our showcase uses Layout and the Jquery trick and does not seem to have the issue: https://www.primefaces.org/showcase-ext/views/home.jsf

**Comment by smckeetx** [comment]
This is the default template. These pages are part of a complex application that doesn't lend itself to a simple demo. I've tested it without the JavaScript that appears at the bottom and the problem persists. It has also be tested with all the DIVs converted to p:layoutPanels.

`<!DOCTYPE html>
<html lang="en" 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:tceq_ui="http://tceq.texas.gov/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
>

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>

        <title>#{applicationMgr.app.appName}</title>
        <p:importConstants type="gov.texas.tceq.core.common.TCEQConstants" var="TCEQConstants" /> 
        <p:importConstants type="gov.texas.tceq.core.common.AccesskeyConstants" var="AccesskeyConstants" />       
        <script>
            var contextPath = '#{request.contextPath}';
        </script>

        <link href="#{request.contextPath}/javax.faces.resource/#{applicationMgr.app.largeIcon}.jsf?ln=images" rel="shortcut icon" type="image/png"  />
        <h:outputStylesheet name="slick.css" library="slick" />
        <h:outputStylesheet name="slick-theme.css" library="slick" />
        <h:outputStylesheet name="jquery.contextMenu.css" library="contextMenu" />
        
        <h:outputStylesheet name="tceq-fonts.css?v#{applicationMgr.version}" library="css" />
        <h:outputStylesheet name="tceq-styles.css?v#{applicationMgr.version}" library="css" />
        <h:outputStylesheet name="tceq-components.css?v#{applicationMgr.version}" library="css" />
        <h:outputStylesheet name="css/font-icon-layout.css" library="tceq-layout" />
        <h:outputStylesheet name="css/core-layout.css" library="tceq-layout" />
        <h:outputStylesheet name="css/layout.css" library="tceq-layout" />
        <h:outputStylesheet name="css/font-awesome.min.css" library="font-awesome" />
        <h:outputStylesheet name="tceq-primefaces-overrides.css?v#{applicationMgr.version}" library="css" />
        <h:outputStylesheet name="tceq.application.css?v#{applicationMgr.version}" library="css" />     
        
        <h:outputScript name="detect.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.console.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.error.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.notifications.js?v#{applicationMgr.version}" library="js" />
        
        <h:outputScript name="js/tceq.layout.js?v#{applicationMgr.version}" library="tceq-layout" />
        <h:outputScript name="slick.min.js" library="slick" />
        <h:outputScript name="jquery.contextMenu.js" library="contextMenu" />
        <h:outputScript name="jquery.ui.position.js" library="contextMenu" />
        <h:outputScript name="jquery.ui.position.min.js" library="contextMenu" />
        <h:outputScript name="tceq.custom.primefaces.CtuSelectCheckboxMenu.js?v#{applicationMgr.version}" library="js" />
        
        <h:outputScript name="inputmask/inputmask.js" library="primefaces"/>
        
        <h:outputScript name="tceq.ctuPanel.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.global.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.dirtyform.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.navigation.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.application.js?v#{applicationMgr.version}" library="js" />
        <h:outputScript name="tceq.windowscrollbottom.js?v#{applicationMgr.version}" library="js" /> 
       
        <ui:include src="scriptElLoader.xhtml" />
        <ui:include src="/WEB-INF/resources/templates/applicationScriptElLoader.xhtml" />
        
        <style>
            .ui-growl{padding-top: 50px;}
        </style>
        
        <ui:insert name="head" />
    </h:head>

    <h:body>
        <h:form id="frmJsConsoleRemote" prependId="false">
            <p:remoteCommand name="rcEnableJavascriptConsoleLog" actionListener="#{userMgr.enableJavascriptConsoleLog}" />
            <p:remoteCommand name="rcLogJavaScriptError" update="globalMsgs"  actionListener="#{applicationMgr.logJavaScriptError}" />
            <p:remoteCommand name="rcDisplayMessage" update="globalMsgs"  actionListener="#{applicationMgr.displayMessage}" />
        </h:form>

        <pe:layout id="menuLayout" fullPage="true" stateCookie="true" widgetVar="menuLayoutWidget">
            <pe:layoutPane id="topPane" position="north" resizable="false" closable="false">
                <ui:include src="defaultTopbar.xhtml" />
            </pe:layoutPane>

            <c:if test="#{not applicationMgr.appDown}">
                <pe:layoutPane id="leftMenu" position="west" resizable="false" closable="false">
                 <ui:include src="defaultLeftmenu.xhtml" />
                </pe:layoutPane>
            </c:if>
            <pe:layoutPane id="contentPane" position="center" resizable="false" closable="false"> 
   
                <h:form id="frmMsg" prependId="false"> 
                    
                    <c:if test="#{not empty requestScope.filterErrorMsg}">
                        <div id="filterErrorMsg"  class="ui-message ui-message-error ui-widget ui-corner-all ui-helper-clearfix">
                           <div>
                               <span class="ui-message-error-icon"></span>
                               <span id="filterErrorMsgTxt" class="ui-message-error-detail">
                                   #{requestScope.filterErrorMsg}
                               </span>
                           </div>
                       </div>  
                    </c:if>
                    
                    <div id="globalNotify" style="position:relative;overflow:hidden;">
                        <div id="globalMsgsDiv" aria-live="assertive" aria-atomic="true">
                            <p:messages 
                                id="globalMsgs" 
                                for="globalMsgs" 
                                globalOnly="false" 
                                escape="false" 
                                showDetail="true" 
                                showSummary="true" 
                                showIcon="true" 
                                closable="true" 
                                aria-atomic="true"
                                >
                            </p:messages>
                        </div>
                                                
                        <div id="globalInfosDiv" style="top:0;right:-1000px;bottom:0;position:absolute" aria-live="assertive">
                            <p:growl 
                                id="globalInfos" 
                                for="globalInfos" 
                                showDetail="true" 
                                redisplay="true" 
                                life="7000"
                                severity="info, warn"
                                globalOnly="false" 
                            />
                        </div>                       
                    </div>
                    <div id="otherMsgsDiv" aria-live="assertive" aria-atomic="true">
                        <p:messages 
                            id="otherMsgs" 
                            for="otherMsgs" 
                            globalOnly="false" 
                            escape="false" 
                            showDetail="true" 
                            showSummary="false" 
                            showIcon="false" 
                            closable="true"
                            styleClass="element-invisible"
                        />
                    </div>
                 </h:form>
             
                <a  class="skipnav" id="topMainContent" />
                
                <div class="center">
                
                     <c:if test="#{applicationMgr.appDown}">
                        <h:outputText class="bottomPad1em" style="font-size:102%" value="#{applicationMgr.appDownMessage}" escape="false"  rendered="#{not empty applicationMgr.appDownMessage}" />
                     </c:if>
                     
                     <c:if test="#{applicationMgr.appDownPending}">
                        <h:outputText class="bottomPad1em" style="font-size:102%;color:#808080" value="#{applicationMgr.appDownMessage}" escape="false"  rendered="#{not empty applicationMgr.appDownMessage}" />
                     </c:if>
                     
                     <c:if test="#{applicationMgr.appDownInSixty}">
                        <h:outputText class="bottomPad1em" style="font-size:104%;color:red" value="#{applicationMgr.appDownMessage}" escape="false"  rendered="#{not empty applicationMgr.appDownMessage}" />
                     </c:if>
                 
                </div>
               
                <c:if test="#{not applicationMgr.appDown}">
                     <ui:insert name="content" />
                </c:if>
                                
                <div class="bottomPad1em right hyperlink">
                    <a id="topPageLink" href="#topMainContent" style="padding-right:10px; color:blue">Back To Top</a>
              </div>
            </pe:layoutPane>
        </pe:layout>

        <c:if test="#{empty confirmNo}">
            <c:set var="confirmNo" value="#{coreBundle['common.No']}" scope="request"/>
        </c:if>

        <c:if test="#{empty confirmYes}">
            <c:set var="confirmYes" value="#{coreBundle['common.Yes']}" scope="request"/>
        </c:if>

        <p:confirmDialog
            id="confirmDialogGlobal"
            global="true"
            showEffect="fade"
            hideEffect="fade"
            closable="false"
            styleClass="autoCenter "
        >
            <p:outputPanel style="display: flex; flex-flow:row-reverse nowrap; justify-content:center; align-content:center;">
                <p:commandButton
                    value="#{confirmNo}"
                    type="button"
                    styleClass="ui-confirmdialog-no"
                    icon="ui-icon-close"
                />
                
                 <tceq_ui:spacer width="10" />
                 
                <p:commandButton
                    value="#{confirmYes}"
                    type="button"
                    styleClass="ui-confirmdialog-yes primary-colored-button"
                    icon="ui-icon-check"
                />
            </p:outputPanel>
        </p:confirmDialog>

        <ui:include src="includeHelp.xhtml" />
        <ui:include src="includeLogoutDialog.xhtml" /> 
        
	    <pe:blockUI id="bui" widgetVar="bui" css="{top: '47%', left: '47%'}">
	        <div id="buiWhiteBox" class="center autoCenter">
	        	Please wait...<br />
	        	<p:graphicImage name="ajax-loader-spin-blue.gif" library="images"/>
	        </div>
	    </pe:blockUI>
        
        <p:ajaxStatus oncomplete="hideWait();" />
    
        <tceq_ui:ctuConfirmDialog
            id="dirtyDialogConfirmDlg"
            header="#{coreBundle['common.Confirm']}"
            width="600"
            yesOnclick="confirmDirtyDialogEvent(true);"
            noOnclick="confirmDirtyDialogEvent(false);"
        >
            <div class="ctuConfirmDialogMsg">
                #{coreBundle['dialog.DirtyFormAlertText']}
            </div>
        </tceq_ui:ctuConfirmDialog>    
    
        <tceq_ui:ctuConfirmDialog
            id="leaveDirtyFormDialog"
            header="#{coreBundle['common.Confirm']}"
            width="600"
            yesOnclick="tceqNavStack.leaveDirtyFormDialogAnswer(true);"
            noOnclick="tceqNavStack.leaveDirtyFormDialogAnswer(false);"
        >
            <div class="ctuConfirmDialogMsg">
                #{coreBundle['dialog.DirtyFormAlertText']}
            </div>
        </tceq_ui:ctuConfirmDialog>
        
        <tceq_ui:ctuConfirmDialog
            id="tabPanelLeaveDirtyFormDialog"
            header="#{coreBundle['common.Confirm']}"
            width="600"
            yesOnclick="tabPanelLeaveDirtyFormDialogApply(true);"
            noOnclick="tabPanelLeaveDirtyFormDialogApply(false);"
        >
            <div class="ctuConfirmDialogMsg">
                #{coreBundle['dialog.DirtyFormAlertText']}
            </div>
        </tceq_ui:ctuConfirmDialog> 
      
        <tceq_ui:ctuConfirmDialog
            id="dataTableExportExceedsLimitDialog"
            header="#{coreBundle['common.CannotExport']}"
            width="600"
            yesOnclick="exportThresholdContinue(true);"
            renderNo="false"
            yesLabel="Ok"
        >
            <div class="ctuConfirmDialogMsg">
                #{coreBundle['dialog.DataTableExportLimitExceeds']}
            </div>
        </tceq_ui:ctuConfirmDialog>  
        
        <tceq_ui:ctuConfirmDialog
            id="pageChangeDirtyDlg"
            header="#{coreBundle['common.Confirm']}"
            width="600"
            renderNo="false"
            yesLabel="Ok"
            yesOnclick="hideDialog('pageChangeDirtyDlg');"
        >
            <div class="ctuConfirmDialogMsg">
                You have unsaved changes. Page navigation is disabled until changes have been saved or cleared.
            </div>
        </tceq_ui:ctuConfirmDialog>         
    
        <tceq_ui:ctuConfirmDialog
            id="deleteDirtyDlg"
            header="#{coreBundle['common.Confirm']}"
            width="600"
            renderNo="false"
            yesLabel="Ok"
            yesOnclick="hideDialog('deleteDirtyDlg');"
        >
            <div class="ctuConfirmDialogMsg">
                You have unsaved changes. Delete is disabled until changes have been saved or cleared.
            </div>
        </tceq_ui:ctuConfirmDialog>  
    
        
        <script>
            console.log('defaultTemplate');
            
            $(document).ready(function() {
                console.log('defaultTemplate: onReady()');
                
                mnuWidget = PF('menuLayoutWidget');
                resizeLeftMenuLayoutContainer();
            });

            $("#layout-menubar-resize").click(function() {
                resizeLeftMenuLayoutContainer();
            });

            $(window).resize(function() {
                resizeLeftMenuLayoutContainer();
            });
            
            $(window).scroll(function () {
                  var st = $(window).scrollTop();
                  var scrollBottom = $(document).height() - $(window).height() - $(window).scrollTop();
            });

        </script>
    </h:body>
</html>
`

**Comment by melloware** [comment]
From looking at your code why is `fullPage="true"` when your layout is the only thing in your page?

**Comment by melloware** [comment]
Also our Showcase uses MOVE_SCRIPTS_TO_BOTTOM and the jquery trick.  Can you compare what is different and why our Showcase works properly and yours does not?

**Comment by smckeetx** [comment]
fullPage="true" is a left over from the p:layout we used with PF 8 but since true is the default now I'm not sure it should make a difference.

I tried MOVE_SCRIPTS_TO_BOTTOM and the jQuery trick referenced here https://forum.primefaces.org/viewtopic.php?f=3&t=60583&p=185873 as recommended by Burak Unsal at PrimeFaces to no avail. What seems to be happening is the layoutPane gets converted to a div with a style in it that includes visibility:visible which defeats the jQuery trick.

**Comment by melloware** [comment]
it should not because the whole HTML node is not displayed making all its children invisible with this CSS.

```css
html {
    overflow: auto !important;
    visibility: hidden;
}
```

There is no way anyting can be displayed inside the main HTML node if the whole thing is not currently visible.  Are you sure you applied the Jquery trick properly?

**Comment by smckeetx** [comment]
I will give it another shot but I believe I did. As a test I even left off the resetting of it so that the page should have remained blank at the end.

**Comment by melloware** [comment]
yeah because the PF showcase is a fullpage Layout pane with the jquey trick and its rendering correctly.

Our global.css
```css
html {
    overflow: auto !important;
    visibility: hidden;
}
```

JS code in our template.xhml
```javascript
// configure the layout
            $(document).ready(function () {
                // trim whitespace from code blocks
                $("code[class^='language-']").each(function () {
                    $(this).html($(this).html().trim());
                });

                // remove the z-index so some elements get rendered on top
                $("#layoutCenter").css("z-index", '');

                // show the HTML pane after everything has been asjusted
                // https://stackoverflow.com/questions/9550760/hide-page-until-everything-is-loaded-advanced/9551066
                document.getElementsByTagName("html")[0].style.visibility = "visible";
            });
```

**Comment by smckeetx** [comment]
I believe I have implemented this correctly and have intentionally commented out the setting of the visibility attribute to visible and it is all quite visible and the page still initially renders improperly.

![image](https://user-images.githubusercontent.com/10233004/128755632-779c40f7-a27c-417e-a38b-fe3c9498c473.png)


But when you get down to the pe:layoutPane with an ID of topPane its visibility is set to visible and the HTML visibility is trumped.

![image](https://user-images.githubusercontent.com/10233004/128755649-1f290a9a-254e-45da-8e1b-8e175362e160.png)


![image](https://user-images.githubusercontent.com/10233004/128755668-bf41a452-f038-42c5-81fc-a4851253932e.png)

**Comment by melloware** [comment]
Yep this reproducer proves it:
[pfe-498.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/6956731/pfe-498.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml verifies what you are seeing.

**Comment by melloware** [comment]
OK can you try this reproducer it includes a patched layout.js that fixes this problem.
[pfe-498-fixed.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/6956879/pfe-498-fixed.zip)

**Comment by smckeetx** [comment]
That worked! Is there an ETA for 10.0.4?

**Comment by melloware** [comment]
No I just release 10.0.3 this morning so no ETA for 10.0.4 yet but you should be able to use that patch I sent in your project in the meantime.

**Comment by smckeetx** [comment]
Yes we can. Thanks!

**Comment by melloware** [comment]
10.0.4 is in Maven Central now!

**Comment by smckeetx** [comment]
Thanks
________________________________

**Comment by melloware** [comment]
cc @GedMarc in case you were interested in seeing this hack i had to make.

**Comment by GedMarc** [comment]
I'm wondering if this can be solved with the live resize option actually, but the problem here is actually the ordering of the output, I think - 

The layouts are actually calculations in JS, very very little CSS in that regard - there were a lot of reasons for this CSS1, IE678, Multi Browser compatibility etc. Also a very bothersome problem IOS and CSS which denied a lot of the wanted functionality. Just never took it off JS into CSS really.

Right now -  
It does depend on the browser to get the render right - There is always a small delay between render CSS and execute JS but you're not supposed to see or feel it - or you do the standard "cloak"

Soooooo for right now I can only think of this until I have done the CSS3 move 
A. Executing scripts at the bottom of the page have the side effect of the CSS getting loaded first, but they have to be put there. Only use async and other enhanced flags for scripts in this section
B. Keep your framework scripts at the top in the header of the page, JQuery, bootstrap etc to load synchronously before the body tag gets hit and prepare the body bubble events. no enhancement flags on the script tag
C. You can now put the .layout() tag anywhere under the declaration or in a document.ready() rather than at the end of the close tag render cycle just before your scripts. CSS problem gone, JS loading correctly bla bla bla

You can then remove the cloak and the hack while retaining the proper render cycle in the browser :) 

For PF the cloak and dagger approach for now is definitely better until I migrate everything to CSS
