### ISSUE TITLE
Layout: Layout shift - inner components are rendered before the layout

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions#500]
**Describe the bug**
Inner components in layout can be rendered ahead of the layout itself causing layout shift.

**Reproducer**

[primefaces-test.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/6979771/primefaces-test.zip)

Main xhtml:

```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

		<pe:layout fullPage="false">
		 	<pe:layoutPane position="west">
		    	<div style="background:red;width:100%">test</div>
		    	
		    	 <p:inputText value="West Text" style="width:100%"/>             
		    </pe:layoutPane>
		    
		    <pe:layoutPane position="center">
		    	<p:inputText value="Main Text" style="width:100%"/>   
		    </pe:layoutPane>
		 </pe:layout>
    </h:body>
</html>
```

**Environment:**
 - PF Version: _10.0_

**To Reproduce**
1. `mvn clean jetty:run`
2. Go to http://localhost:8080/primefaces-test/
3. Refresh the page and see if there's flickering

**Expected behavior**
The layout should be rendered before the inner components, layout shift shouldn't happen.

---

As a closer look, we can see at some point the layout hasn't been rendered yet while the inner components are rendered before the layout. Let's see if this is a known issue or there's something I missed :eyes: .

![image](https://user-images.githubusercontent.com/10467831/129303415-121202d6-cf0c-43c5-8679-a3f741003724.png)

**Comment by melloware** [comment]
I think this is the way the PFE layout has always worked.  Because its a years newer version than the old PF one it supports responsive displays so I believe it is rendering the inner panels first to know for responsiveness and screensize whether they should start open or not.  @GedMarc any thoughts?

**Comment by melloware** [comment]
@jxmai Can you try this version:
[pfe-500.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/6982254/pfe-500.zip)


It implements MOVES_SCRIPTS_TO_BOTTOM and a Jquery trick from this ticket:  https://github.com/primefaces-extensions/primefaces-extensions/issues/498

**Comment by melloware** [comment]
Updated reproducer: 
[pfe-500-updated.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/6982256/pfe-500-updated.zip)

**Comment by jxmai** [comment]
Thanks @melloware. The updated reproducer is working fine. It was not intuitive to make this work so that's awesome to know such trick. I put a summary of what has changed in the reproducer compared to the original file


1. Include the following layout.js with the fix below

https://github.com/primefaces-extensions/primefaces-extensions/commit/59a9d5a0b2af3c52d9600ecb34b6d6e36f3784c7

2. Using:

```xml
<context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```

3. include the following js

```js
 $(document).ready(function () {
                // show the HTML pane after everything has been asjusted
                // https://stackoverflow.com/questions/9550760/hide-page-until-everything-is-loaded-advanced/9551066
                document.getElementsByTagName("html")[0].style.visibility = "visible";
});
```

4. include the following css:




```css
html {
    overflow: auto !important;
    visibility: hidden;
}
```

**Comment by melloware** [comment]
Thank you for documenting. The layout fix i had to make will be in 10.0.4

**Comment by melloware** [comment]
10.0.4 is in Maven Central now!

**Comment by jxmai** [comment]
Sounds good. Thanks for letting me know!

**Comment by melloware** [comment]
I think we made the better fix here: https://github.com/primefaces-extensions/primefaces-extensions/issues/563

**Comment by melloware** [comment]
8.0.5 is now in Maven Central
