### ISSUE TITLE
Layout: Wrong URL to jQuery documentation

### ISSUE THREAD

**Issue by barsk** [primefaces-extensions/primefaces-extensions#515]
The external link for "Overview of Layout Options" points to 
http://layout.jquery-dev.net/documentation.cfm#Options
This gives an 404 error, document not found.

Should be changed to:
http://layout.jquery-dev.com/documentation.cfm#Options

**Comment by melloware** [comment]
Thanks for reporting I have fixed it in Git and it will be pushed on next Showcase deploy! I also updated the ChangeLog URL to point at the fork we are using: https://github.com/GedMarc/layout
