### ISSUE TITLE
New Component: SanitizingConverter

### ISSUE THREAD

**Issue by flange-ipb** [primefaces-extensions/primefaces-extensions#519]
Hi folks,

I'm bringing [my previous feature request from OmniFaces](https://github.com/omnifaces/omnifaces/issues/636). It would be great to have a reusable FacesConverter that sanitizes strings using [OWASP Java HTML Sanitizer](https://github.com/OWASP/java-html-sanitizer)'s PolicyFactory. My typical uses cases are in connection with p:textEditor and when rendering the generated text with via h:outputText with escape="false".

Examples from one of my active projects:
- [RichTextConverter](https://github.com/ipb-halle/CRIMSy/blob/master/ui/src/main/java/de/ipb_halle/lbac/util/RichTextConverter.java) for use with p:textEditor (we still use PF 6.2 where this component doesn't try to perform sanitizing)
- [InputConverter](https://github.com/ipb-halle/CRIMSy/blob/master/ui/src/main/java/de/ipb_halle/lbac/util/InputConverter.java): Sometimes we see that `PolicyFactory.sanitize(String)` also escapes some characters, so we additionally apply `Encoding.decodeHtml(String)`, which is also part of the [OWASP HTML Sanitizer library](https://www.javadoc.io/doc/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/latest/org/owasp/html/Encoding.html). To be honest, we haven't investigated this issue very deeply, but if necessary, I can supply some test strings.

Configuration:
- The PolicyFactory object should be configurable by a `policyFactory` attribute. Thus, this converter needs to have a tag as pointed out by @BalusC in the original ticket.
- What should the default PolicyFactory be if none was passed in? I think `new HtmlPolicyBuilder().toFactory()`, which sanitizes any HTML.
- Maybe make the invocation of `Encoding.decodeHtml(String)` optional by a boolean attribute.

Best,
Frank

**Comment by jepsar** [comment]
If we can use a reasonable default policy, I do see the point. Else, if you would need to create your own policy anyway, you are minutes away from creating your own converter.

**Comment by flange-ipb** [comment]
> Else, if you would need to create your own policy anyway, you are minutes away from creating your own converter.

Indeed, that's a valid argument. I think, from the perspective of a JSF developer, having a reusable converter tag that can invoke PolicyFactories has a higher abstraction level compared to a PolicyFactory.

Imagine a company with many JSF projects and trying to enforce a common security policy. How would you do that?
- Make a security project with all PolicyFactories that are allowed to be used. All projects have this security project as dependency.
- JSF developers in each project start implementing the same JSF converter and most probably make mistakes (because they forgot to read the JavaDoc of Converter). At the end of the day, some developers may take a look at what the other projects did and either copy-paste the implementation or use it via a dependency. That's hell!

**Comment by melloware** [comment]
I think this is an easy Converter to add with a default PolicyFactory but allow a custom policy factory to be passed in.

**Comment by melloware** [comment]
Example usage:
```xml
<p:inputText id="defaultSanitizer" value="#{sanitizingController.defaultSanitizer}">
        <pe:sanitizer/>
</p:inputText>

<p:inputText id="customSanitizer" value="#{sanitizingController.customSanitizer}">
       <pe:sanitizer decodeHtml="true" policy="#{sanitizingController.policyFactory}"/>
</p:inputText>
```

**Comment by melloware** [comment]
I think this works great!  Also you will notice in the Converter I did not use `import` statements I used the full class name each time for `Encoder` and `PolicyFactory` so if someone doesn't have OWASP on their classpath it won't get any ClassNotFound errors unless you ACTUALLY try and use `pe:sanitizer`

**Comment by melloware** [comment]
Showcase example up: https://www.primefaces.org/showcase-ext/sections/converters/sanitizingConverter.jsf

I fixed the bug already that the ManagedBean is not showing up on that page. I had a typo.
