### ISSUE TITLE
LightSwitch: render UI for light and dark + click to toggle

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#529]
Facets is probably ideal for this.

**Comment by melloware** [comment]
@jepsar any chance you want to get this in 10.0.6 ?

**Comment by jepsar** [comment]
Feel free to release 10.0.6. I will be offline the coming days.

**Comment by jepsar** [comment]
Maybe better to add facets to `p:toggleSwitch`. Seems to be more generic.

**Comment by melloware** [comment]
So if you have widget methods available in JS code can't you just hook them up to ToggleSwitch `onclick`?  Or were you thinking you wanted it to be server side?

**Comment by jepsar** [comment]
That is exactly what we currently do in the showcase. I was thinking of being able to use a sun and moon icon. But this could also be done with the toggle switch component, if it would have two facets.

**Comment by melloware** [comment]
Maybe I am confused can't you just do this...

```xml
<p:toggleSwitch value="#{userSettings.contrast}">
            <p:ajax listener="#{userSettings.updateTheme}" update="lightswitch"/>
</p:toggleSwitch>
```

And in the `updateTheme` method flip from light to dark.  And you can use the sun and moon icons from this hack: https://github.com/primefaces/primefaces/issues/7901

**Comment by jepsar** [comment]
In the showcase we simply do
```xhtml
<p:toggleSwitch onchange="PF('lightSwitch').toggle()"/>
```
I don't want use the default toggle switch UI, just the sun and moon icons. Anyway, I don't think it'll make sense to add that to this component. Having this in toggle switch or select boolean checkbox is better IMO.

**Comment by melloware** [comment]
Understood!
