### ISSUE TITLE
MonacoEditor: Add diff editor

### ISSUE THREAD

**Issue by sdemirhan2478** [primefaces-extensions/primefaces-extensions#537]
Can diff editor be added for monaco editor.
thanks.

**Comment by melloware** [comment]
I don't think it comes out of the box with Monaco. See: https://github.com/microsoft/monaco-editor/issues/2332

cc @blutorange

**Comment by blutorange** [comment]
He contacted me via email, I told him should open a feature request here : ) Monaco editor does come with a diff editor:

![image](https://user-images.githubusercontent.com/2456413/132513252-93806d14-89aa-4571-bd82-2ba016bd984a.png)

There are a few things to work out, such as how the Java and XHTML API should look like, but for the most part, it's just calling a different function when creating the editor. Probably can't implement this immediately, but I'll take a look at this when I've got some time.

**Comment by melloware** [comment]
OK I assigned to you.

**Comment by blutorange** [comment]
Quick update: this almost done now. Just need to do a quick review and test a little bit more.

If anybody wants to check it out, you can check out my branch and run the showcase. Any feedback or change requests before this is merged are welcome.

![image](https://user-images.githubusercontent.com/2456413/151720104-68584222-330c-4efd-a6bd-0f24ce0d5fa2.png)

**Comment by melloware** [comment]
Awesome work!

**Comment by melloware** [comment]
I added this to Milestone 11.0.1 i will release 11.0.1 with this fix was hoping Monaco would do a release as well so we can get your FreeMarker stuff in there as well!

**Comment by melloware** [comment]
Can now be seen on the showcase: https://www.primefaces.org/showcase-ext/sections/monacoEditor/basicUsageDiff.jsf
