### ISSUE TITLE
MonacoEditor: add @ResourceDependency(library = "primefaces-extensions", name = "primefaces-extensions.js")

### ISSUE THREAD

**Issue by christophs78** [primefaces-extensions/primefaces-extensions#548]
XHTML includes 
```xhtml
<pe:monacoEditor id="monacoEditorSamlTicket" widgetVar="monacoEditorSamlTicket"
				 value="#{indexView.samlAssertionPretty}"
				 readonly="true" autoResize="true" width="100%" height="400px"
				editorOptions="#{indexView.editorOptions}" locale="de"/>
```

JS throws an error:
![image](https://user-images.githubusercontent.com/10461942/134026699-df8b937b-bcc2-4d6a-a5c7-5f5d0fbddf78.png)

MonacoEditor-JS references PrimeFacesExt.VERSION
https://github.com/primefaces-extensions/primefaces-extensions/blob/07e5b09daa9dd56f228035352bb14a870cd8ef39/core/src/main/resources/META-INF/resources/primefaces-extensions/monacoeditor/01-monaco-helper.js#L173

`PrimeFacesExt.VERSION` is provided by `primefaces-extensions.js`.

So should `org.primefaces.extensions.component.monacoeditor.MonacoEditorInline` and `org.primefaces.extensions.component.monacoeditor.MonacoEditorFramed` add
`@ResourceDependency(library = "primefaces-extensions", name = "primefaces-extensions.js")`

I currently work arround this issue by adding
`<h:outputScript library="primefaces-extensions" name="primefaces-extensions.js" />`
myself.

Do i miss something?

**Comment by melloware** [comment]
HA nope let me fix
