### ISSUE TITLE
LayoutPane: Toggler cannot be hidden

### ISSUE THREAD

**Issue by StevenHachel** [primefaces-extensions/primefaces-extensions#574]
pe:layoutPane slider cant deactivated. is by attribute closable="false" slidable="false" always visible and usable.
It works perfectly with Primefaces 7.

**Environment:**
 - PF Version Elite: _8.0.13_
 - PF Extensions: 8.0.4
 - JSF Mojarra 2.1.29-11
 - javaEE: javaee-api 6.0
 - Affected browsers: Firefox, Chrome

**Example XHTML**
```html
        <pe:layout id="chefpanel" fullPage="true" style="padding: 0px;">
            <pe:layoutPane id="one" position="north" resizable="false" closable="false" slidable="false">
            </pe:layoutPane>
         </pe:layout>
</h:form>
```

**Comment by melloware** [comment]
I don't think I know what you mean.  Here is a reproducer:
[pfe-574.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/7295260/pfe-574.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

I am using 10.0.0 both PF and PFE.

**Comment by StevenHachel** [comment]
Hey,

her is my example with Primefaces 8. layoutPane attribute closable="false" dosent work.

[pfe-574_PF8.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/7296328/pfe-574_PF8.zip)

**Comment by melloware** [comment]
OK yeah I see its broken in 8.0.4 but its fixed in 10.0.0 and 11.0.0.

**Comment by melloware** [comment]
Your issue is this: https://github.com/primefaces-extensions/primefaces-extensions/issues/155

It works in 8.0 but not in 8.0.1/.2/.3/4

**Comment by melloware** [comment]
I will see if I can cut an 8.0.5 release with this in it.  I think @jxmai and @VsevolodGolovanov wanted backports of Layout fixes as well and @EltonR and @ivy-cst wanted backports of DocumentViewer updates

**Comment by StevenHachel** [comment]
> 
> 
> I will see if I can cut an 8.0.5 release with this in it. I think @jxmai and @VsevolodGolovanov wanted backports of Layout fixes as well and @EltonR and @ivy-cst wanted backports of DocumentViewer updates

very nice! :-D

**Comment by melloware** [comment]
8.0.5 is now in Maven Central!  Let me know how it goes.

**Comment by StevenHachel** [comment]
Hello,

the bug it fixed, but now there is a problem with the internal css (layout/layout.css).
you have now added this:
```
body.ui-layout-container, body .ui-layout-container {background-color: var (- surface-a, # fff)}
body .ui-layout-container .ui-layout-unit {border: 1px solid var (- surface-d, # dee2e6); background-color: var (- surface-a, # fff)}
body .ui-layout-resizer {background-color: var (- surface-b, # c8c8c8)}
...
body .ui-layout-unit {-moz-border-radius: 0; -webkit-border-radius: 0; border-radius: 0; background-color: var (- surface-a, # fff)}
body .ui-layout-unit .ui-layout-unit-header {padding: .571em 1em .571em 1em; font-weight: 700}
```

That has to come out again so that the actual body background is not overwritten. 
The versions 8.0./1/2/3/4 do not have these changes in the css. That looks weird and overwrites the actual body css of the page.

**Comment by melloware** [comment]
Ahhh this is necessary for all the primefaces premium themes.  simply override them in your local CSS.

I don't plan on cutting any more 8.0x releases.

**Comment by melloware** [comment]
You can actually just extract the layout.css from 8.0.4 and in your own project put it in the same location `/resources/primefaces-extensions/layout/layout.css` and when it gets loaded it find your version first instead of the one in the JAR file.

**Comment by StevenHachel** [comment]
Override css works for me. thx for your work! :-)
