### ISSUE TITLE
Tooltip: renders its children while in the middle of using WidgetBuilder

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces-extensions/primefaces-extensions#578]
**Describe the bug**
Tooltip renders its children while being in the middle of using WidgetBuilder.
PrimeFaces reuses a single WidgetBuilder instance.
If the children use WidgetBuilder too, they risk affecting its internal state (namely the endFunction field) in such a way, that later Tooltip won't finish its widget properly.

**Reproducer**

**Environment:**
 - PF Version: _6.2.30_
 - PFE Version: _6.2.10_
 - JSF + version: 
 - Affected browsers: _ALL_

**To Reproduce**
Open the page, see error in console (`Uncaught SyntaxError: Unexpected end of input`  in Firefox).

**Expected behavior**
No errors, valid markup.

**Sample XHTML**
```xml
<pe:tooltip>
	<p:dataGrid columns="1">
		Ayy
	</p:dataGrid>
</pe:tooltip>
```

**Furthermore**
Related discussion and changes here: https://github.com/primefaces/primefaces/issues/3110#issuecomment-354194466 - this is when @tandraschko changed `wb.append("},true);});");` to `wb.finish()`, which uncovered the problem.
Now, seemingly by a happy accident, this problem doesn't happen in PF10+PFE10. Because WidgetBuilder gets inited with endFunction=false not on a widget by widget basis anymore, but:
```
if ((context.isPostback() && context.getPartialViewContext().isAjaxRequest()) || configuration.isMoveScriptsToBottom()) {
    this.init(widgetClass, widgetVar, id, false);
}
else {
    context.getResponseWriter().write("$(function(){");
    this.init(widgetClass, widgetVar, id, true);
}
```
So either all widgets per request have endFunction=false, or all have it=true.
Still, this could be a problem in the future. Perhaps
1. Tooltip should render it's children to a buffer before building the widget.
2. PrimeFaces' WidgetBuilder should prevent such misuse by adding a new boolean like this:
```
private boolean building;

init() {
    checkState(!building);
    building = true;
}

finish() {
    building = false;
}
```

**Comment by melloware** [comment]
@tandraschko thoughts on this one?  We can definitely buffer the tooltip with FastStringWriter as option 1.

**Comment by melloware** [comment]
@VsevolodGolovanov it looks like it already does capture its childen in FastResponseWriter?

```java
        if (tooltip.getChildCount() > 0) {
            final FastStringWriter fsw = new FastStringWriter();
            final ResponseWriter clonedWriter = writer.cloneWithWriter(fsw);
            context.setResponseWriter(clonedWriter);
            renderChildren(context, tooltip);
            context.setResponseWriter(writer);
            text = fsw.toString();
        }
        else {
            final String valueToRender = ComponentUtils.getValueToRender(context, tooltip);
            if (valueToRender != null) {
                text = valueToRender;
            }
        }
```

**Comment by VsevolodGolovanov** [comment]
@melloware, it does, but it should do so before getting WidgetBuilder and calling `wb.init`.

**Comment by melloware** [comment]
I see what you mean.

**Comment by melloware** [comment]
@VsevolodGolovanov can you review this fix?  I just basically moved that above the wb.init method.

https://github.com/primefaces-extensions/primefaces-extensions/commit/35597fc868c7af152bfd1ce3bdcc9317729103c8

**Comment by VsevolodGolovanov** [comment]
@melloware, yes, that's good.
