### ISSUE TITLE
New Component: Float label / Field

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#583]
Currently the float label is not supported on all input fields and the order of the rendered HTML is not accessible (label should be rendered before the input). To have the label first, JavaScript will be involved to toggle a class on a parent element.

```xhtml
<pe:field float="true">
  <p:message />
  <p:inputXxx .../>
  <p:label value="..." .../>
  <f:facet name="footer">Help</f:facet>
</pe:field>
```

Renders:

```html
<div class="ui-field ui-field-float-label">
  <label for="..." value="..."/>
  <input .../>
  <div class="ui-message ..." ...>...</div>
  <small>Help</small> (or a div)
</div>
```

**Comment by melloware** [comment]
based on Mert's JS fixes in Ultima I have fixed this in Core and added a Showcase page so we can add components as we fix them for FloatLabel.

See: https://github.com/primefaces/primefaces/pull/8669

![image](https://user-images.githubusercontent.com/4399574/163038953-a2fde14f-2f6c-4273-8cc2-3a51d773a5fc.png)
