### ISSUE TITLE
ColorPicker: add new component based on Coloris

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#601]
https://github.com/mdbassit/Coloris

**Comment by tandraschko** [comment]
im -1 for introducing duplicate components but TBH i didnt use PFE anymore, so its up to you guys

**Comment by jepsar** [comment]
If PrimeTek would include the missing features compared to Coloris, that would be awesome

**Comment by melloware** [comment]
Coloris does look awesome though.  And it does RGB conversion too just not sure about HSB. I am looking at their code and I think it does.

**Comment by jepsar** [comment]
I'll go for https://iro.js.org/colorPicker_api.html which is way more flexible and allows us to replace the current picker in PF without breaking changes and add features later (like alpha, hsla, rgba, wheel, swatches etc).
