### ISSUE TITLE
Sheet: selectItems of SheetColumn evaluation on cell instead of column level

### ISSUE THREAD

**Issue by MatthiasScherrerFGCZ** [primefaces-extensions/primefaces-extensions#612]
XHTML:

```xml
<pe:sheet
          id="sheet"
          widgetVar="sheetWidgetVar"
          value="#{bean.persons}"
          var="person"
          rowKey="#{person.id}"
          showRowHeaders="true"
          styleClass="sheet">
    <pe:sheetcolumn
                    headerText="instrument"
                    value="#{person.instrument}"
                    colType="autocomplete"
                    selectItems="#{instrumentList.getEnabledInstrumentsIncluding(person)}"
                    autoCompleteStrict="false"
                    autoCompleteVisibleRows="10" />
</pe:sheet>
```

```java
public class Person {

private String name;

private Instrument instrument;
}

public class Instrument {

private String name;

private boolean enabled;
}

public class InstrumentList {

public List<Instrument> getEnabledInstrumentsIncluding(Person person) {
    return (List<Instrument>) service.getEnabledInstrumentsIncluding(person).getResultList();
}
```

### Use case:
In an excel sheet, only enabled values should be shown in the autocomplete. However, if in the future an instrument is/will be disabled, the autocomplete does not show said instrument anymore in the autocomplete, yet the current instrument still represents a valid selection. Therefore the method gets all the enabled instruments including the one already on the person object.

### Current behavior:
The method 'getEnabledInstrumentsIncluding(person)' is called/evaluated on column level, i.e., it is only called once and hence person always resolves to null. This makes it impossible to populate an autocomplete on the individual cell level.

### Expected behavior:
The method 'getEnabledInstrumentsIncluding(person)' is called/evaluated on cell level.

**Comment by melloware** [comment]
I don't think the way it is currently designed it can be done at the cell level.  I can take a look but I think this was done for performance because the way the sheet works all the JSON data is sent to the sheet up front and not per cell as you click on it.

**Comment by MatthiasScherrerFGCZ** [comment]
@melloware   
Thanks for the information. This was my initial thought. Thanks for looking into it.
