### ISSUE TITLE
New component: Keynote

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions#640]
I am thinking of adding HTML presentation component for JSF.
I'm not sure if we should use the name "keynote" or the original name "revealjs".
reveal.js is an open source HTML presentation framework. It's a tool that enables anyone with a web browser to create fully-featured and beautiful presentations. It can be accessed from https://revealjs.com.

```xhtml
<pe:keynote>
  <pe:keynoteItem>Slide 1</pe:keynoteItem>
  <pe:keynoteItem>Slide 2</pe:keynoteItem>
  <pe:keynoteItem>Slide 3</pe:keynoteItem>
</pe:keynote>
```

Renders
```html
<div class="reveal">
  <div class="slides">
    <section>Slide 1</section>
    <section>Slide 2</section>
    <section>Slide 3</section>
  </div>
</div>
```

**Comment by melloware** [comment]
OK this is pretty slick.  I would vote for Keynote or SlideDeck.   KeyNote reminds people of Apple's product and PowerPoint is a lame name :)

**Comment by aripddev** [comment]
I will go on with Keynote then.

**Comment by jepsar** [comment]
Why should this be a component instead of plain JavaScript? See also the discussion at #124

**Comment by aripddev** [comment]
@jepsar thanks, i read the discussion. Do you think it is not necessary or does it need improvement like database interaction?
Actually i thought this to use for one of my projects. Instead of providing a guide or an user manual provided by customer (uploading/downloading power points), they can prepare an HTML presentation.

**Comment by jepsar** [comment]
@aripddev I appreciate your work, but I don't really see the point if it being a component. Unless maybe there are events that need to be decoded. I think you can achieve the same by simply render the needed HTML and initialize Reveal. Or did you run into issues while doing that?

**Comment by jepsar** [comment]
By the way, the whole "database" thing is a non arg in the other issue.

**Comment by aripddev** [comment]
@jepsar I didn't think about it but you gave me a good idea about "event". In my case, i can use an "event" to check if user complete to read the slides. After reading slides is complete, the form or button can be submitted. What do you think?
Currently I use "disabled" and "rendered" attributes with bean properties.

**Comment by jepsar** [comment]
Yeah, Reveal has some events that can be included.

Also, I would have done:

```xhtml
<pe:keynote>
  <pe:keynoteSlide>Slide 1</pe:keynoteSlide>
</pe:keynote>
```
instead of
```xhtml
<pe:keynote>
  <section>Slide 1</section>
</pe:keynote>
```
so you can use the `rendered` attribute on the slides.

**Comment by jepsar** [comment]
@melloware why did you use the 12.0.0 milestone? It can be added to 11.0.x, right?

**Comment by aripddev** [comment]
@jepsar :) I already did it as `pe:keynoteItem`. I changed it in the first post.

**Comment by melloware** [comment]
I didn't think this component would be complete and tested in time.  PrimeTek was supposed to release 11.0.0 on Monday but did not so maybe today.

**Comment by jepsar** [comment]
Okay, but we can release it with 11.0.1 or 2

**Comment by melloware** [comment]
oh yeah of course.  I just marked it for 12.0.0 right now so it wasn't in 11.0.0

**Comment by melloware** [comment]
I just moved it to 11.0.1.

**Comment by rider87** [comment]
Nice component... 
If I see that right, you could use it also for a gallery (only show pictures) also ?

For me it would be also important, that everything can be loaded from database.
So you can have than two Entities:

**Keynote**
- Setting1
- Setting2

KeynoteItem
- HtmlContent
- Setting1
- Setting2
- ....

And those can be than use to fill the properties from Primefaces:
<pe:keynote setting1="valueFromDatabase">

But this should not be the problem. In you bean you have than:
private Keynote keynote;
private List<KeynoteItem> keynoteItemList

and than something like this:
<pe:keynote var="#{mybean.keynoteItemList}" setting1=#{myBean.keynote.setting1}>

Also events (as already mentioned) would be nice:
- So you can track if a user completed the slides

So you can rebuild in your own app, like this:
https://slides.com/

**Comment by jepsar** [comment]
@rider87 wait until it is merged and simply try `c:forEach`. Events have been taken care of (see PR).

**Comment by melloware** [comment]
Looks like we have some Sonar issues to clean up.
