### ISSUE TITLE
New Helper: Mongo DB Lazy Datatable implementation

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#659]
Thanks to Newk we will be adding a Mongo DB based `LazyDatamodel` similar to the `JPALazyDataModel` added in PF 11.

**Comment by melloware** [comment]
OK committed I took Newk's code and looked at JPALazyDatamodel and made all the changes accordingly to align them

**Comment by newk5** [comment]
Looking good, I think you tagged a different newk though 😄

**Comment by melloware** [comment]
Thanks for the donation

**Comment by melloware** [comment]
@jepsar  We do all that lazy method all based on JPA example assuming Thomas did it all for good reasons.  Feel free to submit any improvements!

**Comment by tandraschko** [comment]
should datasource really a var inside the model?
note that the lazydatamodel might get serialized, therefore i pass the entitymanager via a supplier

**Comment by melloware** [comment]
OK @tandraschko @newk5 I just changed it to be SerailizedSupplier just like JPA does!

**Comment by newk5** [comment]
I thought since it was transient that serialization would not apply to it, but good idea regardless to have both JPA and Morphia datamodel constructors aligned.

**Comment by tandraschko** [comment]
yep but it would be null on a postback

**Comment by newk5** [comment]
Ahh I see, I wasn't aware of that, good to know.

**Comment by melloware** [comment]
Ok documentation added to showcase https://github.com/primefaces-extensions/primefaces-extensions/commit/f29099439733791e9c4504ccc81771cbaebd9032
