### ISSUE TITLE
LightSwitch: Update to use PrimeFaces.env.getThemeContrast

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#704]
Switch to `PrimeFaces.env.getThemeContrast` for 12.0

See: https://github.com/primefaces/primefaces/pull/8354/files

**Comment by melloware** [comment]
Also need to do this for ImageZoom

**Comment by melloware** [comment]
@jepsar all i did was replace our current function because to me it doesn't make sense to change the theme by reading the theme?

**Comment by jepsar** [comment]
Looks good to me
