### ISSUE TITLE
Sheet: Improve hook afterSelectionEnd

### ISSUE THREAD

**Issue by fanste** [primefaces-extensions/primefaces-extensions#743]
PF-Extensions 11.0.2
PF 11.0.0

Not really a bug but an improvement which prevents an error because of how we customized the usage of our sheet component.

The commit https://github.com/primefaces-extensions/primefaces-extensions/commit/c439153d672da9ade650e5b1435e2f261fb72ae1 changed the hook `afterSelectionEnd` so it calls `$this.ht.getSelected()`. Each hook runs in the scope of the handsontable. That means that `this` equals `$this.ht`.

I suggest to change `this.ht` to `this`, which prevents a JS error in that method, as we aded some logic via the hook `afterInit` and our code triggers a cell selection. `afterInit` is executed before the initialization of the handsontable returns and therefore `$this.ht` is not yet set.

**Comment by melloware** [comment]
Can you review my commit just to double check that is what you were expecting?  too bad you didn't report this yesterday I  would have fixed it in 11.0.2 :)

**Comment by fanste** [comment]
I just switched this app to PF11 (because of all the bugs in the datatable in PF10) and nearly rage quitted as the app broke at another area. But yeah, this happens if a component is missused ;) And it was luckily quite simple to workaround this.

Thanks for the quick fix. Looking forward for 11.0.3 ;)

**Comment by melloware** [comment]
Thanks for reporting it!
