### ISSUE TITLE
DataTable: Sorting/Filtering/Paginator etc. not work anymore after updating PF extension from 11.0.0 to 11.0.2

### ISSUE THREAD

**Issue by tuerker** [primefaces-extensions/primefaces-extensions#750]
It looks that PF-Extensions Version > 11.0.0 breaks the datatable functionality of the PF snapshot. Would be great if somebody could have a look at this.

Side-note: I am using Payara 5.2021.8.

Many thanks in advance.

**Comment by melloware** [comment]
Are you sure your issue is not this one: https://github.com/primefaces-extensions/primefaces-extensions/issues/718

**Comment by tuerker** [comment]
thanks for the hint. i will check tomorrow on my office computer where i run the latest payara 2022.1 version. there at least the mentioned issue https://github.com/primefaces-extensions/primefaces-extensions/issues/718 does not appear.

**Comment by melloware** [comment]
so that is my only thought was is breaking your datatable is that you have a classloader issue with Payara and PFE 11.0.2 and need to add to your pom.xml

```xml
<dependency>
    <groupId>org.primefaces.extensions</groupId>
    <artifactId>resources-monacoeditor</artifactId>
    <version>11.0.2</version>
</dependency>
```

Its possible you have Payara configured to eat this log message.

**Comment by tuerker** [comment]
with this dependency it works as expected. many thanks again.

**Comment by melloware** [comment]
Linked to: https://github.com/payara/Payara/issues/5674
