### ISSUE TITLE
CKEditor Not Loading (404 Issue)

### ISSUE THREAD

**Issue by krishnakittu** [primefaces-extensions/primefaces-extensions#754]
PF extensions 11.0.2

Simple reproducable 

<pe:ckEditor />

http://localhost:8080/test/javax.faces.resource/ckeditor/ckeditor.js.xhtml?ln=primefaces-extensions&v=11.0.2&e=11.0.2 returns 404 error

**Comment by krishnakittu** [comment]
Sorry missing dependency for CK Editor.

**Comment by melloware** [comment]
Thanks for posting back
