### ISSUE TITLE
Monaco: Replace url-loader with asset modules

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#765]
URL Loader is deprecated and no longer supported: https://github.com/webpack-contrib/url-loader

They recommend switching to Assert Modules: https://webpack.js.org/guides/asset-modules/

cc @blutorange

**Comment by blutorange** [comment]
Taking a look at our webpack.config, doesn't look like we're even using that loader. Might be a relic from when I set it up initially. Seems to build fine without it, let me do some testing in the showcase.
