### ISSUE TITLE
New Component: RateLimiter

### ISSUE THREAD

**Issue by fcorneli** [primefaces-extensions/primefaces-extensions#772]
As part of a pentest on one of our projects, we received feedback that certain actions should be rate limited.
Hence we created a component to achieve this, based on `resilience4j-ratelimiter`.
Example usage:
```xml
<p:commandButton value="Some action" ...>
    <pe:rateLimiter/>
</p:commandButton>
```
The `rateLimiter` action will do exactly as it says: limit the rate at which the actions behind the `p:commandButton` can be performed. Without parametrization, the rate limiter will use:
* the HTTP session identifier as rate limiter instance

* if no HTTP session exists, use a global rate limiter instance

Another example:
```xml
<p:commandButton value="Login" ...>
    <pe:rateLimiter name="#{loginController.name}"/>
</p:commandButton>
``` 
Here the `rateLimiter` will use the given `name` value as key towards a certain rate limiter instance. This allows you to, for example, limit the rate at which a certain user account can perform logins.
Of course one can also configure the parametrization of the underlying rate limiter instance as follows:
```xml
<p:commandButton value="Login" ...>
    <pe:rateLimiter name="#{registrationController.name}"
        limitForPeriod="5"
        limitRefreshPeriod="5"
        timeoutDuration="5"/>
</p:commandButton>
```
where `limitForPeriod`, `limitRefreshPeriod` and `timeoutDuration` are used to configure the underlying rate limiter instance.

If there is interest in such component as part of `primefaces-extensions`, please make some noise here.

**Comment by melloware** [comment]
Interesting so this component basically says you can only click this button say "once every 5 minutes" or no more than "3 times in 10 minutes" type of limiting?   I think its pretty clever not sure what others think?

**Comment by jepsar** [comment]
Isn't this https://github.com/primefaces/primefaces/issues/2521 / https://github.com/primefaces/primefaces/pull/8214 with addition of `enableAfterAjaxDelay`? Should this also prevent simultaneous users from being able to perform the action?

**Comment by fcorneli** [comment]
> Interesting so this component basically says you can only click this button say "once every 5 minutes" or no more than "3 times in 10 minutes" type of limiting?

@melloware Yes, something like that indeed.

@jepsar  Our implementation is entirely server-side, as client-side cannot prevent a hacker from doing a "manual" AJAX request.
> Should this also prevent simultaneous users from being able to perform the action?

This depends on the value of the `name` attribute. Anyhow, it's not really a locking mechanism, but a brute force attack prevention mechanism.

**Comment by fcorneli** [comment]
Did some initial work on this one. However, I'm not really happy with the cleanup of the `rateLimiterRegistry`.

**Comment by melloware** [comment]
Well just let us know when want us to review

**Comment by fcorneli** [comment]
@melloware FYI... I gave it another shot within `ejsf`. I'm finally happy with the result.

**Comment by melloware** [comment]
Should I close this ticket then?

**Comment by fcorneli** [comment]
Yes this ticket can be closed.
