### ISSUE TITLE
New Component: Localized

### ISSUE THREAD

**Issue by fcorneli** [primefaces-extensions/primefaces-extensions#773]
i18n is boring. Adding labels, and then in every `properties` file define a value for each supported language.
To reduce the effort here, especially for one-time-shot big paragraph translations, we created an `inlineTranslation` component.
Example usage:
```xml
<pe:inlineTranslation>
    <pe:translation language="en">
        To register yourself via eID, you simply need to login.
    </pe:translation>
    <pe:translation language="nl">
        Om jezelf via eID te registreren, dien je je simpelweg eens aan te melden.
    </pe:translation>
    <pe:translation language="fr">
        Pour vous inscrire via eID, il vous suffit de vous connecter.
    </pe:translation>
</pe:inlineTranslation>
```
Here `inlineTranslation` will render the content of the `translation` child that comes closest to the UIViewRoot locale, i.e., `nl-be` will select the `nl` one.
If no match is found, `inlineTranslation` simply takes the first one.

If there is interest in such component as part of `primefaces-extensions`, please make some noise here.

**Comment by jepsar** [comment]
Close to https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/797

**Comment by melloware** [comment]
@jepsar what do you think? It sounds like both of you have had the same need?

**Comment by jepsar** [comment]
@fcorneli can you see if https://github.com/primefaces-extensions/primefaces-extensions/pull/111 fixes your issue? If so we could refactor it into PFE. I see the point @tandraschko made on the PR, but this could be a nice feature one would not have to create from scratch.

**Comment by fcorneli** [comment]
@jepsar Had a look at https://github.com/primefaces-extensions/primefaces-extensions/pull/111
As far as I understand the code, you basically resolve to some directory content? I'm more interested in having the content within the original XHTML, i.e., have it where it's used. Else it feels like doing `properties` files again, which is exactly what I want to avoid.

**Comment by fcorneli** [comment]
En plus, because I selectively render one of the children, the content is not strictly limited to "plain" content only. You can have regular JSF constructs in there (like buttons, whatever).

**Comment by jepsar** [comment]
Isn't`<h:panelGroup rendered="#{view.locale.property eq value}">content</h:panelGroup>` what you are after?

My PR was targeted to be able to translate large content / HTML blocks in certain languages per region with a fallback to a default language. With optional Markdown and EL support. By removing content from the XHTML you can easily add new languages without needing to go over all of the XHTML files.

**Comment by fcorneli** [comment]
> Isn't `<h:panelGroup rendered="#{view.locale.property eq value}">content</h:panelGroup>` what you are after?

Somehow, except for the smart "nl-be" is also "nl" resolving, and the first one as default translation semantics.

**Comment by fcorneli** [comment]
> By removing content from the XHTML you can easily add new languages without needing to go over all of the XHTML files.

That's indeed a draw-back of inlining the translations.

**Comment by jepsar** [comment]
If I'd be to revive the PR again I'll be sticking to the file based structure. In our case we have 4 countries and 4 languages (which are both likely to increase) with text lengths varying from a few lines to about 30 lines. That will get a total mess if you would do that inline.

**Comment by fcorneli** [comment]
You could mix both behaviors, e.g.,
```xml
<pe:inlineTranslation key="some-file-prefix"/>
```
gives file-based translations, else the component uses the inner `pe:translation` stuff.

**Comment by jepsar** [comment]
In that case I think I'd prefer "content" as the tag name and facets for the inline content.

```xhtml
<pe:content ...>
    <f:facet name="en">
        To register yourself via eID, you simply need to login.
    </f:facet>
    <f:facet name="nl">
        Om jezelf via eID te registreren, dien je je simpelweg eens aan te melden.
    </f:facet>
    <f:facet name="fr">
        Pour vous inscrire via eID, il vous suffit de vous connecter.
    </f:facet>
</pe:content>
```

**Comment by fcorneli** [comment]
@jepsar As far as I can remember we also tried it via facets initially. Problem was that a facet can only hold a single JSF component (button, or just text, which also resolves at the end to some internal JSF comp in case of a facet). As we wanted also content like for example:
```xml
Some text. <p:commandButton .../> And some more text.
```
we had to introduce another component for this.

**Comment by tandraschko** [comment]
a facet can hold multiple components actually

**Comment by fcorneli** [comment]
> a facet can hold multiple components actually

I really stumbled upon this problem somewhere...

**Comment by fcorneli** [comment]
https://docs.oracle.com/javaee/6/api/javax/faces/component/UIComponentBase.html#getFacet(java.lang.String)

Returns only a single comp, no?

**Comment by tandraschko** [comment]
check the docs here: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/util/ComponentUtils.java#L437

**Comment by fcorneli** [comment]
> the facet contains multiple childs, so its wrapped inside a UIPanel

mmm... thanks. It's the JSF spec that dictates this?

**Comment by tandraschko** [comment]
yeah

**Comment by jepsar** [comment]
@melloware I'll restore the original PR and add inline to it

**Comment by melloware** [comment]
Sounds great to me.

**Comment by jepsar** [comment]
With the last PR there was a small discussion about the name. `StaticContent` and `LocalizedContent` were proposed.

I'd like to add `Polyglot` to the list. Nice and short. Or `Multilingual`.

You could compare this to JSP `fmt:message`, difference here is that we don't use a short message but (possibly and probably) multiple paragraphs. So just `pe:content` might be suiting.

**Comment by fcorneli** [comment]
Finding intuitive names is always fun. :)
How about `pe:translate` since this is what it's doing?

**Comment by jepsar** [comment]
It's not translating from language A to language B; the contents is fixed in several languages. It will simply find the content in the language matching the view / provided locale.

**Comment by melloware** [comment]
I personally prefer LocalizedContent or just Localized or Localization.

**Comment by tandraschko** [comment]
just my 0.02$ and a bit offtopic:
i dont like this component and pattern very much - but its ok for me, it would just not go directly into PF
i prefer to have as little as possible code in java and xhtml and move i18n to resources file, to not blow up the code itself


in our company, we created a small framework for it as the JSF own framework also isnt perfect.
1) resources property files, with ordinals (similar to config JSR or deltaspike), so they are overwriteable; e.g. you can place your messages.properties in your common lib and overwrite the file itself in a customer-lib or even in the target webapp
2) you can also have messages.br.properties e.g.
3) a context component, to not use the whole "path" in the msg key
    if you have e.g. "myproduct.mainpage.registration.email = Email", you can simply use
    
    ```
    <blub:msgs context="myproduct.mainpage.registration">
       ... many xhtml content ...
        <p:outputLabel value=#{msgs['email']} />
       ... many xhtml content ...
    </blub:msgs>
    ```

4) values are not cached in dev-mode, so f5 reloads it


And a good reason to NOT add something is that you CANT use it e.g. in `p:tab title="...."`

**Comment by jepsar** [comment]
From my side -1 on inline, as that would get very hairy very fast (see above).

I want to offer working with resource files and offer inline as well (just in case you would have only two languages.. again, adding a third will be a pain, hence the -1 on inline from my side).

I do like to have 1 file per content (instance), so it becomes usable for larger blocks of text. For labels one should simply use a message bundle.

Caching should be done by wrapping it in `p:cache`.

**Comment by fcorneli** [comment]
What would be nice is something like the following:
```xml
<pe:translate labelName="some-unique-identifier" editable="true/false">
The initial text here by the dev team that doesn't care about i18n...
</pe:translate>
```
which would allow the translator to edit the translations where they occur (via some icon that shows up when editable=true). No more shuffling around with properties files towards the translators and back (via Excel, whatever).

> And a good reason to NOT add something is that you CANT use it e.g. in p:tab title="...."

Could be handled via some custom EL magic, no?

**Comment by jepsar** [comment]
> I personally prefer LocalizedContent or just Localized or Localization.

From those three I like `Localized` the most.

**Comment by jepsar** [comment]
> No more shuffling around with properties files towards the translators and back (via Excel, whatever).

But, you would need to go through the entire application, hoping to run into each of the content blocks (even more fun if they are conditional).

**Comment by fcorneli** [comment]
@jepsar Tested out the `pe:localized` component. I like the fallback to root directory idea. Intuitive component name too.
Noticed something within the demo. I have my web browser set to:
```
Accept-Language: nl,en-US;q=0.7,en;q=0.3
```
However, when I try the following within the showcase,
```xml
<pe:localized folder="folder1" name="content1" escape="false"/>
```
I get,
```
Content1 (fallback) in root
```
while I would expect,
```
Content1 (nl) in folder1
```

**Comment by fcorneli** [comment]
mmm... `masterLayout.xhtml` has
```xml
<f:view contentType="text/html" locale="en">
```
so, yeah... JSF doesn't take the web browser settings into account I guess.

**Comment by jepsar** [comment]
It's not JSF, it's the way the showcase is built. If no locale is provided to the component, indeed the view locale is used. Normally one would have something like this in a multi language application:
```xhtml
<f:view locale="#{user.locale}">
```

**Comment by melloware** [comment]
I wonder if I should makethe PFE showcase do the same language switching the PF showcase does?

**Comment by jepsar** [comment]
We don't have much multi lingual content. Maybe only on the localized page(s).

**Comment by fcorneli** [comment]
Within our project, I encountered another i18n use case: client-side translations.
Would be nice to have a widget like:
```xml
<pe:dictionary widgetVar="myDictionary" value="#{controller.keyValueMap}"/>
```
which allows you do have an API for client-side translations:
```javascript
PF("myDictionary").getMessage("KEY_XYZ");
```
and with parameters like for example,
```javascript
let amountParameter = 100;
PF("myDictionary").getMessage("PRICE_MESSAGE", amountParameter);
```

Next to a `Map<String, String>` one could maybe also feed an entire `ResourceBundle` to `pe:dictionary` as value.

Maybe even,
```xml
<pe:dictionary widgetVar="myDictionary" value="#{controller.keyValueMap}">
    <pe:onMissingMessage listener="#{controller.logMissingMessageKey}"/>
</pe:dictionary>
```
so the server-side can get some feedback that the front-end guys are missing some messages.

@jepsar @melloware What do you think? Is it worth it that I burn some time on such widget?

**Comment by jepsar** [comment]
Why not use a resource bundle with expression language?

**Comment by melloware** [comment]
Yes isn't this exactly what resource bundle EL already does?

**Comment by melloware** [comment]
and if the key is missing it displays `???message.key???`

**Comment by fcorneli** [comment]
The thing is that I need to access the translations from within a Javascript file.

**Comment by fcorneli** [comment]
Some context: we have a web socket layer, where we receive events within our Javascript, and there I need to be able to speak human language towards the end-user.

**Comment by melloware** [comment]
Ahhh this might be a really specific use case  I see what your issue is now.

**Comment by jepsar** [comment]
But still, that can be done with EL.

**Comment by fcorneli** [comment]
@jepsar How? My Javascript file is just a resource, not "processed" by JSF.

**Comment by jepsar** [comment]
Just get the resource bundle messages you might need to use and put them in an object, either in your JSF page, or create a JSF resource (handler) which does that. You could also create a resource (handler) for your JavaScript and include the messages there. See for example https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/java/org/primefaces/extensions/application/ThemeAccentColorResource.java

**Comment by jepsar** [comment]
@fcorneli were you able to resolve your client side messages issue?

**Comment by fcorneli** [comment]
@jepsar I had a look at using a `ResourceWrapper`. However, I guess I will run into web browser cache issues (when user changes language and such). Not really sure if I want to go into that direction...

**Comment by jepsar** [comment]
Yeah, probably having a separate resource to get messages which includes the locale in the URL will be best in this case.
