### ISSUE TITLE
ImageZoom: make dark theme aware

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#777]
@melloware Maybe wait of PF 12 so we can use the JS you've added for Captcha?

**Comment by melloware** [comment]
Ahhh no lets do it now. I thought of that the other day when I was testing. I will fix it now.

**Comment by melloware** [comment]
Done and I put a note in the other ticket that for PF 12 we can use the core utility instead.

**Comment by melloware** [comment]
CC @fcorneli in case you want to review...

**Comment by jepsar** [comment]
Can't we simply use `var(--surface-a)` as the background here? I haven't checked out the code yet, but it seems to be looking at the OS preference only, not at the selected theme.

**Comment by melloware** [comment]
i haven't tried it but wasn't sure his component would accept `background: var(--surface-a)` as a param because when you set params with JS not with CSS sometimes they don't evaluate properly.  I have had that trouble in my React code.  We can try it though!

**Comment by jepsar** [comment]
In the PF 12 JS we have a function to test a theme name for being dark, right. If var does not work, we can open an issue to properly fix this with 12.

**Comment by melloware** [comment]
Let me test but yeah I already updated this ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/704

**Comment by melloware** [comment]
`this.cfg.background = 'var(--surface-a)';` works perfectly!
