### ISSUE TITLE
MonacoEditor: Value set programatically before render not applied correctly during rendering

### ISSUE THREAD

**Issue by blutorange** [primefaces-extensions/primefaces-extensions#785]
Sounds a bit complicated, you can assign this to me. Fix is rather simple.

---

Monaco editor is initialized asynchronously. The monaco editor widget has a method `setValue` / `setValueNow`. When the editor was not initialized yet, those methods store the target value and set that value once the editor was initialized.

The value is also set on the model when the model is created, but when the monaco editor is not visible on page load  (e.g. when it is inside a tab), the editor is rendered only once it becomes visible. If `setValue` / `setValueNow` is called in that interval, the new value is not set correctly once the editor is rendered. 

https://github.com/primefaces-extensions/primefaces-extensions/blob/master/core/src/main/resources/META-INF/resources/primefaces-extensions/monacoeditor/03-monaco-widget-base.js#L225-L227

The `setValue` call on the lines above does nothing since the `initialized` data key is only set afterward. We need to change the order of these lines, or call another method to ensure the value is being updated.

---

Can be worked around either by replacing `widget.setValueNow(newValue)` with `widget.whenReady().then(e => e.setValueNow(newValue))`, by using the `initialized` behavior event to set the value, or by using one of the extender methods to set the value directly on the model.

**Comment by melloware** [comment]
Done!
