### ISSUE TITLE
CKEditor: Cannot add Links when CKEditor is in Dialog

### ISSUE THREAD

**Issue by fcjm** [primefaces-extensions/primefaces-extensions#804]
**Describe the bug**
We are using the CKEditor in p:dialogs (modals) at some parts within our application. When the additional popup for adding links is opened, the inputs are not responding to user input - some are not even focusable. When using the CKEditor outside of Dialogs everything behaves as expected.

**Reproducer**
[reproducerPF11.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/8489249/reproducerPF11.zip)
[reproducerPF8.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/8489247/reproducerPF8.zip)

PF11/PF10 - defect
PF8 - working

**Environment:**
 - PF Version: _11.0.0 (extensions: 11.0.2)_
 - JSF + version: _Mojarra 2.3_

**To Reproduce**
1. Start reproducer via 'mvn clean jetty:run -Pmojarra23'
2. Go to 'http://localhost:8080/primefaces-test/'
3. Click inside the CKEditor outside of the modal
4. Press Cntrl+K and type text -> works
5. Open Modal
6. Click inside the CKEditor inside the modal
7. Press Cntrl+K and type text -> does not work (other inputs are not focusable)

**Expected behavior**
The CKEditor should respond to user input when used in a p:dialog.

**Comment by fcjm** [comment]
This problem also occurs with other functionalities inside the CKEditor that open new popups. Other examples are Anchors (Flag symbol) or editing Table properties (Table symbol).

**Comment by melloware** [comment]
I see the issue...

**Comment by melloware** [comment]
Its actually the same issue as this one: https://github.com/primefaces/primefaces/issues/8333

**Comment by melloware** [comment]
Can you add this CSS to your project and see if it fixes your issue

```css
// Fix #804 issue with CKeditor in dialogs.
body .cke_dialog_body {
    z-index: 9999;
}
```

**Comment by fcjm** [comment]
Yes with that CSS it works in both the reproducer and in our main application.

**Comment by melloware** [comment]
Thanks for reporting will be in 11.0.3
