### ISSUE TITLE
Sheet: loosing data when working fast, possible bug?

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions#814]
### Describe the bug

Some of our users work fast in a sheet, all changes look ok, possitive growl feedback, but after F5 a lot of changes are reverted.

client side I do `<p:ajax event="change" update="@none" listener="#{perceelSheetController.cellChangeEvent}"`

serverside I have a sessionscoped bean, that stores updates, handles errors and applies client update logic.

Serverside I tried synchronizing, locking. Clientside I tried eliminating other events than change, updating the whole sheet in onchange seems to help but leads to a hard to fix scrolling problem.

I cannot yet exactly pinpoint the problem, not even after extensice debugging client and server, but it looks like a client side problem where the browser sends data before everything that should be completed is completed.

Do some other users of sheet experience problems like this? Could I overlook something crucial?

### Reproducer

Sorry, no reproducer yet

### PrimeFaces Extensions version

11.0.2

### JSF implementation

Mojarra

### JSF version

2.3

### Affected browsers?

firefox

### Expected behavior

updates applied and saved

### Sample XHTML

```xhtml
            <pe:sheet id="sheet" widgetVar="sheetWidget" value="#{perceelSheetController.percelen}" var="row" rowStyleClass="#{row.id == null ? 'nieuw' : ''}"
                      rowKey="#{perceelSheetController.getRowKey(row.id)}" showRowHeaders="true" 
                      resizableCols="true" resizableRows="true" filteredValue="#{perceelSheetController.filtering.filtered}"
                      readOnly="#{not accessController.mayEdit()}">

                <p:ajax event="change" update="@none" listener="#{perceelSheetController.cellChangeEvent}" 
                        onerror="window.setTimeout(function() {focusFirstSheetError('sheetWidget');}, 200);"/>
                <p:ajax event="cellSelect" update="@none" listener="#{perceelSheetController.cellSelectEvent}" disabled="#{perceelSheetController.isChangeErrors()}"/>
```

### Sample Bean

```java
    public void cellChangeEvent(final SheetEvent event) {
.
# I show only the last bit of what this function does because calling update ajax().update( might cause the problem?
.
        JsfUtil.addSuccessMessage("Saved " + percs.stream().map(p -> perceelConverter.getAsString(null, null, p)).collect(Collectors.joining()));
        List<String> pfupdates = new ArrayList<>(3);
        if (gemStatusChange) pfupdates.add("menuform");            
        if (nieuwPerceel) {
            PrimeFaces.current().executeScript("sc();");
        } else {
            pfupdates.add("buttons");            
        }
        if (!pfupdates.isEmpty()) PrimeFaces.current().ajax().update(pfupdates);
    }
```

**Comment by melloware** [comment]
A reproducer would help.  Have you tried async=false on the Ajax call?

**Comment by eduarddrenth** [comment]
isn't that the default?

**Comment by melloware** [comment]
You are right have you tried `true` to not let them queue up?  Have added logging to figure out what AJAX calls are being lost or is it your backend state that is getting out of sync?  Without a test case I can only speculate.

**Comment by eduarddrenth** [comment]
I know, test-case is crucial here....but your remark on async let to a version we are now testing:

- cellSelect event with `async=true`
- change method synchronized
- refresh an object from the database

If this version is stable I'll close this issue or provide a tester

**Comment by jepsar** [comment]
I would expect async to make things worse. If you are not doing so already, you might want to lock the record when you are updating it, to prevent overwriting data.

**Comment by eduarddrenth** [comment]
Yes, therefore cellselect event is `async=true`, change event is `async=false`, change method is synchronized, jpa and optimistic locking garantee data integrity, this probably fixes the issue (awaiting testers)

**Comment by melloware** [comment]
Any update on this?

**Comment by eduarddrenth** [comment]
looks ok, still testing....

**Comment by melloware** [comment]
Awesome definitely post your final solution for others in the future here!

**Comment by eduarddrenth** [comment]
This issue I solved like this:

-  in xhtml make cellSelect call asynchronous **async="true"**-
```xhtml
<p:ajax event="change" update="@none" listener="#{perceelSheetController.cellChangeEvent}" 
                        onerror="window.setTimeout(function() {focusFirstSheetError('sheetWidget');}, 200);"/>
<p:ajax event="cellSelect" async="true" update="@none" listener="#{perceelSheetController.cellSelectEvent}"/>
```
- in Java bean make change method synchronized:
```java
    public synchronized void cellChangeEvent(final SheetEvent event) {
```

**Comment by melloware** [comment]
Excellent I added the workaround label for future users who may have the same issue
