### ISSUE TITLE
DocumentViewer: add timeout & onerror callback

### ISSUE THREAD

**Issue by devmsaleh** [primefaces-extensions/primefaces-extensions#835]
Please add timeout option for loading document timeout in seconds and a timeout callback
also please add onerror callback if exception happens

Scenario: i am trying to load the document from url (rest service)
and the service timeouts and i get an exception from the service
so i want to handle both cases to define timeout in seconds
and also handle when an error comes from the url

**Comment by melloware** [comment]
I moved the issue to the right repo

**Comment by melloware** [comment]
@devmsaleh these are controlled by the PDFViewer itself and not by PFE.  So you will have to add some JS code yourself to subscribe to these events from the Mozilla PDF.js code.
