### ISSUE TITLE
CookiePolicy: Fix Showcase properties docs

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#836]
### Describe the bug

Showcase page: https://www.primefaces.org/showcase-ext/sections/cookiePolicy/basic.jsf

If you look in the bottom right there are no properties for cookiePolicy or saveCookiePolicy.

It should look like how Layout does with Layout and LayoutPane.

Layout: https://www.primefaces.org/showcase-ext/views/layout.jsf

cc @fcorneli 

### PrimeFaces Extensions version

11.0.3

### JSF implementation

All

**Comment by fcorneli** [comment]
@melloware ach... didn't know this was possible.

**Comment by melloware** [comment]
no worries!

**Comment by melloware** [comment]
It was mentioned on Discord: https://discord.com/channels/787967399105134612/787969344768311296/976124106544123924
