### ISSUE TITLE
CKEditor: this.instance.editable is not a function

### ISSUE THREAD

**Issue by bsanders1979** [primefaces-extensions/primefaces-extensions#842]
### Describe the bug

* Currently upgrading from PrimeFaces 5.1 to 11.0
* Tried with both 11.0.2 and 11.0.3

Editor appears to be functioning correctly, but throws this error. I discovered this error on a component within a dialog. I tried outside of a dialog and I get the same error. Once the component in the dialog is rendered, the screen is broke.

![image](https://user-images.githubusercontent.com/1124276/170370028-11420b0c-b868-4a9a-bdbe-793655d8ec94.png)
![image](https://user-images.githubusercontent.com/1124276/170372284-1f4b85dd-b7ea-47c9-9bf6-8cd0f2c2fecd.png)
![image](https://user-images.githubusercontent.com/1124276/170372180-2da7f015-a224-46e3-aaf4-e81ebf46436b.png)
![image](https://user-images.githubusercontent.com/1124276/170372403-fe35ad97-eda6-4dac-b8a8-afc2855e10c9.png)
![image](https://user-images.githubusercontent.com/1124276/170373575-5eb0bb42-1569-4208-94d3-26f2a36db9e9.png)
![image](https://user-images.githubusercontent.com/1124276/170373460-4d36d0b3-468e-471a-8192-5c971f8e675e.png)

I noticed some differences in filenames between my local instance and the showcase.

local
![image](https://user-images.githubusercontent.com/1124276/170373950-e02329e8-9917-4d3f-be0a-82bb2b57aa1d.png)

showcase
![image](https://user-images.githubusercontent.com/1124276/170374061-5110da5c-0618-4baf-ba47-3149fbf54078.png)

### PrimeFaces Extensions version

11.0.3

### JSF implementation

Mojarra

### JSF version

2.2

**Comment by melloware** [comment]
Working fine for me. Unzip this reproducer:  [pfe-842.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/8774790/pfe-842.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

Running Mojarra 2.2, PF 11, PFE 11.0.4

Both inside and outside a dialog.

**Comment by bsanders1979** [comment]
Well, turns out that I needed to upgrade resources-ckeditor. I only figured that out because I was looking for transitive dependencies containing "ck" and it caught my attention. I didn't see it mentioned in the showcase or anywhere else really. Seems like an important detail ;)

**Comment by melloware** [comment]
Yeah sorrry we have it right on our README.MD: https://github.com/primefaces-extensions/primefaces-extensions   CKEDitor and MonicoEditor are separate JARS.

**Comment by bsanders1979** [comment]
Doh! I don't know how I missed that! I appreciate the speedy responses! 👍

**Comment by melloware** [comment]
Let me know if you get to the bottom of your other issue as well.
