### ISSUE TITLE
CKeditor: breaks with custom Resource Handler

### ISSUE THREAD

**Issue by maxpap72** [primefaces-extensions/primefaces-extensions#845]
### Describe the bug

Hi.
We are using PrimeFaces with a custom ResourceHandler ("customGearHandler"). This handler is used for adding a MD5Hash to the querystring of every static resources handled.
For example, the aristo theme is request by the link:
http://localhost:8080/primefaces-test/javax.faces.resource/theme.css.xhtml?ln=primefaces-aristo&customGearHash=1b7c5ba6b20d2b544871bee5cfb92eb9
 
But when a ckeditor is added into XHTML, some component resources are not found (maybe because the link contains an incorrect parameter).
For example, the skin.js return a 404:
 
[http://localhost:8080/primefaces-test/javax.faces.resource/ckeditor/skins/office2013/b69d0ae6c6f0c42942ae6da2896e84skin.js.xhtml?ln=primefaces-extensions&v=7.0.3&customGearHash=12b69d0ae6c6f0c42942ae6da2896e84
 
The strangeness is that these resources are not handled by our customGearHandler.

Why the ckeditor resources  are not handled by a resource handler ?
How URL's static resources are created by PrimeFaces extension ?

If we don't use our customHandler, the ckeditor works well as expected.

The versioning is:
Primefaces version : 7.0.26
Resources-ckeditor: 7.0.3

Thank you
Massimo

### Reproducer

see attached ZIP fil
[primefaces-test-master-ckEditor.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/8799099/primefaces-test-master-ckEditor.zip)
e

### Expected behavior

ckeditor must work well without errors.

### PrimeFaces Extensions version

7.0.26

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

Chrome 102.0.5005.61

**Comment by melloware** [comment]
@maxpap72 First PF 7.0 is older and no longer supported by PFE.  We only support the last 2 major versions which are 10 and 11.  

Second your MD5Hash filter is not necessary as primefaces already does this by adding a cache busting `v=7.0` on the URL? Or you should use OmniFaces CacheControl Filter: https://showcase.omnifaces.org/filters/CacheControlFilter

Third, that makes perfect sense as the CKEDitor has to generate custom URL callbacks for its components and we do this by looking parsing the URL and and replacing it with CKEditor values.  Your "extra" hash in the URL is breaking it.  

Although I did a lot of work there to try and make it bulletproof can you try PF11.0 and PFE 11.0.4?

**Comment by maroswal** [comment]
@maxpap72 I run into the same problem. Had to exclude Apache Deltaspike library in my custom Resource Handler and CKEditor started working again.

**Comment by melloware** [comment]
Yeah CKEditor needs to do these callbacks in the JS code so it tries to build the correct URL to get its resources. So it's probably building incorrect URLs in your situation.

**Comment by melloware** [comment]
I can probably add a workaround for Detaspike if you can watch the f12 network traffic and see one of the CKeditor urls that fails and paste the full URL here

**Comment by maroswal** [comment]
These 3 urls are broken if I don't exclude Deltaspike in my own version resource handler.

http://localhost:8080/app/javax.faces.resource/ckeditor/skins/office2013/-SNAPSHOTskin.js.xhtml?ln=primefaces-extensions&v=12.0.0&appv=0.1.0-SNAPSHOT

http://localhost:8080/app/javax.faces.resource/ckeditor/styles.js-SNAPSHOT.xhtml?ln=primefaces-extensions&v=12.0.0&appv=0.1.0-SNAPSHOT

http://localhost:8080/app/javax.faces.resource/ckeditor/skins/office2013/-SNAPSHOTeditor.css.xhtml?ln=primefaces-extensions&v=12.0.0&appv=0.1.0-SNAPSHOT&t=M2G9

**Comment by melloware** [comment]
Yep its this `&appv=0.1.0-SNAPSHOT` part of the URL that is messing up our logic.  Is that coming from DeltaSpike?  I assume yes if you remove DeltaSpike?

I think its this: https://github.com/apache/deltaspike/blob/master/deltaspike/modules/jsf/impl/src/main/java/org/apache/deltaspike/jsf/impl/resource/DeltaSpikeResource.java#L49

**Comment by maroswal** [comment]
No, that is coming from my own resource handler, because I want my current app version in all urls. 

Relevant parts of my own resource handler. 
```
@Override
public Resource createResource(final String resourceName, final String libraryName) {

	final Resource resource = super.createResource(resourceName, libraryName);
	// Don't add version attribute to certain library urls
	if (this.isExcludeLibrary(libraryName)) {
		return resource;
	}

	return new VersionResource(resource);
}
```

```
private boolean isExcludeLibrary(final String libraryName) {
	return "primefaces".equals(libraryName) || "primefaces-extensions".equals(libraryName)
			|| "primefaces-extensions-uncompressed".equals(libraryName)
			|| "deltaspike".equals(libraryName);
}
```

If I remove the exclude for deltaspike the urls are broken. The excludes for primefaces and primefaces-extensions where always there.

**Comment by melloware** [comment]
OK then yeah the issue is here where in JS we need to construct the correct URL to callback to get the CKEDitor resources.

https://github.com/primefaces-extensions/primefaces-extensions/blob/46e3e702132663c836a229115e2a8fb76dc74624/core/src/main/resources/META-INF/resources/primefaces-extensions/ckeditor/0-ckeditor-helper.js#L39-L112

I have a feeling your custom resource handler is adding in the URL which is breaking the above logic.

**Comment by maroswal** [comment]
Complete code of my resource handler: [VersionResourceHandler.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/10813891/VersionResourceHandler.zip)

**Comment by melloware** [comment]
See: https://github.com/primefaces-extensions/primefaces-extensions/issues/1106
