### ISSUE TITLE
Sheet: java.util.ConcurrentModificationException when SessionScoped and fast updates

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions#851]
### Describe the bug

When using a sheet SessionScoped working fast `entries.remove();` in Sheet#validate on line 725 throws a java.util.ConcurrentModificationException.

Using `Collections.synchronizedMap` instead of `new HashMap<>();` will I think fix the problem.

I try to do a PR

### Reproducer

no

### Expected behavior

When working fast and SessionScoped no ConcurrentModificationException is thrown

### PrimeFaces Extensions version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
I think you want `ConcurrentHashMap` instead see: https://www.baeldung.com/java-synchronizedmap-vs-concurrenthashmap

**Comment by eduarddrenth** [comment]
yes

**Comment by melloware** [comment]
OK let me know how it goes a PR would be great!

**Comment by melloware** [comment]
Just add
```xml
<dependency>
   <groupId>org.primefaces.extensions</groupId>
   <artifactId>resources-monacoeditor</artifactId>
   <version>11.0.4</version>
</dependency>
```

**Comment by eduarddrenth** [comment]
Workaround for now:

`<p:ajaxExceptionHandler type="java.util.ConcurrentModificationException" onexception="$('#buttons\\:ververs').click();alert('Changes not recorded! Working a bit slower may help.');" update="exceptionDialog"/>`

**Comment by jepsar** [comment]
Never tried this, but can't block UI be used here?

**Comment by eduarddrenth** [comment]
Perhaps, but I am not going to introduce that now

**Comment by eduarddrenth** [comment]
Workaround causes different problems. Looks my closed PR does solve this issue using pf 11.0.5, it's being tested, keep you posted

**Comment by eduarddrenth** [comment]
Tests confirm my original PR fixes the issue, I'll reopen it.

**Comment by melloware** [comment]
Nice thanks for reopening and fixing!
