### ISSUE TITLE
InputPhone: Update JS Lib

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#938]
https://github.com/jackocnr/intl-tel-input/releases/tag/v17.0.19

**Comment by jepsar** [comment]
FYI I will take care of this when I get back from vacation (I'll be leaving tomorrow for a week)

**Comment by melloware** [comment]
@jepsar did you forget to submit this PR?  I see you have a branch?

**Comment by jepsar** [comment]
> @jepsar did you forget to submit this PR? I see you have a branch?

No, I wanted to test using the showcase first, but I was not able to. See also Discord (mentioned you there in the PFE channel).
