### ISSUE TITLE
Orgchart: potential CSS corruption after css minifying (hosted in maven)

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions#950]
### Describe the bug

Let's compare the css in line:

https://github.com/primefaces-extensions/primefaces-extensions/blame/master/core/src/main/resources/META-INF/resources/primefaces-extensions/orgchart/orgchart.css#L113

```css
.orgchart>table:first-child{
  margin: 20px auto;
}
```

compared to the css in here, https://mvnrepository.com/artifact/org.primefaces.extensions/primefaces-extensions/11.0.5

if we download the jar and open orgchart.css

![Screenshot_2022-09-25_21-34-57](https://user-images.githubusercontent.com/10467831/192183145-e08b2513-87a4-4444-bf48-80f16cfb680b.png)

we can see there's an extra space in between which can cause css corruption

Defect:
![Screenshot_2022-09-25_19-56-24](https://user-images.githubusercontent.com/10467831/192183813-cfcca348-f756-4496-8268-b3124b2b33fd.png)

Expected:
![Screenshot_2022-09-25_20-21-19](https://user-images.githubusercontent.com/10467831/192183814-e43a35ba-a4dc-4266-bc9c-fc3f6e113483.png)

@melloware Do you know the potential reason of unexpected empty spaces could be added during the resource minifying and broke the style? Thanks:)

**Comment by jxmai** [comment]
For comparison:

https://mvnrepository.com/artifact/org.primefaces.extensions/primefaces-extensions/8.0.5


![Screenshot_2022-09-25_22-07-00](https://user-images.githubusercontent.com/10467831/192185539-6bed6c8a-859b-4dae-bdf1-7d48acc6e26f.png)

The file is OK in the previous version but I don't see any changes in the source code after all since I wrote that a couple years ago (https://github.com/primefaces-extensions/primefaces-extensions/blame/master/core/src/main/resources/META-INF/resources/primefaces-extensions/orgchart/orgchart.css#L113). Any process changes in terms of minimizing the source code? (new lib etc)

**Comment by melloware** [comment]
Yep I know what is going on. Thanks for reporting I will fix it!

**Comment by melloware** [comment]
@jxmai this is fixed in 11.0.6 and 12.0.0

**Comment by jxmai** [comment]
Thanks @melloware for prompt response! The style sheet looks good in https://mvnrepository.com/artifact/org.primefaces.extensions/primefaces-extensions/11.0.6.
