### ISSUE TITLE
Sheet: Setter not found for property autoCompleteTrimDropdown

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions#957]
### Describe the bug

With a sheet column declared like:

```xml
                <pe:sheetcolumn autoCompleteTrimDropdown="false" ..../>
```
An exception occurrs:
```
java.lang.IllegalArgumentException: Setter not found for property autoCompleteTrimDropdown
```

### Reproducer

If needed I can provide

### Expected behavior

The property to work

### PrimeFaces Extensions version

11.0.6 (pf 11.0.7)

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

ff

**Comment by melloware** [comment]
Thanks for reporting. Fixed.

**Comment by eduarddrenth** [comment]
You now hold the record for the fastest fix ever....
