### ISSUE TITLE
Showcase is down

### ISSUE THREAD

**Issue by SteveIreland** [primefaces-extensions/primefaces-extensions#962]
### Describe the bug

I apologize if this is not the correct place to report this.  But I was just about to start using the one of the extension components and when I went to the showcase to get the documentation I found that I was getting the 503 error for the site.

Will it be back up soon or is there an alternative location for getting the documentation for the extension components?

### PrimeFaces Extensions version

11.0.6

**Comment by melloware** [comment]
No worries yep I am working with PrimeTek to get it deployed hopefully it will be up sometime tonight.

**Comment by SteveIreland** [comment]
Would this also have something to do with the reason that xmlns:pe="http://primefaces.org/ui/extensions" is showing as "not a valid registered URI"?

**Comment by melloware** [comment]
mhmm i don't think so I can download the 12.0.0 showcase here: https://search.maven.org/artifact/org.primefaces.extensions/primefaces-extensions-showcase/12.0.0/war

Then download Jetty standalone and drop that WAR in the `/webapps` folder and run `java -jar start.jar` to start Jetty and it starts and runs fine.  There is some issue on the PrimeTek end.

**Comment by SteveIreland** [comment]
Thanks for the response.  After eliminating that possibility I found I hand mangled my updates to the pom.xml file so the URI is now working as expected.

**Comment by melloware** [comment]
IT is back: https://www.primefaces.org/showcase-ext/views/home.jsf
