### ISSUE TITLE
TimeAgo: support OffsetDateTime

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#972]

**Comment by fcorneli** [comment]
Would be nice if `timeAgo` also had an option to stop saying "... ago" after a certain period.
For example, after a year, it's kind of pointless to see "more than 1 year ago". Here displaying the actual date might be more interesting.

**Comment by jepsar** [comment]
@fcorneli I'll see if it can easily be done without having to change the original library. Also it should support conversion in that case. I don't want to reinvent the wheel there.

**Comment by fcorneli** [comment]
@jepsar Seems like there is a `cutoff` option.
https://github.com/rmm5t/jquery-timeago#settings

**Comment by jepsar** [comment]
@fcorneli You can set the cutoff setting using JavaScript. I don't think this is a per instance setting, so it would not make sense to create an attribute for it.
