### ISSUE TITLE
Sheet: Empty Cell not set null value on BackingBean

### ISSUE THREAD

**Issue by AlessandroRugi** [primefaces-extensions/primefaces-extensions#975]
### Describe the bug

Hi,

we found an issue recently introduced working on [Issue 886](https://github.com/primefaces-extensions/primefaces-extensions/issues/886). When a cell containing a value is blanked the value remains in the backing bean and when the row is updated is shown again. 

We have a possible solution for this problem.

Create a new Interface to mark a value to be removed 
```
public interface ToBeRemoved{
} 
```
Update class Sheet.java method setLocalValue in that way (in the localValues map an entry is required for each field to be updated)
```
public void setLocalValue(final String rowKey, final int col, final Object value) {
    final SheetRowColIndex key = new SheetRowColIndex(rowKey, col);
    if (value != null) {
        localValues.put(key, value);
    } else {
       localValues.put(key, ToBeRemoved.class);
    }
}
```
Update method updateModel to assign the variable newValue in that way (to set to null the value to be removed)
```
final Object newValue = ToBeRemoved.class.equals(entry.getValue()) ? null : entry.getValue();
```

### Reproducer

1. Go to the pe:sheet [showcase](https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf), basic usage
2. Select the cell on row 1, column Type
![ss1](https://user-images.githubusercontent.com/48560663/196967951-b6a55140-53ef-41fa-9c33-f87b0ed0b0eb.png)

3. Click Del to remove the value 'SERVER' from the cell.
     - Verify this cell is now empty
![ss2](https://user-images.githubusercontent.com/48560663/196967961-e5dee3a8-a04b-48d3-bc3c-8e5edf390c82.png)

4. Click the selected checkbox in the column Active on row 1, the row is updated
    - Verify that  on cell on row 1, column Active the checkbox is unchecked
    - Verify that  on cell on row 1, column Type the value 'SERVER' is shown again
![ss3](https://user-images.githubusercontent.com/48560663/196967963-bd068fd1-3db9-4c04-906f-37cf1392f85d.png)

### Expected behavior

1. Go to the pe:sheet [showcase](https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf), basic usage
2. Select the cell on row 1, column Type
3. Click Del to remove the value 'SERVER' from the cell.
     - Verify this cell is now empty
4. Click the selected checkbox in the column Active on row 1, the row is updated
    - Verify that  on cell on row 1, column Active the checkbox is unchecked
    - Verify that  on cell on row 1, column Type remains empty

### PrimeFaces Extensions version

11.0.6

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
cc @eduarddrenth 

He fixed 886 and he is my most active Sheet user 😄

**Comment by melloware** [comment]
@AlessandroRugi feel free to submit a PR for review.

**Comment by AlessandroRugi** [comment]
@melloware I've created the [pull request](https://github.com/primefaces-extensions/primefaces-extensions/pull/976#issue-1418499563)

**Comment by eduarddrenth** [comment]
I can confirm this issue in my test environment, thanks!

**Comment by eduarddrenth** [comment]
Does 12.0.1 contain the pr for this issue? I am running 12.0.1 in my test env and see values not being stored. I will investigate, perhaps it is me

**Comment by eduarddrenth** [comment]
12.0.1 doesn't contain the fix so to see, I'll be patient

**Comment by melloware** [comment]
No it's in 12.02 which I didn't release yet.  I can release today

**Comment by eduarddrenth** [comment]
comming week or so is fine for me, thnx

**Comment by melloware** [comment]
12.0.2 is now in Maven Central!

**Comment by eduarddrenth** [comment]
and using it....
