### ISSUE TITLE
MasterDetail: Option to hide breadCrumb if level 1

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions#982]
### Describe the feature you would like to see added

The breadcrumb just with the "home" icon has not much value to the user if the user if he stays on the main page. It even takes up space at the top and depending on theme a not so "nice" and almost empty bar is shown.

This is very often the use case if he just wants to see / filter or edit items using row-edit or cell-edit functionality. 

For example we use masterdetail now in editing stock of an online shop and most user interactions are not with the detail levels. Only advanced editing is done there.

The UI would look nicer if it would be hidden at the main/first level.

### Describe the solution you'd like

A new flag "showBreadcrumbMainLevel" or "showBreadcrumbFirstLevel" with default _true_ for backwards compatibility would be a great option. If its _false_ and we are at level 1 the breadcrumb is not rendered.

**Comment by melloware** [comment]
Went with `showBreadcrumbFirstLevel` as the property name

**Comment by djmj** [comment]
Thank you for your quick implementation. Looking forward to it in production!
