### ISSUE TITLE
Clipboard: CSP issue

### ISSUE THREAD

**Issue by xLevision** [primefaces-extensions/primefaces-extensions#998]
### Describe the bug

```
<pe:clipboard>
    <p:ajax .../> 
</pe:clipboard>

```
The <p:ajax> call triggering CSP:
Refused to execute inline script because it violates the following CSP directive: "script-src 'self'".
Using default primefaces CSP. The copy is working, but it throw an error when i want to show something in growl.

### Reproducer

[pfe-998.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/10104427/pfe-998.zip)

### PrimeFaces Extensions version

12.0.0

### JSF implementation

Mojarra

**Comment by melloware** [comment]
cc @mihaiDumea in case you were interested!

**Comment by melloware** [comment]
Here is what the AJAX response is that is failing.

```xml
<?xml version='1.0' encoding='utf-8'?>
<partial-response><changes><update id="growl"><![CDATA[<span id="growl"></span><script id="growl_s" type="text/javascript" nonce="MzdhM2VkOWQtMWM4YS00ZjlmLWJkOGUtNTYwNmFjODlhMTZl">PrimeFaces.cw("Growl","growl",{id:"growl",sticky:false,life:6000,escape:true,keepAlive:false,msgs:[{summary:"Success",detail:"Copied to clipboard",severity:'info',severityText:'Information'}]});</script>]]></update><update id="j_id1:javax.faces.ViewState:0"><![CDATA[-4459800465616584619:-2817074877395722102]]></update><eval><![CDATA[if(window.PrimeFaces){PrimeFaces.csp.init('MzdhM2VkOWQtMWM4YS00ZjlmLWJkOGUtNTYwNmFjODlhMTZl');};;]]></eval></changes></partial-response>
```

**Comment by melloware** [comment]
Closing in favor of: https://github.com/primefaces/primefaces/issues/9453
